using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.JSInterop;

namespace Lumeo.Docs.Services;

public sealed class RegistryService(HttpClient http, IJSRuntime js)
{
    private static readonly JsonSerializerOptions JsonOpts =
        new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    private Registry? _cached;
    private readonly SemaphoreSlim _gate = new(1, 1);

    public async Task<Registry> GetAsync()
    {
        if (_cached is not null) return _cached;
        await _gate.WaitAsync();
        try
        {
            if (_cached is not null) return _cached;

            // Prefer registry data inlined into the prerendered catalog HTML.
            // It's available synchronously, so on hydration the catalog renders
            // populated on its first pass instead of flashing a skeleton — which
            // otherwise caused a large layout shift (CLS) when the grid was
            // replaced and re-rendered. Falls back to fetching /registry.json.
            _cached = ReadInline();
            if (_cached is not null) return _cached;

            _cached = await http.GetFromJsonAsync<Registry>("registry.json", JsonOpts)
                ?? throw new InvalidOperationException("registry.json failed to deserialize.");
            Hydrate(_cached);
            return _cached;
        }
        finally { _gate.Release(); }
    }

    private Registry? ReadInline()
    {
        try
        {
            if (js is not IJSInProcessRuntime ip) return null;
            var json = ip.Invoke<string?>("lumeo.readInlineRegistry");
            if (string.IsNullOrWhiteSpace(json)) return null;
            var registry = JsonSerializer.Deserialize<Registry>(json, JsonOpts);
            if (registry is null || registry.Components.Count == 0) return null;
            Hydrate(registry);
            return registry;
        }
        catch
        {
            // Any interop/parse failure: fall back to the HTTP fetch path.
            return null;
        }
    }

    private static void Hydrate(Registry registry)
    {
        foreach (var (key, comp) in registry.Components)
        {
            comp.Slug = key;
        }
    }

    public async Task<Dictionary<string, List<RegistryComponent>>> GroupsByCategoryAsync()
    {
        var registry = await GetAsync();
        // Show every component in the catalog. Undocumented ones (HasDocsPage = false) render
        // with a "Coming soon" badge and no link — handled by CatalogCard. This way the user sees
        // the full library at a glance and never silently loses a component just because its docs
        // page hasn't been written yet.
        return registry.Components.Values
            .GroupBy(c => c.Category)
            .ToDictionary(g => g.Key, g => g.OrderBy(c => c.Name).ToList());
    }
}

public sealed class Registry
{
    [JsonPropertyName("components")] public Dictionary<string, RegistryComponent> Components { get; set; } = new();
}

public sealed class RegistryComponent
{
    [JsonPropertyName("name")] public string Name { get; set; } = "";
    [JsonPropertyName("category")] public string Category { get; set; } = "";
    [JsonPropertyName("subcategory")] public string? Subcategory { get; set; }
    [JsonPropertyName("description")] public string Description { get; set; } = "";
    [JsonPropertyName("thumbnail")] public string? Thumbnail { get; set; }
    [JsonPropertyName("nugetPackage")] public string NugetPackage { get; set; } = "";
    [JsonPropertyName("hasDocsPage")] public bool HasDocsPage { get; set; }
    [JsonPropertyName("testCoverage")] public TestCoverageInfo? TestCoverage { get; set; }
    [JsonIgnore] public string Slug { get; set; } = "";
}

/// <summary>
/// Per-component test-coverage snapshot generated by Lumeo.RegistryGen from the real
/// test sources (bUnit .cs/.razor + the browser E2E suite). Surfaced in the docs so
/// devs can see at a glance what has been battle-tested. See the component page's
/// &lt;TestCoverage&gt; panel and the /test-coverage overview.
/// </summary>
public sealed class TestCoverageInfo
{
    /// <summary>0 = render-smoke only … 4 = real-browser E2E.</summary>
    [JsonPropertyName("tier")] public int Tier { get; set; }
    [JsonPropertyName("files")] public int Files { get; set; }
    [JsonPropertyName("tests")] public int Tests { get; set; }
    [JsonPropertyName("render")] public bool Render { get; set; }
    [JsonPropertyName("behavior")] public bool Behavior { get; set; }
    [JsonPropertyName("a11y")] public bool A11y { get; set; }
    [JsonPropertyName("keyboard")] public bool Keyboard { get; set; }
    [JsonPropertyName("scale")] public bool Scale { get; set; }
    [JsonPropertyName("e2e")] public bool E2e { get; set; }
    /// <summary>"smoke" = covered by the universal render-contract test;
    /// "excluded"/"skipped" = NOT smoke-rendered by it (has its own tests instead).</summary>
    [JsonPropertyName("contract")] public string Contract { get; set; } = "";

    public string TierLabel => Tier switch
    {
        4 => "E2E + a11y",
        3 => "A11y + behavior",
        2 => "Behavior",
        1 => "Render + props",
        _ => "Smoke",
    };
}
