"""Generates the localization key catalogue the docs show on /docs/localization.

Reads the English and German dictionaries in LumeoDefaultStrings.cs and the twelve locale
files, and writes docs/Lumeo.Docs/Data/LocalizationKeyCatalog.g.cs: every key with its
English default, the German text, and which shipped locales carry it. A host that adds a
culture Lumeo does not ship (Croatian, say) starts from this list with
LumeoLocalizationOptions.AddMany. Run from the repo root: python scripts/i18n/generate-key-catalog.py
"""
import io, os, re, sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
loc = os.path.join(root, "src/Lumeo/Services/Localization")
ENTRY = re.compile(r'\["([^"\]]+)"\]\s*=\s*"((?:[^"\\]|\\.)*)"')


def dictionaries(path):
    """Yields (name, {key: value}) for every `static readonly IReadOnlyDictionary<string, string> Name = new ... { ... };` block."""
    s = io.open(path, encoding="utf-8").read()
    for m in re.finditer(r"IReadOnlyDictionary<string, string> (\w+) = new Dictionary<string, string>[^{]*\{(.*?)\n\s*\};", s, re.S):
        yield m.group(1), dict(ENTRY.findall(m.group(2)))


base = dict(dictionaries(os.path.join(loc, "LumeoDefaultStrings.cs")))
en, de = base["En"], base.get("De", {})
locales = {}
for f in sorted(os.listdir(os.path.join(loc, "Locales"))):
    if not f.endswith(".cs"):
        continue
    for name, d in dictionaries(os.path.join(loc, "Locales", f)):
        locales[name] = d

def esc(v):
    return v.replace("\\", "\\\\").replace('"', '\\"')

lines = []
for key in sorted(en):
    have = [n for n, d in locales.items() if key in d]
    lines.append(f'        new("{esc(key)}", "{esc(en[key])}", "{esc(de.get(key, ""))}", {len(have) + (1 if key in de else 0) + 1}),')

out = f"""// <auto-generated> by scripts/i18n/generate-key-catalog.py from LumeoDefaultStrings.cs; do not edit. </auto-generated>
namespace Lumeo.Docs.Data;

/// <summary>Every ILumeoLocalizer key with its English default, the German text and the number of
/// shipped locales (of {len(locales) + 2}) that carry it. Rendered on /docs/localization.</summary>
public static class LocalizationKeyCatalog
{{
    public sealed record Entry(string Key, string English, string German, int Locales);

    public const int ShippedLocales = {len(locales) + 2};

    public static readonly IReadOnlyList<Entry> Entries =
    [
{chr(10).join(lines)}
    ];
}}
"""
target = os.path.join(root, "docs/Lumeo.Docs/Data/LocalizationKeyCatalog.g.cs")
os.makedirs(os.path.dirname(target), exist_ok=True)
io.open(target, "w", encoding="utf-8", newline="\r\n").write(out)
print(f"{len(en)} keys, {len(locales) + 2} locales -> {os.path.relpath(target, root)}")
