// <auto-generated />
// Lucide icons — ISC License.
// https://github.com/lucide-icons/lucide
// 
// ISC License
// 
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of
// Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
// 
// Permission to use, copy, modify, and/or distribute this software for any purpose with or
// without fee is hereby granted, provided that the above copyright notice and this permission
// notice appear in all copies.
// 
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO
// THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT
// SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR
// ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
// CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
// OR PERFORMANCE OF THIS SOFTWARE.
// Source: Lucide v1.23.0
// Generated by tools/Lumeo.IconGen — DO NOT EDIT BY HAND.
#nullable enable

namespace Lumeo.Icons;

public static partial class Lucide
{
    /// <summary>Lucide <c>sticky-note-x</c>.</summary>
    public static global::Lumeo.IconSource StickyNoteX => global::Lumeo.IconSource.Stroke("<path d=\"M15 3v5a1 1 0 0 0 1 1h5\" /><path d=\"m16 16 5 5\" /><path d=\"M21 12V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7\" /><path d=\"m21 16-5 5\" />");
    /// <summary>Lucide <c>sticky-notes</c>.</summary>
    public static global::Lumeo.IconSource StickyNotes => global::Lumeo.IconSource.Stroke("<path d=\"M10 8a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 16 14v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 2-2z\" /><path d=\"M10 8v5a1 1 0 0 0 1 1h5\" /><path d=\"M8 4a2 2 0 0 1 2-2h6a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 22 8v6a2 2 0 0 1-2 2\" /><path d=\"M16 2v5a1 1 0 0 0 1 1h5\" />");
    /// <summary>Lucide <c>stone</c>.</summary>
    public static global::Lumeo.IconSource Stone => global::Lumeo.IconSource.Stroke("<path d=\"M11.264 2.205A4 4 0 0 0 6.42 4.211l-4 8a4 4 0 0 0 1.359 5.117l6 4a4 4 0 0 0 4.438 0l6-4a4 4 0 0 0 1.576-4.592l-2-6a4 4 0 0 0-2.53-2.53z\" /><path d=\"M11.99 22 14 12l7.822 3.184\" /><path d=\"M14 12 8.47 2.302\" />");
    /// <summary>Lucide <c>store</c>.</summary>
    public static global::Lumeo.IconSource Store => global::Lumeo.IconSource.Stroke("<path d=\"M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5\" /><path d=\"M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244\" /><path d=\"M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05\" />");
    /// <summary>Lucide <c>stretch-horizontal</c>.</summary>
    public static global::Lumeo.IconSource StretchHorizontal => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"6\" x=\"2\" y=\"4\" rx=\"2\" /><rect width=\"20\" height=\"6\" x=\"2\" y=\"14\" rx=\"2\" />");
    /// <summary>Lucide <c>stretch-vertical</c>.</summary>
    public static global::Lumeo.IconSource StretchVertical => global::Lumeo.IconSource.Stroke("<rect width=\"6\" height=\"20\" x=\"4\" y=\"2\" rx=\"2\" /><rect width=\"6\" height=\"20\" x=\"14\" y=\"2\" rx=\"2\" />");
    /// <summary>Lucide <c>strikethrough</c>.</summary>
    public static global::Lumeo.IconSource Strikethrough => global::Lumeo.IconSource.Stroke("<path d=\"M16 4H9a3 3 0 0 0-2.83 4\" /><path d=\"M14 12a4 4 0 0 1 0 8H6\" /><line x1=\"4\" x2=\"20\" y1=\"12\" y2=\"12\" />");
    /// <summary>Lucide <c>subscript</c>.</summary>
    public static global::Lumeo.IconSource Subscript => global::Lumeo.IconSource.Stroke("<path d=\"m4 5 8 8\" /><path d=\"m12 5-8 8\" /><path d=\"M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07\" />");
    /// <summary>Lucide <c>summary</c>.</summary>
    public static global::Lumeo.IconSource Summary => global::Lumeo.IconSource.Stroke("<path d=\"M15 4H7\" /><path d=\"m18 16 3 3-3 3\" /><path d=\"M3 4v13a2 2 0 0 0 2 2h16\" /><path d=\"M7 14h7\" /><path d=\"M7 9h12\" />");
    /// <summary>Lucide <c>sun</c>.</summary>
    public static global::Lumeo.IconSource Sun => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M12 2v2\" /><path d=\"M12 20v2\" /><path d=\"m4.93 4.93 1.41 1.41\" /><path d=\"m17.66 17.66 1.41 1.41\" /><path d=\"M2 12h2\" /><path d=\"M20 12h2\" /><path d=\"m6.34 17.66-1.41 1.41\" /><path d=\"m19.07 4.93-1.41 1.41\" />");
    /// <summary>Lucide <c>sun-dim</c>.</summary>
    public static global::Lumeo.IconSource SunDim => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M12 4h.01\" /><path d=\"M20 12h.01\" /><path d=\"M12 20h.01\" /><path d=\"M4 12h.01\" /><path d=\"M17.657 6.343h.01\" /><path d=\"M17.657 17.657h.01\" /><path d=\"M6.343 17.657h.01\" /><path d=\"M6.343 6.343h.01\" />");
    /// <summary>Lucide <c>sun-medium</c>.</summary>
    public static global::Lumeo.IconSource SunMedium => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M12 3v1\" /><path d=\"M12 20v1\" /><path d=\"M3 12h1\" /><path d=\"M20 12h1\" /><path d=\"m18.364 5.636-.707.707\" /><path d=\"m6.343 17.657-.707.707\" /><path d=\"m5.636 5.636.707.707\" /><path d=\"m17.657 17.657.707.707\" />");
    /// <summary>Lucide <c>sun-moon</c>.</summary>
    public static global::Lumeo.IconSource SunMoon => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v2\" /><path d=\"M14.837 16.385a6 6 0 1 1-7.223-7.222c.624-.147.97.66.715 1.248a4 4 0 0 0 5.26 5.259c.589-.255 1.396.09 1.248.715\" /><path d=\"M16 12a4 4 0 0 0-4-4\" /><path d=\"m19 5-1.256 1.256\" /><path d=\"M20 12h2\" />");
    /// <summary>Lucide <c>sun-snow</c>.</summary>
    public static global::Lumeo.IconSource SunSnow => global::Lumeo.IconSource.Stroke("<path d=\"M10 21v-1\" /><path d=\"M10 4V3\" /><path d=\"M10 9a3 3 0 0 0 0 6\" /><path d=\"m14 20 1.25-2.5L18 18\" /><path d=\"m14 4 1.25 2.5L18 6\" /><path d=\"m17 21-3-6 1.5-3H22\" /><path d=\"m17 3-3 6 1.5 3\" /><path d=\"M2 12h1\" /><path d=\"m20 10-1.5 2 1.5 2\" /><path d=\"m3.64 18.36.7-.7\" /><path d=\"m4.34 6.34-.7-.7\" />");
    /// <summary>Lucide <c>sunrise</c>.</summary>
    public static global::Lumeo.IconSource Sunrise => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v8\" /><path d=\"m4.93 10.93 1.41 1.41\" /><path d=\"M2 18h2\" /><path d=\"M20 18h2\" /><path d=\"m19.07 10.93-1.41 1.41\" /><path d=\"M22 22H2\" /><path d=\"m8 6 4-4 4 4\" /><path d=\"M16 18a4 4 0 0 0-8 0\" />");
    /// <summary>Lucide <c>sunset</c>.</summary>
    public static global::Lumeo.IconSource Sunset => global::Lumeo.IconSource.Stroke("<path d=\"M12 10V2\" /><path d=\"m4.93 10.93 1.41 1.41\" /><path d=\"M2 18h2\" /><path d=\"M20 18h2\" /><path d=\"m19.07 10.93-1.41 1.41\" /><path d=\"M22 22H2\" /><path d=\"m16 6-4 4-4-4\" /><path d=\"M16 18a4 4 0 0 0-8 0\" />");
    /// <summary>Lucide <c>superscript</c>.</summary>
    public static global::Lumeo.IconSource Superscript => global::Lumeo.IconSource.Stroke("<path d=\"m4 19 8-8\" /><path d=\"m12 19-8-8\" /><path d=\"M20 12h-4c0-1.5.442-2 1.5-2.5S20 8.334 20 7.002c0-.472-.17-.93-.484-1.29a2.105 2.105 0 0 0-2.617-.436c-.42.239-.738.614-.899 1.06\" />");
    /// <summary>Lucide <c>swatch-book</c>.</summary>
    public static global::Lumeo.IconSource SwatchBook => global::Lumeo.IconSource.Stroke("<path d=\"M11 17a4 4 0 0 1-8 0V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2Z\" /><path d=\"M16.7 13H19a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H7\" /><path d=\"M 7 17h.01\" /><path d=\"m11 8 2.3-2.3a2.4 2.4 0 0 1 3.404.004L18.6 7.6a2.4 2.4 0 0 1 .026 3.434L9.9 19.8\" />");
    /// <summary>Lucide <c>swiss-franc</c>.</summary>
    public static global::Lumeo.IconSource SwissFranc => global::Lumeo.IconSource.Stroke("<path d=\"M10 21V3h8\" /><path d=\"M6 16h9\" /><path d=\"M10 9.5h7\" />");
    /// <summary>Lucide <c>switch-camera</c>.</summary>
    public static global::Lumeo.IconSource SwitchCamera => global::Lumeo.IconSource.Stroke("<path d=\"M11 19H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5\" /><path d=\"M13 5h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-5\" /><circle cx=\"12\" cy=\"12\" r=\"3\" /><path d=\"m18 22-3-3 3-3\" /><path d=\"m6 2 3 3-3 3\" />");
    /// <summary>Lucide <c>sword</c>.</summary>
    public static global::Lumeo.IconSource Sword => global::Lumeo.IconSource.Stroke("<path d=\"m11 19-6-6\" /><path d=\"m5 21-2-2\" /><path d=\"m8 16-4 4\" /><path d=\"M9.5 17.5 21 6V3h-3L6.5 14.5\" />");
    /// <summary>Lucide <c>swords</c>.</summary>
    public static global::Lumeo.IconSource Swords => global::Lumeo.IconSource.Stroke("<polyline points=\"14.5 17.5 3 6 3 3 6 3 17.5 14.5\" /><line x1=\"13\" x2=\"19\" y1=\"19\" y2=\"13\" /><line x1=\"16\" x2=\"20\" y1=\"16\" y2=\"20\" /><line x1=\"19\" x2=\"21\" y1=\"21\" y2=\"19\" /><polyline points=\"14.5 6.5 18 3 21 3 21 6 17.5 9.5\" /><line x1=\"5\" x2=\"9\" y1=\"14\" y2=\"18\" /><line x1=\"7\" x2=\"4\" y1=\"17\" y2=\"20\" /><line x1=\"3\" x2=\"5\" y1=\"19\" y2=\"21\" />");
    /// <summary>Lucide <c>syringe</c>.</summary>
    public static global::Lumeo.IconSource Syringe => global::Lumeo.IconSource.Stroke("<path d=\"m18 2 4 4\" /><path d=\"m17 7 3-3\" /><path d=\"M19 9 8.7 19.3c-1 1-2.5 1-3.4 0l-.6-.6c-1-1-1-2.5 0-3.4L15 5\" /><path d=\"m9 11 4 4\" /><path d=\"m5 19-3 3\" /><path d=\"m14 4 6 6\" />");
    /// <summary>Lucide <c>table</c>.</summary>
    public static global::Lumeo.IconSource Table => global::Lumeo.IconSource.Stroke("<path d=\"M12 3v18\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M3 9h18\" /><path d=\"M3 15h18\" />");
    /// <summary>Lucide <c>table-2</c>.</summary>
    public static global::Lumeo.IconSource Table2 => global::Lumeo.IconSource.Stroke("<path d=\"M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18\" />");
    /// <summary>Lucide <c>table-cells-merge</c>.</summary>
    public static global::Lumeo.IconSource TableCellsMerge => global::Lumeo.IconSource.Stroke("<path d=\"M12 21v-6\" /><path d=\"M12 9V3\" /><path d=\"M3 15h18\" /><path d=\"M3 9h18\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />");
    /// <summary>Lucide <c>table-cells-split</c>.</summary>
    public static global::Lumeo.IconSource TableCellsSplit => global::Lumeo.IconSource.Stroke("<path d=\"M12 15V9\" /><path d=\"M3 15h18\" /><path d=\"M3 9h18\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />");
    /// <summary>Lucide <c>table-columns-split</c>.</summary>
    public static global::Lumeo.IconSource TableColumnsSplit => global::Lumeo.IconSource.Stroke("<path d=\"M14 14v2\" /><path d=\"M14 20v2\" /><path d=\"M14 2v2\" /><path d=\"M14 8v2\" /><path d=\"M2 15h8\" /><path d=\"M2 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H2\" /><path d=\"M2 9h8\" /><path d=\"M22 15h-4\" /><path d=\"M22 3h-2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h2\" /><path d=\"M22 9h-4\" /><path d=\"M5 3v18\" />");
    /// <summary>Lucide <c>table-of-contents</c>.</summary>
    public static global::Lumeo.IconSource TableOfContents => global::Lumeo.IconSource.Stroke("<path d=\"M16 5H3\" /><path d=\"M16 12H3\" /><path d=\"M16 19H3\" /><path d=\"M21 5h.01\" /><path d=\"M21 12h.01\" /><path d=\"M21 19h.01\" />");
    /// <summary>Lucide <c>table-properties</c>.</summary>
    public static global::Lumeo.IconSource TableProperties => global::Lumeo.IconSource.Stroke("<path d=\"M15 3v18\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M21 9H3\" /><path d=\"M21 15H3\" />");
    /// <summary>Lucide <c>table-rows-split</c>.</summary>
    public static global::Lumeo.IconSource TableRowsSplit => global::Lumeo.IconSource.Stroke("<path d=\"M14 10h2\" /><path d=\"M15 22v-8\" /><path d=\"M15 2v4\" /><path d=\"M2 10h2\" /><path d=\"M20 10h2\" /><path d=\"M3 19h18\" /><path d=\"M3 22v-6a2 2 135 0 1 2-2h14a2 2 45 0 1 2 2v6\" /><path d=\"M3 2v2a2 2 45 0 0 2 2h14a2 2 135 0 0 2-2V2\" /><path d=\"M8 10h2\" /><path d=\"M9 22v-8\" /><path d=\"M9 2v4\" />");
    /// <summary>Lucide <c>tablet</c>.</summary>
    public static global::Lumeo.IconSource Tablet => global::Lumeo.IconSource.Stroke("<rect width=\"16\" height=\"20\" x=\"4\" y=\"2\" rx=\"2\" ry=\"2\" /><line x1=\"12\" x2=\"12.01\" y1=\"18\" y2=\"18\" />");
    /// <summary>Lucide <c>tablet-smartphone</c>.</summary>
    public static global::Lumeo.IconSource TabletSmartphone => global::Lumeo.IconSource.Stroke("<rect width=\"10\" height=\"14\" x=\"3\" y=\"8\" rx=\"2\" /><path d=\"M5 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2h-2.4\" /><path d=\"M8 18h.01\" />");
    /// <summary>Lucide <c>tablets</c>.</summary>
    public static global::Lumeo.IconSource Tablets => global::Lumeo.IconSource.Stroke("<circle cx=\"7\" cy=\"7\" r=\"5\" /><circle cx=\"17\" cy=\"17\" r=\"5\" /><path d=\"M12 17h10\" /><path d=\"m3.46 10.54 7.08-7.08\" />");
    /// <summary>Lucide <c>tag</c>.</summary>
    public static global::Lumeo.IconSource Tag => global::Lumeo.IconSource.Stroke("<path d=\"M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>tag-plus</c>.</summary>
    public static global::Lumeo.IconSource TagPlus => global::Lumeo.IconSource.Stroke("<path d=\"M16 13h6\" /><path d=\"m16.5 6.5-3.914-3.914A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l1.79-1.79\" /><path d=\"M19 10v6\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>tag-x</c>.</summary>
    public static global::Lumeo.IconSource TagX => global::Lumeo.IconSource.Stroke("<path d=\"m16.5 6.5-3.914-3.914A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.43 2.43 0 0 0 3.42 0l1.79-1.79\" /><path d=\"m16.5 10.5 5 5\" /><path d=\"m21.5 10.5-5 5\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>tags</c>.</summary>
    public static global::Lumeo.IconSource Tags => global::Lumeo.IconSource.Stroke("<path d=\"M13.172 2a2 2 0 0 1 1.414.586l6.71 6.71a2.4 2.4 0 0 1 0 3.408l-4.592 4.592a2.4 2.4 0 0 1-3.408 0l-6.71-6.71A2 2 0 0 1 6 9.172V3a1 1 0 0 1 1-1z\" /><path d=\"M2 7v6.172a2 2 0 0 0 .586 1.414l6.71 6.71a2.4 2.4 0 0 0 3.191.193\" /><circle cx=\"10.5\" cy=\"6.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>tally-1</c>.</summary>
    public static global::Lumeo.IconSource Tally1 => global::Lumeo.IconSource.Stroke("<path d=\"M4 4v16\" />");
    /// <summary>Lucide <c>tally-2</c>.</summary>
    public static global::Lumeo.IconSource Tally2 => global::Lumeo.IconSource.Stroke("<path d=\"M4 4v16\" /><path d=\"M9 4v16\" />");
    /// <summary>Lucide <c>tally-3</c>.</summary>
    public static global::Lumeo.IconSource Tally3 => global::Lumeo.IconSource.Stroke("<path d=\"M4 4v16\" /><path d=\"M9 4v16\" /><path d=\"M14 4v16\" />");
    /// <summary>Lucide <c>tally-4</c>.</summary>
    public static global::Lumeo.IconSource Tally4 => global::Lumeo.IconSource.Stroke("<path d=\"M4 4v16\" /><path d=\"M9 4v16\" /><path d=\"M14 4v16\" /><path d=\"M19 4v16\" />");
    /// <summary>Lucide <c>tally-5</c>.</summary>
    public static global::Lumeo.IconSource Tally5 => global::Lumeo.IconSource.Stroke("<path d=\"M4 4v16\" /><path d=\"M9 4v16\" /><path d=\"M14 4v16\" /><path d=\"M19 4v16\" /><path d=\"M22 6 2 18\" />");
    /// <summary>Lucide <c>tangent</c>.</summary>
    public static global::Lumeo.IconSource Tangent => global::Lumeo.IconSource.Stroke("<circle cx=\"17\" cy=\"4\" r=\"2\" /><path d=\"M15.59 5.41 5.41 15.59\" /><circle cx=\"4\" cy=\"17\" r=\"2\" /><path d=\"M12 22s-4-9-1.5-11.5S22 12 22 12\" />");
    /// <summary>Lucide <c>target</c>.</summary>
    public static global::Lumeo.IconSource Target => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><circle cx=\"12\" cy=\"12\" r=\"6\" /><circle cx=\"12\" cy=\"12\" r=\"2\" />");
    /// <summary>Lucide <c>telescope</c>.</summary>
    public static global::Lumeo.IconSource Telescope => global::Lumeo.IconSource.Stroke("<path d=\"m10.065 12.493-6.18 1.318a.934.934 0 0 1-1.108-.702l-.537-2.15a1.07 1.07 0 0 1 .691-1.265l13.504-4.44\" /><path d=\"m13.56 11.747 4.332-.924\" /><path d=\"m16 21-3.105-6.21\" /><path d=\"M16.485 5.94a2 2 0 0 1 1.455-2.425l1.09-.272a1 1 0 0 1 1.212.727l1.515 6.06a1 1 0 0 1-.727 1.213l-1.09.272a2 2 0 0 1-2.425-1.455z\" /><path d=\"m6.158 8.633 1.114 4.456\" /><path d=\"m8 21 3.105-6.21\" /><circle cx=\"12\" cy=\"13\" r=\"2\" />");
    /// <summary>Lucide <c>tent</c>.</summary>
    public static global::Lumeo.IconSource Tent => global::Lumeo.IconSource.Stroke("<path d=\"M3.5 21 14 3\" /><path d=\"M20.5 21 10 3\" /><path d=\"M15.5 21 12 15l-3.5 6\" /><path d=\"M2 21h20\" />");
    /// <summary>Lucide <c>tent-tree</c>.</summary>
    public static global::Lumeo.IconSource TentTree => global::Lumeo.IconSource.Stroke("<circle cx=\"4\" cy=\"4\" r=\"2\" /><path d=\"m14 5 3-3 3 3\" /><path d=\"m14 10 3-3 3 3\" /><path d=\"M17 14V2\" /><path d=\"M17 14H7l-5 8h20Z\" /><path d=\"M8 14v8\" /><path d=\"m9 14 5 8\" />");
    /// <summary>Lucide <c>terminal</c>.</summary>
    public static global::Lumeo.IconSource Terminal => global::Lumeo.IconSource.Stroke("<path d=\"M12 19h8\" /><path d=\"m4 17 6-6-6-6\" />");
    /// <summary>Lucide <c>test-tube</c>.</summary>
    public static global::Lumeo.IconSource TestTube => global::Lumeo.IconSource.Stroke("<path d=\"M14.5 2v17.5c0 1.4-1.1 2.5-2.5 2.5c-1.4 0-2.5-1.1-2.5-2.5V2\" /><path d=\"M8.5 2h7\" /><path d=\"M14.5 16h-5\" />");
    /// <summary>Lucide <c>test-tube-diagonal</c>.</summary>
    public static global::Lumeo.IconSource TestTubeDiagonal => global::Lumeo.IconSource.Stroke("<path d=\"M21 7 6.82 21.18a2.83 2.83 0 0 1-3.99-.01a2.83 2.83 0 0 1 0-4L17 3\" /><path d=\"m16 2 6 6\" /><path d=\"M12 16H4\" />");
    /// <summary>Lucide <c>test-tubes</c>.</summary>
    public static global::Lumeo.IconSource TestTubes => global::Lumeo.IconSource.Stroke("<path d=\"M9 2v17.5A2.5 2.5 0 0 1 6.5 22A2.5 2.5 0 0 1 4 19.5V2\" /><path d=\"M20 2v17.5a2.5 2.5 0 0 1-2.5 2.5a2.5 2.5 0 0 1-2.5-2.5V2\" /><path d=\"M3 2h7\" /><path d=\"M14 2h7\" /><path d=\"M9 16H4\" /><path d=\"M20 16h-5\" />");
    /// <summary>Lucide <c>text-align-center</c>.</summary>
    public static global::Lumeo.IconSource TextAlignCenter => global::Lumeo.IconSource.Stroke("<path d=\"M21 5H3\" /><path d=\"M17 12H7\" /><path d=\"M19 19H5\" />");
    /// <summary>Lucide <c>text-align-end</c>.</summary>
    public static global::Lumeo.IconSource TextAlignEnd => global::Lumeo.IconSource.Stroke("<path d=\"M21 5H3\" /><path d=\"M21 12H9\" /><path d=\"M21 19H7\" />");
    /// <summary>Lucide <c>text-align-justify</c>.</summary>
    public static global::Lumeo.IconSource TextAlignJustify => global::Lumeo.IconSource.Stroke("<path d=\"M3 5h18\" /><path d=\"M3 12h18\" /><path d=\"M3 19h18\" />");
    /// <summary>Lucide <c>text-align-start</c>.</summary>
    public static global::Lumeo.IconSource TextAlignStart => global::Lumeo.IconSource.Stroke("<path d=\"M21 5H3\" /><path d=\"M15 12H3\" /><path d=\"M17 19H3\" />");
    /// <summary>Lucide <c>text-cursor</c>.</summary>
    public static global::Lumeo.IconSource TextCursor => global::Lumeo.IconSource.Stroke("<path d=\"M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1\" /><path d=\"M7 22h1a4 4 0 0 0 4-4\" /><path d=\"M7 2h1a4 4 0 0 1 4 4\" />");
    /// <summary>Lucide <c>text-cursor-input</c>.</summary>
    public static global::Lumeo.IconSource TextCursorInput => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h-1a2 2 0 0 1-2-2 2 2 0 0 1-2 2H6\" /><path d=\"M13 8h7a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-7\" /><path d=\"M5 16H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h1\" /><path d=\"M6 4h1a2 2 0 0 1 2 2 2 2 0 0 1 2-2h1\" /><path d=\"M9 6v12\" />");
    /// <summary>Lucide <c>text-initial</c>.</summary>
    public static global::Lumeo.IconSource TextInitial => global::Lumeo.IconSource.Stroke("<path d=\"M15 5h6\" /><path d=\"M15 12h6\" /><path d=\"M3 19h18\" /><path d=\"m3 12 3.553-7.724a.5.5 0 0 1 .894 0L11 12\" /><path d=\"M3.92 10h6.16\" />");
    /// <summary>Lucide <c>text-quote</c>.</summary>
    public static global::Lumeo.IconSource TextQuote => global::Lumeo.IconSource.Stroke("<path d=\"M17 5H3\" /><path d=\"M21 12H8\" /><path d=\"M21 19H8\" /><path d=\"M3 12v7\" />");
    /// <summary>Lucide <c>text-search</c>.</summary>
    public static global::Lumeo.IconSource TextSearch => global::Lumeo.IconSource.Stroke("<path d=\"M21 5H3\" /><path d=\"M10 12H3\" /><path d=\"M10 19H3\" /><circle cx=\"17\" cy=\"15\" r=\"3\" /><path d=\"m21 19-1.9-1.9\" />");
    /// <summary>Lucide <c>text-wrap</c>.</summary>
    public static global::Lumeo.IconSource TextWrap => global::Lumeo.IconSource.Stroke("<path d=\"m16 16-3 3 3 3\" /><path d=\"M3 12h14.5a1 1 0 0 1 0 7H13\" /><path d=\"M3 19h6\" /><path d=\"M3 5h18\" />");
    /// <summary>Lucide <c>theater</c>.</summary>
    public static global::Lumeo.IconSource Theater => global::Lumeo.IconSource.Stroke("<path d=\"M2 10s3-3 3-8\" /><path d=\"M22 10s-3-3-3-8\" /><path d=\"M10 2c0 4.4-3.6 8-8 8\" /><path d=\"M14 2c0 4.4 3.6 8 8 8\" /><path d=\"M2 10s2 2 2 5\" /><path d=\"M22 10s-2 2-2 5\" /><path d=\"M8 15h8\" /><path d=\"M2 22v-1a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1\" /><path d=\"M14 22v-1a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1\" />");
    /// <summary>Lucide <c>thermometer</c>.</summary>
    public static global::Lumeo.IconSource Thermometer => global::Lumeo.IconSource.Stroke("<path d=\"M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z\" />");
    /// <summary>Lucide <c>thermometer-snowflake</c>.</summary>
    public static global::Lumeo.IconSource ThermometerSnowflake => global::Lumeo.IconSource.Stroke("<path d=\"m10 20-1.25-2.5L6 18\" /><path d=\"M10 4 8.75 6.5 6 6\" /><path d=\"M10.585 15H10\" /><path d=\"M2 12h6.5L10 9\" /><path d=\"M20 14.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z\" /><path d=\"m4 10 1.5 2L4 14\" /><path d=\"m7 21 3-6-1.5-3\" /><path d=\"m7 3 3 6h2\" />");
    /// <summary>Lucide <c>thermometer-sun</c>.</summary>
    public static global::Lumeo.IconSource ThermometerSun => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v2\" /><path d=\"M12 8a4 4 0 0 0-1.645 7.647\" /><path d=\"M2 12h2\" /><path d=\"M20 14.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z\" /><path d=\"m4.93 4.93 1.41 1.41\" /><path d=\"m6.34 17.66-1.41 1.41\" />");
    /// <summary>Lucide <c>thumbs-down</c>.</summary>
    public static global::Lumeo.IconSource ThumbsDown => global::Lumeo.IconSource.Stroke("<path d=\"M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z\" /><path d=\"M17 14V2\" />");
    /// <summary>Lucide <c>thumbs-up</c>.</summary>
    public static global::Lumeo.IconSource ThumbsUp => global::Lumeo.IconSource.Stroke("<path d=\"M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z\" /><path d=\"M7 10v12\" />");
    /// <summary>Lucide <c>ticket</c>.</summary>
    public static global::Lumeo.IconSource Ticket => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"M13 5v2\" /><path d=\"M13 17v2\" /><path d=\"M13 11v2\" />");
    /// <summary>Lucide <c>ticket-check</c>.</summary>
    public static global::Lumeo.IconSource TicketCheck => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"m9 12 2 2 4-4\" />");
    /// <summary>Lucide <c>ticket-minus</c>.</summary>
    public static global::Lumeo.IconSource TicketMinus => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"M9 12h6\" />");
    /// <summary>Lucide <c>ticket-percent</c>.</summary>
    public static global::Lumeo.IconSource TicketPercent => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 1 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 1 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"M9 9h.01\" /><path d=\"m15 9-6 6\" /><path d=\"M15 15h.01\" />");
    /// <summary>Lucide <c>ticket-plus</c>.</summary>
    public static global::Lumeo.IconSource TicketPlus => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"M9 12h6\" /><path d=\"M12 9v6\" />");
    /// <summary>Lucide <c>ticket-slash</c>.</summary>
    public static global::Lumeo.IconSource TicketSlash => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"m9.5 14.5 5-5\" />");
    /// <summary>Lucide <c>ticket-x</c>.</summary>
    public static global::Lumeo.IconSource TicketX => global::Lumeo.IconSource.Stroke("<path d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\" /><path d=\"m9.5 14.5 5-5\" /><path d=\"m9.5 9.5 5 5\" />");
    /// <summary>Lucide <c>tickets</c>.</summary>
    public static global::Lumeo.IconSource Tickets => global::Lumeo.IconSource.Stroke("<path d=\"m3.173 8.18 11-5a2 2 0 0 1 2.647.993L18.56 8\" /><path d=\"M6 10V8\" /><path d=\"M6 14v1\" /><path d=\"M6 19v2\" /><rect x=\"2\" y=\"8\" width=\"20\" height=\"13\" rx=\"2\" />");
    /// <summary>Lucide <c>tickets-plane</c>.</summary>
    public static global::Lumeo.IconSource TicketsPlane => global::Lumeo.IconSource.Stroke("<path d=\"M10.5 17h1.227a2 2 0 0 0 1.345-.52L18 12\" /><path d=\"m12 13.5 3.794.506\" /><path d=\"m3.173 8.18 11-5a2 2 0 0 1 2.647.993L18.56 8\" /><path d=\"M6 10V8\" /><path d=\"M6 14v1\" /><path d=\"M6 19v2\" /><rect x=\"2\" y=\"8\" width=\"20\" height=\"13\" rx=\"2\" />");
    /// <summary>Lucide <c>timeline</c>.</summary>
    public static global::Lumeo.IconSource Timeline => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h.01\" /><path d=\"M4 16h.01\" /><path d=\"M4 20h.01\" /><path d=\"M4 4h.01\" /><path d=\"M4 8h.01\" /><path d=\"M9.414 13.414a2 2 0 0 0 1.414.586H19a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-8.172a2 2 0 0 0-1.414.586L8 12z\" /><path d=\"M9.414 21.414a2 2 0 0 0 1.414.586H19a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-8.172a2 2 0 0 0-1.414.586L8 20z\" /><path d=\"M9.414 5.414A2 2 0 0 0 10.828 6H19a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1h-8.172a2 2 0 0 0-1.414.586L8 4z\" />");
    /// <summary>Lucide <c>timer</c>.</summary>
    public static global::Lumeo.IconSource Timer => global::Lumeo.IconSource.Stroke("<line x1=\"10\" x2=\"14\" y1=\"2\" y2=\"2\" /><line x1=\"12\" x2=\"15\" y1=\"14\" y2=\"11\" /><circle cx=\"12\" cy=\"14\" r=\"8\" />");
    /// <summary>Lucide <c>timer-off</c>.</summary>
    public static global::Lumeo.IconSource TimerOff => global::Lumeo.IconSource.Stroke("<path d=\"M10 2h4\" /><path d=\"M4.6 11a8 8 0 0 0 1.7 8.7 8 8 0 0 0 8.7 1.7\" /><path d=\"M7.4 7.4a8 8 0 0 1 10.3 1 8 8 0 0 1 .9 10.2\" /><path d=\"m2 2 20 20\" /><path d=\"M12 12v-2\" />");
    /// <summary>Lucide <c>timer-reset</c>.</summary>
    public static global::Lumeo.IconSource TimerReset => global::Lumeo.IconSource.Stroke("<path d=\"M10 2h4\" /><path d=\"M12 14v-4\" /><path d=\"M4 13a8 8 0 0 1 8-7 8 8 0 1 1-5.3 14L4 17.6\" /><path d=\"M9 17H4v5\" />");
    /// <summary>Lucide <c>toggle-left</c>.</summary>
    public static global::Lumeo.IconSource ToggleLeft => global::Lumeo.IconSource.Stroke("<circle cx=\"9\" cy=\"12\" r=\"3\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"5\" rx=\"7\" />");
    /// <summary>Lucide <c>toggle-right</c>.</summary>
    public static global::Lumeo.IconSource ToggleRight => global::Lumeo.IconSource.Stroke("<circle cx=\"15\" cy=\"12\" r=\"3\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"5\" rx=\"7\" />");
    /// <summary>Lucide <c>toilet</c>.</summary>
    public static global::Lumeo.IconSource Toilet => global::Lumeo.IconSource.Stroke("<path d=\"M7 12h13a1 1 0 0 1 1 1 5 5 0 0 1-5 5h-.598a.5.5 0 0 0-.424.765l1.544 2.47a.5.5 0 0 1-.424.765H5.402a.5.5 0 0 1-.424-.765L7 18\" /><path d=\"M8 18a5 5 0 0 1-5-5V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8\" />");
    /// <summary>Lucide <c>tool-case</c>.</summary>
    public static global::Lumeo.IconSource ToolCase => global::Lumeo.IconSource.Stroke("<path d=\"M10 15h4\" /><path d=\"m14.817 10.995-.971-1.45 1.034-1.232a2 2 0 0 0-2.025-3.238l-1.82.364L9.91 3.885a2 2 0 0 0-3.625.748L6.141 6.55l-1.725.426a2 2 0 0 0-.19 3.756l.657.27\" /><path d=\"m18.822 10.995 2.26-5.38a1 1 0 0 0-.557-1.318L16.954 2.9a1 1 0 0 0-1.281.533l-.924 2.122\" /><path d=\"M4 12.006A1 1 0 0 1 4.994 11H19a1 1 0 0 1 1 1v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z\" />");
    /// <summary>Lucide <c>toolbox</c>.</summary>
    public static global::Lumeo.IconSource Toolbox => global::Lumeo.IconSource.Stroke("<path d=\"M16 12v4\" /><path d=\"M16 6a2 2 0 0 1 1.414.586l4 4A2 2 0 0 1 22 12v7a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 .586-1.414l4-4A2 2 0 0 1 8 6z\" /><path d=\"M16 6V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2\" /><path d=\"M2 14h20\" /><path d=\"M8 12v4\" />");
    /// <summary>Lucide <c>tornado</c>.</summary>
    public static global::Lumeo.IconSource Tornado => global::Lumeo.IconSource.Stroke("<path d=\"M21 4H3\" /><path d=\"M18 8H6\" /><path d=\"M19 12H9\" /><path d=\"M16 16h-6\" /><path d=\"M11 20H9\" />");
    /// <summary>Lucide <c>torus</c>.</summary>
    public static global::Lumeo.IconSource Torus => global::Lumeo.IconSource.Stroke("<ellipse cx=\"12\" cy=\"11\" rx=\"3\" ry=\"2\" /><ellipse cx=\"12\" cy=\"12.5\" rx=\"10\" ry=\"8.5\" />");
    /// <summary>Lucide <c>touchpad</c>.</summary>
    public static global::Lumeo.IconSource Touchpad => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"16\" x=\"2\" y=\"4\" rx=\"2\" /><path d=\"M2 14h20\" /><path d=\"M12 20v-6\" />");
    /// <summary>Lucide <c>touchpad-off</c>.</summary>
    public static global::Lumeo.IconSource TouchpadOff => global::Lumeo.IconSource.Stroke("<path d=\"M12 20v-6\" /><path d=\"M19.656 14H22\" /><path d=\"M2 14h12\" /><path d=\"m2 2 20 20\" /><path d=\"M20 20H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2\" /><path d=\"M9.656 4H20a2 2 0 0 1 2 2v10.344\" />");
    /// <summary>Lucide <c>towel-rack</c>.</summary>
    public static global::Lumeo.IconSource TowelRack => global::Lumeo.IconSource.Stroke("<path d=\"M22 7h-2\" /><path d=\"M6.5 3h11A2.5 2.5 0 0 1 20 5.5V20a1 1 0 0 1-1 1h-9a1 1 0 0 1-1-1V5.5a1 1 0 0 0-5 0V17a1 1 0 0 0 1 1h4\" /><path d=\"M9 7H2\" />");
    /// <summary>Lucide <c>tower-control</c>.</summary>
    public static global::Lumeo.IconSource TowerControl => global::Lumeo.IconSource.Stroke("<path d=\"M18.2 12.27 20 6H4l1.8 6.27a1 1 0 0 0 .95.73h10.5a1 1 0 0 0 .96-.73Z\" /><path d=\"M8 13v9\" /><path d=\"M16 22v-9\" /><path d=\"m9 6 1 7\" /><path d=\"m15 6-1 7\" /><path d=\"M12 6V2\" /><path d=\"M13 2h-2\" />");
    /// <summary>Lucide <c>toy-brick</c>.</summary>
    public static global::Lumeo.IconSource ToyBrick => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"12\" x=\"3\" y=\"8\" rx=\"1\" /><path d=\"M10 8V5c0-.6-.4-1-1-1H6a1 1 0 0 0-1 1v3\" /><path d=\"M19 8V5c0-.6-.4-1-1-1h-3a1 1 0 0 0-1 1v3\" />");
    /// <summary>Lucide <c>tractor</c>.</summary>
    public static global::Lumeo.IconSource Tractor => global::Lumeo.IconSource.Stroke("<path d=\"m10 11 11 .9a1 1 0 0 1 .8 1.1l-.665 4.158a1 1 0 0 1-.988.842H20\" /><path d=\"M16 18h-5\" /><path d=\"M18 5a1 1 0 0 0-1 1v5.573\" /><path d=\"M3 4h8.129a1 1 0 0 1 .99.863L13 11.246\" /><path d=\"M4 11V4\" /><path d=\"M7 15h.01\" /><path d=\"M8 10.1V4\" /><circle cx=\"18\" cy=\"18\" r=\"2\" /><circle cx=\"7\" cy=\"15\" r=\"5\" />");
    /// <summary>Lucide <c>traffic-cone</c>.</summary>
    public static global::Lumeo.IconSource TrafficCone => global::Lumeo.IconSource.Stroke("<path d=\"M16.05 10.966a5 2.5 0 0 1-8.1 0\" /><path d=\"m16.923 14.049 4.48 2.04a1 1 0 0 1 .001 1.831l-8.574 3.9a2 2 0 0 1-1.66 0l-8.574-3.91a1 1 0 0 1 0-1.83l4.484-2.04\" /><path d=\"M16.949 14.14a5 2.5 0 1 1-9.9 0L10.063 3.5a2 2 0 0 1 3.874 0z\" /><path d=\"M9.194 6.57a5 2.5 0 0 0 5.61 0\" />");
    /// <summary>Lucide <c>train-front</c>.</summary>
    public static global::Lumeo.IconSource TrainFront => global::Lumeo.IconSource.Stroke("<path d=\"M8 3.1V7a4 4 0 0 0 8 0V3.1\" /><path d=\"m9 15-1-1\" /><path d=\"m15 15 1-1\" /><path d=\"M9 19c-2.8 0-5-2.2-5-5v-4a8 8 0 0 1 16 0v4c0 2.8-2.2 5-5 5Z\" /><path d=\"m8 19-2 3\" /><path d=\"m16 19 2 3\" />");
    /// <summary>Lucide <c>train-front-tunnel</c>.</summary>
    public static global::Lumeo.IconSource TrainFrontTunnel => global::Lumeo.IconSource.Stroke("<path d=\"M2 22V12a10 10 0 1 1 20 0v10\" /><path d=\"M15 6.8v1.4a3 2.8 0 1 1-6 0V6.8\" /><path d=\"M10 15h.01\" /><path d=\"M14 15h.01\" /><path d=\"M10 19a4 4 0 0 1-4-4v-3a6 6 0 1 1 12 0v3a4 4 0 0 1-4 4Z\" /><path d=\"m9 19-2 3\" /><path d=\"m15 19 2 3\" />");
    /// <summary>Lucide <c>train-track</c>.</summary>
    public static global::Lumeo.IconSource TrainTrack => global::Lumeo.IconSource.Stroke("<path d=\"M2 17 17 2\" /><path d=\"m2 14 8 8\" /><path d=\"m5 11 8 8\" /><path d=\"m8 8 8 8\" /><path d=\"m11 5 8 8\" /><path d=\"m14 2 8 8\" /><path d=\"M7 22 22 7\" />");
    /// <summary>Lucide <c>tram-front</c>.</summary>
    public static global::Lumeo.IconSource TramFront => global::Lumeo.IconSource.Stroke("<rect width=\"16\" height=\"16\" x=\"4\" y=\"3\" rx=\"2\" /><path d=\"M4 11h16\" /><path d=\"M12 3v8\" /><path d=\"m8 19-2 3\" /><path d=\"m18 22-2-3\" /><path d=\"M8 15h.01\" /><path d=\"M16 15h.01\" />");
    /// <summary>Lucide <c>transgender</c>.</summary>
    public static global::Lumeo.IconSource Transgender => global::Lumeo.IconSource.Stroke("<path d=\"M12 16v6\" /><path d=\"M14 20h-4\" /><path d=\"M18 2h4v4\" /><path d=\"m2 2 7.17 7.17\" /><path d=\"M2 5.355V2h3.357\" /><path d=\"m22 2-7.17 7.17\" /><path d=\"M8 5 5 8\" /><circle cx=\"12\" cy=\"12\" r=\"4\" />");
    /// <summary>Lucide <c>trash</c>.</summary>
    public static global::Lumeo.IconSource Trash => global::Lumeo.IconSource.Stroke("<path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\" /><path d=\"M3 6h18\" /><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\" />");
    /// <summary>Lucide <c>trash-2</c>.</summary>
    public static global::Lumeo.IconSource Trash2 => global::Lumeo.IconSource.Stroke("<path d=\"M10 11v6\" /><path d=\"M14 11v6\" /><path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\" /><path d=\"M3 6h18\" /><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\" />");
    /// <summary>Lucide <c>tree-deciduous</c>.</summary>
    public static global::Lumeo.IconSource TreeDeciduous => global::Lumeo.IconSource.Stroke("<path d=\"M8 19a4 4 0 0 1-2.24-7.32A3.5 3.5 0 0 1 9 6.03V6a3 3 0 1 1 6 0v.04a3.5 3.5 0 0 1 3.24 5.65A4 4 0 0 1 16 19Z\" /><path d=\"M12 19v3\" />");
    /// <summary>Lucide <c>tree-palm</c>.</summary>
    public static global::Lumeo.IconSource TreePalm => global::Lumeo.IconSource.Stroke("<path d=\"M13 8c0-2.76-2.46-5-5.5-5S2 5.24 2 8h2l1-1 1 1h4\" /><path d=\"M13 7.14A5.82 5.82 0 0 1 16.5 6c3.04 0 5.5 2.24 5.5 5h-3l-1-1-1 1h-3\" /><path d=\"M5.89 9.71c-2.15 2.15-2.3 5.47-.35 7.43l4.24-4.25.7-.7.71-.71 2.12-2.12c-1.95-1.96-5.27-1.8-7.42.35\" /><path d=\"M11 15.5c.5 2.5-.17 4.5-1 6.5h4c2-5.5-.5-12-1-14\" />");
    /// <summary>Lucide <c>tree-pine</c>.</summary>
    public static global::Lumeo.IconSource TreePine => global::Lumeo.IconSource.Stroke("<path d=\"m17 14 3 3.3a1 1 0 0 1-.7 1.7H4.7a1 1 0 0 1-.7-1.7L7 14h-.3a1 1 0 0 1-.7-1.7L9 9h-.2A1 1 0 0 1 8 7.3L12 3l4 4.3a1 1 0 0 1-.8 1.7H15l3 3.3a1 1 0 0 1-.7 1.7H17Z\" /><path d=\"M12 22v-3\" />");
    /// <summary>Lucide <c>trees</c>.</summary>
    public static global::Lumeo.IconSource Trees => global::Lumeo.IconSource.Stroke("<path d=\"M10 10v.2A3 3 0 0 1 8.9 16H5a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z\" /><path d=\"M7 16v6\" /><path d=\"M13 19v3\" /><path d=\"M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5\" />");
    /// <summary>Lucide <c>trending-down</c>.</summary>
    public static global::Lumeo.IconSource TrendingDown => global::Lumeo.IconSource.Stroke("<path d=\"M16 17h6v-6\" /><path d=\"m22 17-8.5-8.5-5 5L2 7\" />");
    /// <summary>Lucide <c>trending-up</c>.</summary>
    public static global::Lumeo.IconSource TrendingUp => global::Lumeo.IconSource.Stroke("<path d=\"M16 7h6v6\" /><path d=\"m22 7-8.5 8.5-5-5L2 17\" />");
    /// <summary>Lucide <c>trending-up-down</c>.</summary>
    public static global::Lumeo.IconSource TrendingUpDown => global::Lumeo.IconSource.Stroke("<path d=\"M14.828 14.828 21 21\" /><path d=\"M21 16v5h-5\" /><path d=\"m21 3-9 9-4-4-6 6\" /><path d=\"M21 8V3h-5\" />");
    /// <summary>Lucide <c>triangle</c>.</summary>
    public static global::Lumeo.IconSource Triangle => global::Lumeo.IconSource.Stroke("<path d=\"M13.73 4a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z\" />");
    /// <summary>Lucide <c>triangle-alert</c>.</summary>
    public static global::Lumeo.IconSource TriangleAlert => global::Lumeo.IconSource.Stroke("<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" /><path d=\"M12 9v4\" /><path d=\"M12 17h.01\" />");
    /// <summary>Lucide <c>triangle-dashed</c>.</summary>
    public static global::Lumeo.IconSource TriangleDashed => global::Lumeo.IconSource.Stroke("<path d=\"M10.17 4.193a2 2 0 0 1 3.666.013\" /><path d=\"M14 21h2\" /><path d=\"m15.874 7.743 1 1.732\" /><path d=\"m18.849 12.952 1 1.732\" /><path d=\"M21.824 18.18a2 2 0 0 1-1.835 2.824\" /><path d=\"M4.024 21a2 2 0 0 1-1.839-2.839\" /><path d=\"m5.136 12.952-1 1.732\" /><path d=\"M8 21h2\" /><path d=\"m8.102 7.743-1 1.732\" />");
    /// <summary>Lucide <c>triangle-right</c>.</summary>
    public static global::Lumeo.IconSource TriangleRight => global::Lumeo.IconSource.Stroke("<path d=\"M22 18a2 2 0 0 1-2 2H3c-1.1 0-1.3-.6-.4-1.3L20.4 4.3c.9-.7 1.6-.4 1.6.7Z\" />");
    /// <summary>Lucide <c>trophy</c>.</summary>
    public static global::Lumeo.IconSource Trophy => global::Lumeo.IconSource.Stroke("<path d=\"M10 14.66v1.626a2 2 0 0 1-.976 1.696A5 5 0 0 0 7 21.978\" /><path d=\"M14 14.66v1.626a2 2 0 0 0 .976 1.696A5 5 0 0 1 17 21.978\" /><path d=\"M18 9h1.5a1 1 0 0 0 0-5H18\" /><path d=\"M4 22h16\" /><path d=\"M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z\" /><path d=\"M6 9H4.5a1 1 0 0 1 0-5H6\" />");
    /// <summary>Lucide <c>truck</c>.</summary>
    public static global::Lumeo.IconSource Truck => global::Lumeo.IconSource.Stroke("<path d=\"M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2\" /><path d=\"M15 18H9\" /><path d=\"M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14\" /><circle cx=\"17\" cy=\"18\" r=\"2\" /><circle cx=\"7\" cy=\"18\" r=\"2\" />");
    /// <summary>Lucide <c>truck-electric</c>.</summary>
    public static global::Lumeo.IconSource TruckElectric => global::Lumeo.IconSource.Stroke("<path d=\"M14 19V7a2 2 0 0 0-2-2H9\" /><path d=\"M15 19H9\" /><path d=\"M19 19h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.62L18.3 9.38a1 1 0 0 0-.78-.38H14\" /><path d=\"M2 13v5a1 1 0 0 0 1 1h2\" /><path d=\"M4 3 2.15 5.15a.495.495 0 0 0 .35.86h2.15a.47.47 0 0 1 .35.86L3 9.02\" /><circle cx=\"17\" cy=\"19\" r=\"2\" /><circle cx=\"7\" cy=\"19\" r=\"2\" />");
    /// <summary>Lucide <c>turkish-lira</c>.</summary>
    public static global::Lumeo.IconSource TurkishLira => global::Lumeo.IconSource.Stroke("<path d=\"M15 4 5 9\" /><path d=\"m15 8.5-10 5\" /><path d=\"M18 12a9 9 0 0 1-9 9V3\" />");
    /// <summary>Lucide <c>turntable</c>.</summary>
    public static global::Lumeo.IconSource Turntable => global::Lumeo.IconSource.Stroke("<path d=\"M10 12.01h.01\" /><path d=\"M18 8v4a8 8 0 0 1-1.07 4\" /><circle cx=\"10\" cy=\"12\" r=\"4\" /><rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\" />");
    /// <summary>Lucide <c>turtle</c>.</summary>
    public static global::Lumeo.IconSource Turtle => global::Lumeo.IconSource.Stroke("<path d=\"m12 10 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a8 8 0 1 0-16 0v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3l2-4h4Z\" /><path d=\"M4.82 7.9 8 10\" /><path d=\"M15.18 7.9 12 10\" /><path d=\"M16.93 10H20a2 2 0 0 1 0 4H2\" />");
    /// <summary>Lucide <c>tv</c>.</summary>
    public static global::Lumeo.IconSource Tv => global::Lumeo.IconSource.Stroke("<path d=\"m17 2-5 5-5-5\" /><rect width=\"20\" height=\"15\" x=\"2\" y=\"7\" rx=\"2\" />");
    /// <summary>Lucide <c>tv-minimal</c>.</summary>
    public static global::Lumeo.IconSource TvMinimal => global::Lumeo.IconSource.Stroke("<path d=\"M7 21h10\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" />");
    /// <summary>Lucide <c>tv-minimal-play</c>.</summary>
    public static global::Lumeo.IconSource TvMinimalPlay => global::Lumeo.IconSource.Stroke("<path d=\"M15.033 9.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56V7.648a.645.645 0 0 1 .967-.56z\" /><path d=\"M7 21h10\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" />");
    /// <summary>Lucide <c>type</c>.</summary>
    public static global::Lumeo.IconSource Type => global::Lumeo.IconSource.Stroke("<path d=\"M12 4v16\" /><path d=\"M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2\" /><path d=\"M9 20h6\" />");
    /// <summary>Lucide <c>type-outline</c>.</summary>
    public static global::Lumeo.IconSource TypeOutline => global::Lumeo.IconSource.Stroke("<path d=\"M14 16.5a.5.5 0 0 0 .5.5h.5a2 2 0 0 1 0 4H9a2 2 0 0 1 0-4h.5a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5V8a2 2 0 0 1-4 0V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v3a2 2 0 0 1-4 0v-.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5Z\" />");
    /// <summary>Lucide <c>umbrella</c>.</summary>
    public static global::Lumeo.IconSource Umbrella => global::Lumeo.IconSource.Stroke("<path d=\"M12 13v7a2 2 0 0 0 4 0\" /><path d=\"M12 2v2\" /><path d=\"M20.992 13a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-19.923 0A1 1 0 0 0 3 13z\" />");
    /// <summary>Lucide <c>umbrella-off</c>.</summary>
    public static global::Lumeo.IconSource UmbrellaOff => global::Lumeo.IconSource.Stroke("<path d=\"M12 13v7a2 2 0 0 0 4 0\" /><path d=\"M12 2v2\" /><path d=\"M18.656 13h2.336a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-12.07-7.51\" /><path d=\"m2 2 20 20\" /><path d=\"M5.961 5.957a10.28 10.28 0 0 0-3.922 5.769A1 1 0 0 0 3 13h10\" />");
    /// <summary>Lucide <c>underline</c>.</summary>
    public static global::Lumeo.IconSource Underline => global::Lumeo.IconSource.Stroke("<path d=\"M6 4v6a6 6 0 0 0 12 0V4\" /><line x1=\"4\" x2=\"20\" y1=\"20\" y2=\"20\" />");
    /// <summary>Lucide <c>undo</c>.</summary>
    public static global::Lumeo.IconSource Undo => global::Lumeo.IconSource.Stroke("<path d=\"M3 7v6h6\" /><path d=\"M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13\" />");
    /// <summary>Lucide <c>undo-2</c>.</summary>
    public static global::Lumeo.IconSource Undo2 => global::Lumeo.IconSource.Stroke("<path d=\"M9 14 4 9l5-5\" /><path d=\"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11\" />");
    /// <summary>Lucide <c>undo-dot</c>.</summary>
    public static global::Lumeo.IconSource UndoDot => global::Lumeo.IconSource.Stroke("<path d=\"M21 17a9 9 0 0 0-15-6.7L3 13\" /><path d=\"M3 7v6h6\" /><circle cx=\"12\" cy=\"17\" r=\"1\" />");
    /// <summary>Lucide <c>unfold-horizontal</c>.</summary>
    public static global::Lumeo.IconSource UnfoldHorizontal => global::Lumeo.IconSource.Stroke("<path d=\"M16 12h6\" /><path d=\"M8 12H2\" /><path d=\"M12 2v2\" /><path d=\"M12 8v2\" /><path d=\"M12 14v2\" /><path d=\"M12 20v2\" /><path d=\"m19 15 3-3-3-3\" /><path d=\"m5 9-3 3 3 3\" />");
    /// <summary>Lucide <c>unfold-vertical</c>.</summary>
    public static global::Lumeo.IconSource UnfoldVertical => global::Lumeo.IconSource.Stroke("<path d=\"M12 22v-6\" /><path d=\"M12 8V2\" /><path d=\"M4 12H2\" /><path d=\"M10 12H8\" /><path d=\"M16 12h-2\" /><path d=\"M22 12h-2\" /><path d=\"m15 19-3 3-3-3\" /><path d=\"m15 5-3-3-3 3\" />");
    /// <summary>Lucide <c>ungroup</c>.</summary>
    public static global::Lumeo.IconSource Ungroup => global::Lumeo.IconSource.Stroke("<rect x=\"11\" y=\"14\" width=\"10\" height=\"7\" rx=\"2\" /><rect x=\"3\" y=\"3\" width=\"10\" height=\"7\" rx=\"2\" />");
    /// <summary>Lucide <c>university</c>.</summary>
    public static global::Lumeo.IconSource University => global::Lumeo.IconSource.Stroke("<path d=\"M14 21v-3a2 2 0 0 0-4 0v3\" /><path d=\"M18 12h.01\" /><path d=\"M18 16h.01\" /><path d=\"M22 7a1 1 0 0 0-1-1h-2a2 2 0 0 1-1.143-.359L13.143 2.36a2 2 0 0 0-2.286-.001L6.143 5.64A2 2 0 0 1 5 6H3a1 1 0 0 0-1 1v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2z\" /><path d=\"M6 12h.01\" /><path d=\"M6 16h.01\" /><circle cx=\"12\" cy=\"10\" r=\"2\" />");
    /// <summary>Lucide <c>unlink</c>.</summary>
    public static global::Lumeo.IconSource Unlink => global::Lumeo.IconSource.Stroke("<path d=\"m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71\" /><path d=\"m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71\" /><line x1=\"8\" x2=\"8\" y1=\"2\" y2=\"5\" /><line x1=\"2\" x2=\"5\" y1=\"8\" y2=\"8\" /><line x1=\"16\" x2=\"16\" y1=\"19\" y2=\"22\" /><line x1=\"19\" x2=\"22\" y1=\"16\" y2=\"16\" />");
    /// <summary>Lucide <c>unlink-2</c>.</summary>
    public static global::Lumeo.IconSource Unlink2 => global::Lumeo.IconSource.Stroke("<path d=\"M15 7h2a5 5 0 0 1 0 10h-2m-6 0H7A5 5 0 0 1 7 7h2\" />");
    /// <summary>Lucide <c>unplug</c>.</summary>
    public static global::Lumeo.IconSource Unplug => global::Lumeo.IconSource.Stroke("<path d=\"m19 5 3-3\" /><path d=\"m2 22 3-3\" /><path d=\"M6.3 20.3a2.4 2.4 0 0 0 3.4 0L12 18l-6-6-2.3 2.3a2.4 2.4 0 0 0 0 3.4Z\" /><path d=\"M7.5 13.5 10 11\" /><path d=\"M10.5 16.5 13 14\" /><path d=\"m12 6 6 6 2.3-2.3a2.4 2.4 0 0 0 0-3.4l-2.6-2.6a2.4 2.4 0 0 0-3.4 0Z\" />");
    /// <summary>Lucide <c>upload</c>.</summary>
    public static global::Lumeo.IconSource Upload => global::Lumeo.IconSource.Stroke("<path d=\"M12 3v12\" /><path d=\"m17 8-5-5-5 5\" /><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\" />");
    /// <summary>Lucide <c>usb</c>.</summary>
    public static global::Lumeo.IconSource Usb => global::Lumeo.IconSource.Stroke("<circle cx=\"10\" cy=\"7\" r=\"1\" /><circle cx=\"4\" cy=\"20\" r=\"1\" /><path d=\"M4.7 19.3 19 5\" /><path d=\"m21 3-3 1 2 2Z\" /><path d=\"M9.26 7.68 5 12l2 5\" /><path d=\"m10 14 5 2 3.5-3.5\" /><path d=\"m18 12 1-1 1 1-1 1Z\" />");
    /// <summary>Lucide <c>user</c>.</summary>
    public static global::Lumeo.IconSource User => global::Lumeo.IconSource.Stroke("<path d=\"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2\" /><circle cx=\"12\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-check</c>.</summary>
    public static global::Lumeo.IconSource UserCheck => global::Lumeo.IconSource.Stroke("<path d=\"m16 11 2 2 4-4\" /><path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-cog</c>.</summary>
    public static global::Lumeo.IconSource UserCog => global::Lumeo.IconSource.Stroke("<path d=\"M10 15H6a4 4 0 0 0-4 4v2\" /><path d=\"m14.305 16.53.923-.382\" /><path d=\"m15.228 13.852-.923-.383\" /><path d=\"m16.852 12.228-.383-.923\" /><path d=\"m16.852 17.772-.383.924\" /><path d=\"m19.148 12.228.383-.923\" /><path d=\"m19.53 18.696-.382-.924\" /><path d=\"m20.772 13.852.924-.383\" /><path d=\"m20.772 16.148.924.383\" /><circle cx=\"18\" cy=\"15\" r=\"3\" /><circle cx=\"9\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-key</c>.</summary>
    public static global::Lumeo.IconSource UserKey => global::Lumeo.IconSource.Stroke("<path d=\"M20 11v6\" /><path d=\"M20 13h2\" /><path d=\"M3 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 2.072.578\" /><circle cx=\"10\" cy=\"7\" r=\"4\" /><circle cx=\"20\" cy=\"19\" r=\"2\" />");
    /// <summary>Lucide <c>user-lock</c>.</summary>
    public static global::Lumeo.IconSource UserLock => global::Lumeo.IconSource.Stroke("<path d=\"M19 16v-2a2 2 0 0 0-4 0v2\" /><path d=\"M9.5 15H7a4 4 0 0 0-4 4v2\" /><circle cx=\"10\" cy=\"7\" r=\"4\" /><rect x=\"13\" y=\"16\" width=\"8\" height=\"5\" rx=\".899\" />");
    /// <summary>Lucide <c>user-minus</c>.</summary>
    public static global::Lumeo.IconSource UserMinus => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" /><line x1=\"22\" x2=\"16\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>user-pen</c>.</summary>
    public static global::Lumeo.IconSource UserPen => global::Lumeo.IconSource.Stroke("<path d=\"M11.5 15H7a4 4 0 0 0-4 4v2\" /><path d=\"M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" /><circle cx=\"10\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-plus</c>.</summary>
    public static global::Lumeo.IconSource UserPlus => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" /><line x1=\"19\" x2=\"19\" y1=\"8\" y2=\"14\" /><line x1=\"22\" x2=\"16\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>user-round</c>.</summary>
    public static global::Lumeo.IconSource UserRound => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"8\" r=\"5\" /><path d=\"M20 21a8 8 0 0 0-16 0\" />");
    /// <summary>Lucide <c>user-round-arrow-left</c>.</summary>
    public static global::Lumeo.IconSource UserRoundArrowLeft => global::Lumeo.IconSource.Stroke("<path d=\"m19 16-3 3\" /><path d=\"M2 21a8 8 0 0 1 12.664-6.5\" /><path d=\"M22 19h-6l3 3\" /><circle cx=\"10\" cy=\"8\" r=\"5\" />");
    /// <summary>Lucide <c>user-round-check</c>.</summary>
    public static global::Lumeo.IconSource UserRoundCheck => global::Lumeo.IconSource.Stroke("<path d=\"M2 21a8 8 0 0 1 13.292-6\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"m16 19 2 2 4-4\" />");
    /// <summary>Lucide <c>user-round-cog</c>.</summary>
    public static global::Lumeo.IconSource UserRoundCog => global::Lumeo.IconSource.Stroke("<path d=\"m14.305 19.53.923-.382\" /><path d=\"m15.228 16.852-.923-.383\" /><path d=\"m16.852 15.228-.383-.923\" /><path d=\"m16.852 20.772-.383.924\" /><path d=\"m19.148 15.228.383-.923\" /><path d=\"m19.53 21.696-.382-.924\" /><path d=\"M2 21a8 8 0 0 1 10.434-7.62\" /><path d=\"m20.772 16.852.924-.383\" /><path d=\"m20.772 19.148.924.383\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><circle cx=\"18\" cy=\"18\" r=\"3\" />");
    /// <summary>Lucide <c>user-round-key</c>.</summary>
    public static global::Lumeo.IconSource UserRoundKey => global::Lumeo.IconSource.Stroke("<path d=\"M19 11v6\" /><path d=\"M19 13h2\" /><path d=\"M2 21a8 8 0 0 1 12.868-6.349\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><circle cx=\"19\" cy=\"19\" r=\"2\" />");
    /// <summary>Lucide <c>user-round-minus</c>.</summary>
    public static global::Lumeo.IconSource UserRoundMinus => global::Lumeo.IconSource.Stroke("<path d=\"M2 21a8 8 0 0 1 13.292-6\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"M22 19h-6\" />");
    /// <summary>Lucide <c>user-round-pen</c>.</summary>
    public static global::Lumeo.IconSource UserRoundPen => global::Lumeo.IconSource.Stroke("<path d=\"M2 21a8 8 0 0 1 10.821-7.487\" /><path d=\"M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" /><circle cx=\"10\" cy=\"8\" r=\"5\" />");
    /// <summary>Lucide <c>user-round-plus</c>.</summary>
    public static global::Lumeo.IconSource UserRoundPlus => global::Lumeo.IconSource.Stroke("<path d=\"M2 21a8 8 0 0 1 13.292-6\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"M19 16v6\" /><path d=\"M22 19h-6\" />");
    /// <summary>Lucide <c>user-round-search</c>.</summary>
    public static global::Lumeo.IconSource UserRoundSearch => global::Lumeo.IconSource.Stroke("<circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"M2 21a8 8 0 0 1 10.434-7.62\" /><circle cx=\"18\" cy=\"18\" r=\"3\" /><path d=\"m22 22-1.9-1.9\" />");
    /// <summary>Lucide <c>user-round-x</c>.</summary>
    public static global::Lumeo.IconSource UserRoundX => global::Lumeo.IconSource.Stroke("<path d=\"M2 21a8 8 0 0 1 11.873-7\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"m17 17 5 5\" /><path d=\"m22 17-5 5\" />");
    /// <summary>Lucide <c>user-search</c>.</summary>
    public static global::Lumeo.IconSource UserSearch => global::Lumeo.IconSource.Stroke("<circle cx=\"10\" cy=\"7\" r=\"4\" /><path d=\"M10.3 15H7a4 4 0 0 0-4 4v2\" /><circle cx=\"17\" cy=\"17\" r=\"3\" /><path d=\"m21 21-1.9-1.9\" />");
    /// <summary>Lucide <c>user-star</c>.</summary>
    public static global::Lumeo.IconSource UserStar => global::Lumeo.IconSource.Stroke("<path d=\"M16.051 12.616a1 1 0 0 1 1.909.024l.737 1.452a1 1 0 0 0 .737.535l1.634.256a1 1 0 0 1 .588 1.806l-1.172 1.168a1 1 0 0 0-.282.866l.259 1.613a1 1 0 0 1-1.541 1.134l-1.465-.75a1 1 0 0 0-.912 0l-1.465.75a1 1 0 0 1-1.539-1.133l.258-1.613a1 1 0 0 0-.282-.866l-1.156-1.153a1 1 0 0 1 .572-1.822l1.633-.256a1 1 0 0 0 .737-.535z\" /><path d=\"M8 15H7a4 4 0 0 0-4 4v2\" /><circle cx=\"10\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-x</c>.</summary>
    public static global::Lumeo.IconSource UserX => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" /><line x1=\"17\" x2=\"22\" y1=\"8\" y2=\"13\" /><line x1=\"22\" x2=\"17\" y1=\"8\" y2=\"13\" />");
    /// <summary>Lucide <c>users</c>.</summary>
    public static global::Lumeo.IconSource Users => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><path d=\"M16 3.128a4 4 0 0 1 0 7.744\" /><path d=\"M22 21v-2a4 4 0 0 0-3-3.87\" /><circle cx=\"9\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>users-round</c>.</summary>
    public static global::Lumeo.IconSource UsersRound => global::Lumeo.IconSource.Stroke("<path d=\"M18 21a8 8 0 0 0-16 0\" /><circle cx=\"10\" cy=\"8\" r=\"5\" /><path d=\"M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3\" />");
    /// <summary>Lucide <c>utensils</c>.</summary>
    public static global::Lumeo.IconSource Utensils => global::Lumeo.IconSource.Stroke("<path d=\"M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2\" /><path d=\"M7 2v20\" /><path d=\"M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7\" />");
    /// <summary>Lucide <c>utensils-crossed</c>.</summary>
    public static global::Lumeo.IconSource UtensilsCrossed => global::Lumeo.IconSource.Stroke("<path d=\"m16 2-2.3 2.3a3 3 0 0 0 0 4.2l1.8 1.8a3 3 0 0 0 4.2 0L22 8\" /><path d=\"M15 15 3.3 3.3a4.2 4.2 0 0 0 0 6l7.3 7.3c.7.7 2 .7 2.8 0L15 15Zm0 0 7 7\" /><path d=\"m2.1 21.8 6.4-6.3\" /><path d=\"m19 5-7 7\" />");
    /// <summary>Lucide <c>utility-pole</c>.</summary>
    public static global::Lumeo.IconSource UtilityPole => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v20\" /><path d=\"M2 5h20\" /><path d=\"M3 3v2\" /><path d=\"M7 3v2\" /><path d=\"M17 3v2\" /><path d=\"M21 3v2\" /><path d=\"m19 5-7 7-7-7\" />");
    /// <summary>Lucide <c>van</c>.</summary>
    public static global::Lumeo.IconSource Van => global::Lumeo.IconSource.Stroke("<path d=\"M13 6v5a1 1 0 0 0 1 1h6.102a1 1 0 0 1 .712.298l.898.91a1 1 0 0 1 .288.702V17a1 1 0 0 1-1 1h-3\" /><path d=\"M5 18H3a1 1 0 0 1-1-1V8a2 2 0 0 1 2-2h12c1.1 0 2.1.8 2.4 1.8l1.176 4.2\" /><path d=\"M9 18h5\" /><circle cx=\"16\" cy=\"18\" r=\"2\" /><circle cx=\"7\" cy=\"18\" r=\"2\" />");
    /// <summary>Lucide <c>variable</c>.</summary>
    public static global::Lumeo.IconSource Variable => global::Lumeo.IconSource.Stroke("<path d=\"M8 21s-4-3-4-9 4-9 4-9\" /><path d=\"M16 3s4 3 4 9-4 9-4 9\" /><line x1=\"15\" x2=\"9\" y1=\"9\" y2=\"15\" /><line x1=\"9\" x2=\"15\" y1=\"9\" y2=\"15\" />");
    /// <summary>Lucide <c>vault</c>.</summary>
    public static global::Lumeo.IconSource Vault => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" /><path d=\"m7.9 7.9 2.7 2.7\" /><circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" /><path d=\"m13.4 10.6 2.7-2.7\" /><circle cx=\"7.5\" cy=\"16.5\" r=\".5\" fill=\"currentColor\" /><path d=\"m7.9 16.1 2.7-2.7\" /><circle cx=\"16.5\" cy=\"16.5\" r=\".5\" fill=\"currentColor\" /><path d=\"m13.4 13.4 2.7 2.7\" /><circle cx=\"12\" cy=\"12\" r=\"2\" />");
    /// <summary>Lucide <c>vector-square</c>.</summary>
    public static global::Lumeo.IconSource VectorSquare => global::Lumeo.IconSource.Stroke("<path d=\"M19.5 7a24 24 0 0 1 0 10\" /><path d=\"M4.5 7a24 24 0 0 0 0 10\" /><path d=\"M7 19.5a24 24 0 0 0 10 0\" /><path d=\"M7 4.5a24 24 0 0 1 10 0\" /><rect x=\"17\" y=\"17\" width=\"5\" height=\"5\" rx=\"1\" /><rect x=\"17\" y=\"2\" width=\"5\" height=\"5\" rx=\"1\" /><rect x=\"2\" y=\"17\" width=\"5\" height=\"5\" rx=\"1\" /><rect x=\"2\" y=\"2\" width=\"5\" height=\"5\" rx=\"1\" />");
    /// <summary>Lucide <c>vegan</c>.</summary>
    public static global::Lumeo.IconSource Vegan => global::Lumeo.IconSource.Stroke("<path d=\"M16 8q6 0 6-6-6 0-6 6\" /><path d=\"M17.41 3.59a10 10 0 1 0 3 3\" /><path d=\"M2 2a26.6 26.6 0 0 1 10 20c.9-6.82 1.5-9.5 4-14\" />");
    /// <summary>Lucide <c>venetian-mask</c>.</summary>
    public static global::Lumeo.IconSource VenetianMask => global::Lumeo.IconSource.Stroke("<path d=\"M18 11c-1.5 0-2.5.5-3 2\" /><path d=\"M4 6a2 2 0 0 0-2 2v4a5 5 0 0 0 5 5 8 8 0 0 1 5 2 8 8 0 0 1 5-2 5 5 0 0 0 5-5V8a2 2 0 0 0-2-2h-3a8 8 0 0 0-5 2 8 8 0 0 0-5-2z\" /><path d=\"M6 11c1.5 0 2.5.5 3 2\" />");
    /// <summary>Lucide <c>venus</c>.</summary>
    public static global::Lumeo.IconSource Venus => global::Lumeo.IconSource.Stroke("<path d=\"M12 15v7\" /><path d=\"M9 19h6\" /><circle cx=\"12\" cy=\"9\" r=\"6\" />");
    /// <summary>Lucide <c>venus-and-mars</c>.</summary>
    public static global::Lumeo.IconSource VenusAndMars => global::Lumeo.IconSource.Stroke("<path d=\"M10 20h4\" /><path d=\"M12 16v6\" /><path d=\"M17 2h4v4\" /><path d=\"m21 2-5.46 5.46\" /><circle cx=\"12\" cy=\"11\" r=\"5\" />");
    /// <summary>Lucide <c>vibrate</c>.</summary>
    public static global::Lumeo.IconSource Vibrate => global::Lumeo.IconSource.Stroke("<path d=\"m2 8 2 2-2 2 2 2-2 2\" /><path d=\"m22 8-2 2 2 2-2 2 2 2\" /><rect width=\"8\" height=\"14\" x=\"8\" y=\"5\" rx=\"1\" />");
    /// <summary>Lucide <c>vibrate-off</c>.</summary>
    public static global::Lumeo.IconSource VibrateOff => global::Lumeo.IconSource.Stroke("<path d=\"m2 8 2 2-2 2 2 2-2 2\" /><path d=\"m22 8-2 2 2 2-2 2 2 2\" /><path d=\"M8 8v10c0 .55.45 1 1 1h6c.55 0 1-.45 1-1v-2\" /><path d=\"M16 10.34V6c0-.55-.45-1-1-1h-4.34\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" />");
    /// <summary>Lucide <c>video</c>.</summary>
    public static global::Lumeo.IconSource Video => global::Lumeo.IconSource.Stroke("<path d=\"m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5\" /><rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\" />");
    /// <summary>Lucide <c>video-off</c>.</summary>
    public static global::Lumeo.IconSource VideoOff => global::Lumeo.IconSource.Stroke("<path d=\"M10.66 6H14a2 2 0 0 1 2 2v2.5l5.248-3.062A.5.5 0 0 1 22 7.87v8.196\" /><path d=\"M16 16a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>videotape</c>.</summary>
    public static global::Lumeo.IconSource Videotape => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"16\" x=\"2\" y=\"4\" rx=\"2\" /><path d=\"M2 8h20\" /><circle cx=\"8\" cy=\"14\" r=\"2\" /><path d=\"M8 12h8\" /><circle cx=\"16\" cy=\"14\" r=\"2\" />");
    /// <summary>Lucide <c>view</c>.</summary>
    public static global::Lumeo.IconSource View => global::Lumeo.IconSource.Stroke("<path d=\"M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2\" /><path d=\"M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2\" /><circle cx=\"12\" cy=\"12\" r=\"1\" /><path d=\"M18.944 12.33a1 1 0 0 0 0-.66 7.5 7.5 0 0 0-13.888 0 1 1 0 0 0 0 .66 7.5 7.5 0 0 0 13.888 0\" />");
    /// <summary>Lucide <c>voicemail</c>.</summary>
    public static global::Lumeo.IconSource Voicemail => global::Lumeo.IconSource.Stroke("<circle cx=\"6\" cy=\"12\" r=\"4\" /><circle cx=\"18\" cy=\"12\" r=\"4\" /><line x1=\"6\" x2=\"18\" y1=\"16\" y2=\"16\" />");
    /// <summary>Lucide <c>volleyball</c>.</summary>
    public static global::Lumeo.IconSource Volleyball => global::Lumeo.IconSource.Stroke("<path d=\"M11 7a16 16 20 0 1 10.98 4.362\" /><path d=\"M12 12a13 13 0 0 1-8.66 5\" /><path d=\"M16.83 13.634a16 16 0 0 1-9.267 7.328\" /><path d=\"M20.66 17A13 13 0 0 0 12 12a13 13 0 0 1 0-10\" /><path d=\"M8.17 15.366a16 16 0 0 1-1.713-11.69\" /><circle cx=\"12\" cy=\"12\" r=\"10\" />");
    /// <summary>Lucide <c>volume</c>.</summary>
    public static global::Lumeo.IconSource Volume => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" />");
    /// <summary>Lucide <c>volume-1</c>.</summary>
    public static global::Lumeo.IconSource Volume1 => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><path d=\"M16 9a5 5 0 0 1 0 6\" />");
    /// <summary>Lucide <c>volume-2</c>.</summary>
    public static global::Lumeo.IconSource Volume2 => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><path d=\"M16 9a5 5 0 0 1 0 6\" /><path d=\"M19.364 18.364a9 9 0 0 0 0-12.728\" />");
    /// <summary>Lucide <c>volume-off</c>.</summary>
    public static global::Lumeo.IconSource VolumeOff => global::Lumeo.IconSource.Stroke("<path d=\"M16 9a5 5 0 0 1 .95 2.293\" /><path d=\"M19.364 5.636a9 9 0 0 1 1.889 9.96\" /><path d=\"m2 2 20 20\" /><path d=\"m7 7-.587.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298V11\" /><path d=\"M9.828 4.172A.686.686 0 0 1 11 4.657v.686\" />");
    /// <summary>Lucide <c>volume-x</c>.</summary>
    public static global::Lumeo.IconSource VolumeX => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><line x1=\"22\" x2=\"16\" y1=\"9\" y2=\"15\" /><line x1=\"16\" x2=\"22\" y1=\"9\" y2=\"15\" />");
    /// <summary>Lucide <c>vote</c>.</summary>
    public static global::Lumeo.IconSource Vote => global::Lumeo.IconSource.Stroke("<path d=\"m9 12 2 2 4-4\" /><path d=\"M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z\" /><path d=\"M22 19H2\" />");
    /// <summary>Lucide <c>wallet</c>.</summary>
    public static global::Lumeo.IconSource Wallet => global::Lumeo.IconSource.Stroke("<path d=\"M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1\" /><path d=\"M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4\" />");
    /// <summary>Lucide <c>wallet-cards</c>.</summary>
    public static global::Lumeo.IconSource WalletCards => global::Lumeo.IconSource.Stroke("<path d=\"M3 11h3.75a2 2 0 0 1 1.6.8l.45.6a4 4 0 0 0 6.4 0l.45-.6a2 2 0 0 1 1.6-.8H21\" /><path d=\"M3 7h18\" /><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" />");
    /// <summary>Lucide <c>wallet-minimal</c>.</summary>
    public static global::Lumeo.IconSource WalletMinimal => global::Lumeo.IconSource.Stroke("<path d=\"M17 14h.01\" /><path d=\"M7 7h12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14\" />");
    /// <summary>Lucide <c>wallpaper</c>.</summary>
    public static global::Lumeo.IconSource Wallpaper => global::Lumeo.IconSource.Stroke("<path d=\"M12 17v4\" /><path d=\"M8 21h8\" /><path d=\"m9 17 6.1-6.1a2 2 0 0 1 2.81.01L22 15\" /><circle cx=\"8\" cy=\"9\" r=\"2\" /><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" />");
    /// <summary>Lucide <c>wand</c>.</summary>
    public static global::Lumeo.IconSource Wand => global::Lumeo.IconSource.Stroke("<path d=\"M15 4V2\" /><path d=\"M15 16v-2\" /><path d=\"M8 9h2\" /><path d=\"M20 9h2\" /><path d=\"M17.8 11.8 19 13\" /><path d=\"M15 9h.01\" /><path d=\"M17.8 6.2 19 5\" /><path d=\"m3 21 9-9\" /><path d=\"M12.2 6.2 11 5\" />");
    /// <summary>Lucide <c>wand-sparkles</c>.</summary>
    public static global::Lumeo.IconSource WandSparkles => global::Lumeo.IconSource.Stroke("<path d=\"m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72\" /><path d=\"m14 7 3 3\" /><path d=\"M5 6v4\" /><path d=\"M19 14v4\" /><path d=\"M10 2v2\" /><path d=\"M7 8H3\" /><path d=\"M21 16h-4\" /><path d=\"M11 3H9\" />");
    /// <summary>Lucide <c>warehouse</c>.</summary>
    public static global::Lumeo.IconSource Warehouse => global::Lumeo.IconSource.Stroke("<path d=\"M18 21V10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v11\" /><path d=\"M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 1.132-1.803l7.95-3.974a2 2 0 0 1 1.837 0l7.948 3.974A2 2 0 0 1 22 8z\" /><path d=\"M6 13h12\" /><path d=\"M6 17h12\" />");
    /// <summary>Lucide <c>washing-machine</c>.</summary>
    public static global::Lumeo.IconSource WashingMachine => global::Lumeo.IconSource.Stroke("<path d=\"M3 6h3\" /><path d=\"M17 6h.01\" /><rect width=\"18\" height=\"20\" x=\"3\" y=\"2\" rx=\"2\" /><circle cx=\"12\" cy=\"13\" r=\"5\" /><path d=\"M12 18a2.5 2.5 0 0 0 0-5 2.5 2.5 0 0 1 0-5\" />");
    /// <summary>Lucide <c>watch</c>.</summary>
    public static global::Lumeo.IconSource Watch => global::Lumeo.IconSource.Stroke("<path d=\"M12 10v2.2l1.6 1\" /><path d=\"m16.13 7.66-.81-4.05a2 2 0 0 0-2-1.61h-2.68a2 2 0 0 0-2 1.61l-.78 4.05\" /><path d=\"m7.88 16.36.8 4a2 2 0 0 0 2 1.61h2.72a2 2 0 0 0 2-1.61l.81-4.05\" /><circle cx=\"12\" cy=\"12\" r=\"6\" />");
    /// <summary>Lucide <c>waves-arrow-down</c>.</summary>
    public static global::Lumeo.IconSource WavesArrowDown => global::Lumeo.IconSource.Stroke("<path d=\"M12 10L12 2\" /><path d=\"M16 6L12 10L8 6\" /><path d=\"M2 15C2.6 15.5 3.2 16 4.5 16C7 16 7 14 9.5 14C12.1 14 11.9 16 14.5 16C17 16 17 14 19.5 14C20.8 14 21.4 14.5 22 15\" /><path d=\"M2 21C2.6 21.5 3.2 22 4.5 22C7 22 7 20 9.5 20C12.1 20 11.9 22 14.5 22C17 22 17 20 19.5 20C20.8 20 21.4 20.5 22 21\" />");
    /// <summary>Lucide <c>waves-arrow-up</c>.</summary>
    public static global::Lumeo.IconSource WavesArrowUp => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v8\" /><path d=\"M2 15c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1\" /><path d=\"M2 21c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1\" /><path d=\"m8 6 4-4 4 4\" />");
    /// <summary>Lucide <c>waves-horizontal</c>.</summary>
    public static global::Lumeo.IconSource WavesHorizontal => global::Lumeo.IconSource.Stroke("<path d=\"M2 12q2.5 2 5 0t5 0 5 0 5 0\" /><path d=\"M2 19q2.5 2 5 0t5 0 5 0 5 0\" /><path d=\"M2 5q2.5 2 5 0t5 0 5 0 5 0\" />");
    /// <summary>Lucide <c>waves-ladder</c>.</summary>
    public static global::Lumeo.IconSource WavesLadder => global::Lumeo.IconSource.Stroke("<path d=\"M19 5a2 2 0 0 0-2 2v11\" /><path d=\"M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1\" /><path d=\"M7 13h10\" /><path d=\"M7 9h10\" /><path d=\"M9 5a2 2 0 0 0-2 2v11\" />");
    /// <summary>Lucide <c>waves-vertical</c>.</summary>
    public static global::Lumeo.IconSource WavesVertical => global::Lumeo.IconSource.Stroke("<path d=\"M12 2q2 2.5 0 5t0 5 0 5 0 5\" /><path d=\"M19 2q2 2.5 0 5t0 5 0 5 0 5\" /><path d=\"M5 2q2 2.5 0 5t0 5 0 5 0 5\" />");
    /// <summary>Lucide <c>waypoints</c>.</summary>
    public static global::Lumeo.IconSource Waypoints => global::Lumeo.IconSource.Stroke("<path d=\"m10.586 5.414-5.172 5.172\" /><path d=\"m18.586 13.414-5.172 5.172\" /><path d=\"M6 12h12\" /><circle cx=\"12\" cy=\"20\" r=\"2\" /><circle cx=\"12\" cy=\"4\" r=\"2\" /><circle cx=\"20\" cy=\"12\" r=\"2\" /><circle cx=\"4\" cy=\"12\" r=\"2\" />");
    /// <summary>Lucide <c>webcam</c>.</summary>
    public static global::Lumeo.IconSource Webcam => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"10\" r=\"8\" /><circle cx=\"12\" cy=\"10\" r=\"3\" /><path d=\"M7 22h10\" /><path d=\"M12 22v-4\" />");
    /// <summary>Lucide <c>webcam-off</c>.</summary>
    public static global::Lumeo.IconSource WebcamOff => global::Lumeo.IconSource.Stroke("<path d=\"M12 22v-4\" /><path d=\"M12.754 7.096a3 3 0 0 1 2.15 2.15\" /><path d=\"M12.863 12.873a3 3 0 0 1-3.736-3.735\" /><path d=\"M16.566 16.57A8 8 0 0 1 5.43 5.433\" /><path d=\"m2 2 20 20\" /><path d=\"M7 22h10\" /><path d=\"M8.478 2.817a8 8 0 0 1 10.705 10.705\" />");
    /// <summary>Lucide <c>webhook</c>.</summary>
    public static global::Lumeo.IconSource Webhook => global::Lumeo.IconSource.Stroke("<path d=\"M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2\" /><path d=\"m6 17 3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06\" /><path d=\"m12 6 3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8\" />");
    /// <summary>Lucide <c>webhook-off</c>.</summary>
    public static global::Lumeo.IconSource WebhookOff => global::Lumeo.IconSource.Stroke("<path d=\"M17 17h-5c-1.09-.02-1.94.92-2.5 1.9A3 3 0 1 1 2.57 15\" /><path d=\"M9 3.4a4 4 0 0 1 6.52.66\" /><path d=\"m6 17 3.1-5.8a2.5 2.5 0 0 0 .057-2.05\" /><path d=\"M20.3 20.3a4 4 0 0 1-2.3.7\" /><path d=\"M18.6 13a4 4 0 0 1 3.357 3.414\" /><path d=\"m12 6 .6 1\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>weight</c>.</summary>
    public static global::Lumeo.IconSource Weight => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"5\" r=\"3\" /><path d=\"M6.5 8a2 2 0 0 0-1.905 1.46L2.1 18.5A2 2 0 0 0 4 21h16a2 2 0 0 0 1.925-2.54L19.4 9.5A2 2 0 0 0 17.48 8Z\" />");
    /// <summary>Lucide <c>weight-tilde</c>.</summary>
    public static global::Lumeo.IconSource WeightTilde => global::Lumeo.IconSource.Stroke("<path d=\"M6.5 8a2 2 0 0 0-1.906 1.46L2.1 18.5A2 2 0 0 0 4 21h16a2 2 0 0 0 1.925-2.54L19.4 9.5A2 2 0 0 0 17.48 8z\" /><path d=\"M7.999 15a2.5 2.5 0 0 1 4 0 2.5 2.5 0 0 0 4 0\" /><circle cx=\"12\" cy=\"5\" r=\"3\" />");
    /// <summary>Lucide <c>wheat</c>.</summary>
    public static global::Lumeo.IconSource Wheat => global::Lumeo.IconSource.Stroke("<path d=\"M2 22 16 8\" /><path d=\"M3.47 12.53 5 11l1.53 1.53a3.5 3.5 0 0 1 0 4.94L5 19l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z\" /><path d=\"M7.47 8.53 9 7l1.53 1.53a3.5 3.5 0 0 1 0 4.94L9 15l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z\" /><path d=\"M11.47 4.53 13 3l1.53 1.53a3.5 3.5 0 0 1 0 4.94L13 11l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z\" /><path d=\"M20 2h2v2a4 4 0 0 1-4 4h-2V6a4 4 0 0 1 4-4Z\" /><path d=\"M11.47 17.47 13 19l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L5 19l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z\" /><path d=\"M15.47 13.47 17 15l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L9 15l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z\" /><path d=\"M19.47 9.47 21 11l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L13 11l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z\" />");
    /// <summary>Lucide <c>wheat-off</c>.</summary>
    public static global::Lumeo.IconSource WheatOff => global::Lumeo.IconSource.Stroke("<path d=\"m2 22 10-10\" /><path d=\"m16 8-1.17 1.17\" /><path d=\"M3.47 12.53 5 11l1.53 1.53a3.5 3.5 0 0 1 0 4.94L5 19l-1.53-1.53a3.5 3.5 0 0 1 0-4.94Z\" /><path d=\"m8 8-.53.53a3.5 3.5 0 0 0 0 4.94L9 15l1.53-1.53c.55-.55.88-1.25.98-1.97\" /><path d=\"M10.91 5.26c.15-.26.34-.51.56-.73L13 3l1.53 1.53a3.5 3.5 0 0 1 .28 4.62\" /><path d=\"M20 2h2v2a4 4 0 0 1-4 4h-2V6a4 4 0 0 1 4-4Z\" /><path d=\"M11.47 17.47 13 19l-1.53 1.53a3.5 3.5 0 0 1-4.94 0L5 19l1.53-1.53a3.5 3.5 0 0 1 4.94 0Z\" /><path d=\"m16 16-.53.53a3.5 3.5 0 0 1-4.94 0L9 15l1.53-1.53a3.49 3.49 0 0 1 1.97-.98\" /><path d=\"M18.74 13.09c.26-.15.51-.34.73-.56L21 11l-1.53-1.53a3.5 3.5 0 0 0-4.62-.28\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" />");
    /// <summary>Lucide <c>whole-word</c>.</summary>
    public static global::Lumeo.IconSource WholeWord => global::Lumeo.IconSource.Stroke("<circle cx=\"7\" cy=\"12\" r=\"3\" /><path d=\"M10 9v6\" /><circle cx=\"17\" cy=\"12\" r=\"3\" /><path d=\"M14 7v8\" /><path d=\"M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1\" />");
    /// <summary>Lucide <c>wifi</c>.</summary>
    public static global::Lumeo.IconSource Wifi => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h.01\" /><path d=\"M2 8.82a15 15 0 0 1 20 0\" /><path d=\"M5 12.859a10 10 0 0 1 14 0\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" />");
    /// <summary>Lucide <c>wifi-cog</c>.</summary>
    public static global::Lumeo.IconSource WifiCog => global::Lumeo.IconSource.Stroke("<path d=\"m14.305 19.53.923-.382\" /><path d=\"m15.228 16.852-.923-.383\" /><path d=\"m16.852 15.228-.383-.923\" /><path d=\"m16.852 20.772-.383.924\" /><path d=\"m19.148 15.228.383-.923\" /><path d=\"m19.53 21.696-.382-.924\" /><path d=\"M2 7.82a15 15 0 0 1 20 0\" /><path d=\"m20.772 16.852.924-.383\" /><path d=\"m20.772 19.148.924.383\" /><path d=\"M5 11.858a10 10 0 0 1 11.5-1.785\" /><path d=\"M8.5 15.429a5 5 0 0 1 2.413-1.31\" /><circle cx=\"18\" cy=\"18\" r=\"3\" />");
    /// <summary>Lucide <c>wifi-high</c>.</summary>
    public static global::Lumeo.IconSource WifiHigh => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h.01\" /><path d=\"M5 12.859a10 10 0 0 1 14 0\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" />");
    /// <summary>Lucide <c>wifi-low</c>.</summary>
    public static global::Lumeo.IconSource WifiLow => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h.01\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" />");
    /// <summary>Lucide <c>wifi-off</c>.</summary>
    public static global::Lumeo.IconSource WifiOff => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h.01\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" /><path d=\"M5 12.859a10 10 0 0 1 5.17-2.69\" /><path d=\"M19 12.859a10 10 0 0 0-2.007-1.523\" /><path d=\"M2 8.82a15 15 0 0 1 4.177-2.643\" /><path d=\"M22 8.82a15 15 0 0 0-11.288-3.764\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>wifi-pen</c>.</summary>
    public static global::Lumeo.IconSource WifiPen => global::Lumeo.IconSource.Stroke("<path d=\"M2 8.82a15 15 0 0 1 20 0\" /><path d=\"M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" /><path d=\"M5 12.859a10 10 0 0 1 10.5-2.222\" /><path d=\"M8.5 16.429a5 5 0 0 1 3-1.406\" />");
    /// <summary>Lucide <c>wifi-sync</c>.</summary>
    public static global::Lumeo.IconSource WifiSync => global::Lumeo.IconSource.Stroke("<path d=\"M11.965 10.105v4L13.5 12.5a5 5 0 0 1 8 1.5\" /><path d=\"M11.965 14.105h4\" /><path d=\"M17.965 18.105h4L20.43 19.71a5 5 0 0 1-8-1.5\" /><path d=\"M2 8.82a15 15 0 0 1 20 0\" /><path d=\"M21.965 22.105v-4\" /><path d=\"M5 12.86a10 10 0 0 1 3-2.032\" /><path d=\"M8.5 16.429h.01\" />");
    /// <summary>Lucide <c>wifi-zero</c>.</summary>
    public static global::Lumeo.IconSource WifiZero => global::Lumeo.IconSource.Stroke("<path d=\"M12 20h.01\" />");
    /// <summary>Lucide <c>wind</c>.</summary>
    public static global::Lumeo.IconSource Wind => global::Lumeo.IconSource.Stroke("<path d=\"M12.8 19.6A2 2 0 1 0 14 16H2\" /><path d=\"M17.5 8a2.5 2.5 0 1 1 2 4H2\" /><path d=\"M9.8 4.4A2 2 0 1 1 11 8H2\" />");
    /// <summary>Lucide <c>wind-arrow-down</c>.</summary>
    public static global::Lumeo.IconSource WindArrowDown => global::Lumeo.IconSource.Stroke("<path d=\"M10 2v8\" /><path d=\"M12.8 21.6A2 2 0 1 0 14 18H2\" /><path d=\"M17.5 10a2.5 2.5 0 1 1 2 4H2\" /><path d=\"m6 6 4 4 4-4\" />");
    /// <summary>Lucide <c>wine</c>.</summary>
    public static global::Lumeo.IconSource Wine => global::Lumeo.IconSource.Stroke("<path d=\"M8 22h8\" /><path d=\"M7 10h10\" /><path d=\"M12 15v7\" /><path d=\"M12 15a5 5 0 0 0 5-5c0-2-.5-4-2-8H9c-1.5 4-2 6-2 8a5 5 0 0 0 5 5Z\" />");
    /// <summary>Lucide <c>wine-off</c>.</summary>
    public static global::Lumeo.IconSource WineOff => global::Lumeo.IconSource.Stroke("<path d=\"M8 22h8\" /><path d=\"M7 10h3m7 0h-1.343\" /><path d=\"M12 15v7\" /><path d=\"M7.307 7.307A12.33 12.33 0 0 0 7 10a5 5 0 0 0 7.391 4.391M8.638 2.981C8.75 2.668 8.872 2.34 9 2h6c1.5 4 2 6 2 8 0 .407-.05.809-.145 1.198\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" />");
    /// <summary>Lucide <c>workflow</c>.</summary>
    public static global::Lumeo.IconSource Workflow => global::Lumeo.IconSource.Stroke("<rect width=\"8\" height=\"8\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M7 11v4a2 2 0 0 0 2 2h4\" /><rect width=\"8\" height=\"8\" x=\"13\" y=\"13\" rx=\"2\" />");
    /// <summary>Lucide <c>worm</c>.</summary>
    public static global::Lumeo.IconSource Worm => global::Lumeo.IconSource.Stroke("<path d=\"m19 12-1.5 3\" /><path d=\"M19.63 18.81 22 20\" /><path d=\"M6.47 8.23a1.68 1.68 0 0 1 2.44 1.93l-.64 2.08a6.76 6.76 0 0 0 10.16 7.67l.42-.27a1 1 0 1 0-2.73-4.21l-.42.27a1.76 1.76 0 0 1-2.63-1.99l.64-2.08A6.66 6.66 0 0 0 3.94 3.9l-.7.4a1 1 0 1 0 2.55 4.34z\" />");
    /// <summary>Lucide <c>wrench</c>.</summary>
    public static global::Lumeo.IconSource Wrench => global::Lumeo.IconSource.Stroke("<path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z\" />");
    /// <summary>Lucide <c>wrench-off</c>.</summary>
    public static global::Lumeo.IconSource WrenchOff => global::Lumeo.IconSource.Stroke("<path d=\"M10.747 5.093a6 6 0 0 1 6.841-2.882c.438.12.54.662.219.984L14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-2.882 6.842\" /><path d=\"m13.5 13.5-7.88 7.88a1 1 0 0 1-2.999-3l7.88-7.88\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>x</c>.</summary>
    public static global::Lumeo.IconSource X => global::Lumeo.IconSource.Stroke("<path d=\"M18 6 6 18\" /><path d=\"m6 6 12 12\" />");
    /// <summary>Lucide <c>x-line-top</c>.</summary>
    public static global::Lumeo.IconSource XLineTop => global::Lumeo.IconSource.Stroke("<path d=\"M18 4H6\" /><path d=\"M18 8 6 20\" /><path d=\"m6 8 12 12\" />");
    /// <summary>Lucide <c>zap</c>.</summary>
    public static global::Lumeo.IconSource Zap => global::Lumeo.IconSource.Stroke("<path d=\"M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z\" />");
    /// <summary>Lucide <c>zap-off</c>.</summary>
    public static global::Lumeo.IconSource ZapOff => global::Lumeo.IconSource.Stroke("<path d=\"M10.513 4.856 13.12 2.17a.5.5 0 0 1 .86.46l-1.377 4.317\" /><path d=\"M15.656 10H20a1 1 0 0 1 .78 1.63l-1.72 1.773\" /><path d=\"M16.273 16.273 10.88 21.83a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14H4a1 1 0 0 1-.78-1.63l4.507-4.643\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>zodiac-aquarius</c>.</summary>
    public static global::Lumeo.IconSource ZodiacAquarius => global::Lumeo.IconSource.Stroke("<path d=\"m2 10 2.456-3.684a.7.7 0 0 1 1.106-.013l2.39 3.413a.7.7 0 0 0 1.096-.001l2.402-3.432a.7.7 0 0 1 1.098 0l2.402 3.432a.7.7 0 0 0 1.098 0l2.389-3.413a.7.7 0 0 1 1.106.013L22 10\" /><path d=\"m2 18.002 2.456-3.684a.7.7 0 0 1 1.106-.013l2.39 3.413a.7.7 0 0 0 1.097 0l2.402-3.432a.7.7 0 0 1 1.098 0l2.402 3.432a.7.7 0 0 0 1.098 0l2.389-3.413a.7.7 0 0 1 1.106.013L22 18.002\" />");
    /// <summary>Lucide <c>zodiac-aries</c>.</summary>
    public static global::Lumeo.IconSource ZodiacAries => global::Lumeo.IconSource.Stroke("<path d=\"M12 7.5a4.5 4.5 0 1 1 5 4.5\" /><path d=\"M7 12a4.5 4.5 0 1 1 5-4.5V21\" />");
    /// <summary>Lucide <c>zodiac-cancer</c>.</summary>
    public static global::Lumeo.IconSource ZodiacCancer => global::Lumeo.IconSource.Stroke("<path d=\"M21 14.5A9 6.5 0 0 1 5.5 19\" /><path d=\"M3 9.5A9 6.5 0 0 1 18.5 5\" /><circle cx=\"17.5\" cy=\"14.5\" r=\"3.5\" /><circle cx=\"6.5\" cy=\"9.5\" r=\"3.5\" />");
    /// <summary>Lucide <c>zodiac-capricorn</c>.</summary>
    public static global::Lumeo.IconSource ZodiacCapricorn => global::Lumeo.IconSource.Stroke("<path d=\"M11 21a3 3 0 0 0 3-3V6.5a1 1 0 0 0-7 0\" /><path d=\"M7 19V6a3 3 0 0 0-3-3h0\" /><circle cx=\"17\" cy=\"17\" r=\"3\" />");
    /// <summary>Lucide <c>zodiac-gemini</c>.</summary>
    public static global::Lumeo.IconSource ZodiacGemini => global::Lumeo.IconSource.Stroke("<path d=\"M16 4.525v14.948\" /><path d=\"M20 3A17 17 0 0 1 4 3\" /><path d=\"M4 21a17 17 0 0 1 16 0\" /><path d=\"M8 4.525v14.948\" />");
    /// <summary>Lucide <c>zodiac-leo</c>.</summary>
    public static global::Lumeo.IconSource ZodiacLeo => global::Lumeo.IconSource.Stroke("<path d=\"M10 16c0-4-3-4.5-3-8a5 5 0 0 1 10 0c0 3.466-3 6.196-3 10a3 3 0 0 0 6 0\" /><circle cx=\"7\" cy=\"16\" r=\"3\" />");
    /// <summary>Lucide <c>zodiac-libra</c>.</summary>
    public static global::Lumeo.IconSource ZodiacLibra => global::Lumeo.IconSource.Stroke("<path d=\"M3 16h6.857c.162-.012.19-.323.038-.38a6 6 0 1 1 4.212 0c-.153.057-.125.368.038.38H21\" /><path d=\"M3 20h18\" />");
    /// <summary>Lucide <c>zodiac-ophiuchus</c>.</summary>
    public static global::Lumeo.IconSource ZodiacOphiuchus => global::Lumeo.IconSource.Stroke("<path d=\"M3 10A6.06 6.06 0 0 1 12 10 A6.06 6.06 0 0 0 21 10\" /><path d=\"M6 3v12a6 6 0 0 0 12 0V3\" />");
    /// <summary>Lucide <c>zodiac-pisces</c>.</summary>
    public static global::Lumeo.IconSource ZodiacPisces => global::Lumeo.IconSource.Stroke("<path d=\"M19 21a15 15 0 0 1 0-18\" /><path d=\"M20 12H4\" /><path d=\"M5 3a15 15 0 0 1 0 18\" />");
    /// <summary>Lucide <c>zodiac-sagittarius</c>.</summary>
    public static global::Lumeo.IconSource ZodiacSagittarius => global::Lumeo.IconSource.Stroke("<path d=\"M15 3h6v6\" /><path d=\"M21 3 3 21\" /><path d=\"m9 9 6 6\" />");
    /// <summary>Lucide <c>zodiac-scorpio</c>.</summary>
    public static global::Lumeo.IconSource ZodiacScorpio => global::Lumeo.IconSource.Stroke("<path d=\"M10 19V5.5a1 1 0 0 1 5 0V17a2 2 0 0 0 2 2h5l-3-3\" /><path d=\"m22 19-3 3\" /><path d=\"M5 19V5.5a1 1 0 0 1 5 0\" /><path d=\"M5 5.5A2.5 2.5 0 0 0 2.5 3\" />");
    /// <summary>Lucide <c>zodiac-taurus</c>.</summary>
    public static global::Lumeo.IconSource ZodiacTaurus => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"15\" r=\"6\" /><path d=\"M18 3A6 6 0 0 1 6 3\" />");
    /// <summary>Lucide <c>zodiac-virgo</c>.</summary>
    public static global::Lumeo.IconSource ZodiacVirgo => global::Lumeo.IconSource.Stroke("<path d=\"M11 5.5a1 1 0 0 1 5 0V16a5 5 0 0 0 5 5\" /><path d=\"M16 11.5a1 1 0 0 1 5 0V16a5 5 0 0 1-5 5\" /><path d=\"M6 19V6a3 3 0 0 0-3-3h0\" /><path d=\"M6 5.5a1 1 0 0 1 5 0V19\" />");
    /// <summary>Lucide <c>zoom-in</c>.</summary>
    public static global::Lumeo.IconSource ZoomIn => global::Lumeo.IconSource.Stroke("<circle cx=\"11\" cy=\"11\" r=\"8\" /><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" /><line x1=\"11\" x2=\"11\" y1=\"8\" y2=\"14\" /><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>zoom-out</c>.</summary>
    public static global::Lumeo.IconSource ZoomOut => global::Lumeo.IconSource.Stroke("<circle cx=\"11\" cy=\"11\" r=\"8\" /><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" /><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" />");
}
