namespace Lumeo;

/// <summary>Calendar unit a <see cref="TimeTickStep"/> is expressed in.</summary>
internal enum TimeTickUnit
{
    Millisecond,
    Second,
    Minute,
    Hour,
    Day,
    Week,
    Month,
    Year,
}

/// <summary>A tick interval: <paramref name="Multiple"/> of <paramref name="Unit"/>
/// (e.g. "every 15 minutes", "every 3 months").</summary>
internal readonly record struct TimeTickStep(TimeTickUnit Unit, int Multiple);

/// <summary>
/// Time-axis tick INTERVAL selection (spec §2.1's "genuinely new piece of
/// work") — choosing ms/s/min/hour/day/week/month/year from a domain span and a
/// target tick count, the way d3-time/ECharts' own time axis does. Calendar
/// units (month/year) vary in length, so ticks are generated by calendar
/// arithmetic (<see cref="DateTimeOffset.AddMonths"/> etc.), not by dividing the
/// span into equal millisecond chunks.
/// </summary>
internal static class TimeTicks
{
    // Ordered from finest to coarsest. Quarter is deliberately folded into
    // "3 months" rather than a distinct unit — same calendar arithmetic, one
    // fewer case to hand-roll Advance()/AlignDown() for.
    private static readonly TimeTickStep[] Steps =
    {
        new(TimeTickUnit.Millisecond, 1), new(TimeTickUnit.Millisecond, 5), new(TimeTickUnit.Millisecond, 10),
        new(TimeTickUnit.Millisecond, 50), new(TimeTickUnit.Millisecond, 100), new(TimeTickUnit.Millisecond, 500),
        new(TimeTickUnit.Second, 1), new(TimeTickUnit.Second, 5), new(TimeTickUnit.Second, 15), new(TimeTickUnit.Second, 30),
        new(TimeTickUnit.Minute, 1), new(TimeTickUnit.Minute, 5), new(TimeTickUnit.Minute, 15), new(TimeTickUnit.Minute, 30),
        new(TimeTickUnit.Hour, 1), new(TimeTickUnit.Hour, 3), new(TimeTickUnit.Hour, 6), new(TimeTickUnit.Hour, 12),
        new(TimeTickUnit.Day, 1), new(TimeTickUnit.Day, 2),
        new(TimeTickUnit.Week, 1),
        new(TimeTickUnit.Month, 1), new(TimeTickUnit.Month, 3), new(TimeTickUnit.Month, 6),
        new(TimeTickUnit.Year, 1),
    };

    /// <summary>Approximate duration in ms — "approximate" because Month/Year
    /// are calendar units of varying real length; used only to RANK candidate
    /// steps against the target count, never to place a tick (placement uses
    /// exact calendar arithmetic in <see cref="Compute"/>).</summary>
    public static double ApproxDurationMs(TimeTickStep step) => step.Unit switch
    {
        TimeTickUnit.Millisecond => step.Multiple,
        TimeTickUnit.Second => step.Multiple * 1_000.0,
        TimeTickUnit.Minute => step.Multiple * 60_000.0,
        TimeTickUnit.Hour => step.Multiple * 3_600_000.0,
        TimeTickUnit.Day => step.Multiple * 86_400_000.0,
        TimeTickUnit.Week => step.Multiple * 7 * 86_400_000.0,
        TimeTickUnit.Month => step.Multiple * 30.44 * 86_400_000.0,
        TimeTickUnit.Year => step.Multiple * 365.25 * 86_400_000.0,
        _ => throw new ArgumentOutOfRangeException(nameof(step)),
    };

    /// <summary>Picks the finest predefined step whose tick count over
    /// <c>[start,end]</c> does not exceed <paramref name="targetCount"/>; falls
    /// back to an N-year step (N chosen via <see cref="NiceTicks.NiceNumber"/>)
    /// for spans wider than the table covers.</summary>
    public static TimeTickStep SelectStep(DateTimeOffset start, DateTimeOffset end, int targetCount)
    {
        if (targetCount < 1) targetCount = 1;
        var spanMs = (end - start).TotalMilliseconds;
        if (spanMs <= 0) return Steps[0];

        foreach (var step in Steps)
        {
            var count = spanMs / ApproxDurationMs(step);
            if (count <= targetCount) return step;
        }

        var spanYears = spanMs / ApproxDurationMs(new TimeTickStep(TimeTickUnit.Year, 1));
        var niceYears = NiceTicks.NiceNumber(spanYears / targetCount, true);
        return new TimeTickStep(TimeTickUnit.Year, Math.Max(1, (int)Math.Round(niceYears)));
    }

    /// <summary>Generates the actual tick timestamps for <c>[start,end]</c>,
    /// aligned to natural calendar boundaries for the chosen step (e.g. every-3-
    /// months ticks land on Jan/Apr/Jul/Oct 1st, not on an arbitrary offset from
    /// <paramref name="start"/>).</summary>
    public static IReadOnlyList<DateTimeOffset> Compute(DateTimeOffset start, DateTimeOffset end, int targetCount = 6)
    {
        if (end < start) (start, end) = (end, start);
        var step = SelectStep(start, end, targetCount);

        var ticks = new List<DateTimeOffset>();
        var cur = AlignDown(start, step);
        // Guard against a pathological infinite loop (shouldn't happen given the
        // step table, but a caller-supplied absurd targetCount could still spin).
        var guard = 0;
        while (cur <= end && guard++ < 100_000)
        {
            if (cur >= start) ticks.Add(cur);
            cur = Advance(cur, step);
        }
        if (ticks.Count == 0) ticks.Add(start);
        return ticks;
    }

    private static DateTimeOffset AlignDown(DateTimeOffset t, TimeTickStep step)
    {
        switch (step.Unit)
        {
            case TimeTickUnit.Millisecond:
                return t.AddTicks(-(t.Ticks % (step.Multiple * TimeSpan.TicksPerMillisecond)));
            case TimeTickUnit.Second:
            {
                var floor = new DateTimeOffset(t.Year, t.Month, t.Day, t.Hour, t.Minute, t.Second, t.Offset);
                return floor.AddSeconds(-(floor.Second % step.Multiple));
            }
            case TimeTickUnit.Minute:
            {
                var floor = new DateTimeOffset(t.Year, t.Month, t.Day, t.Hour, t.Minute, 0, t.Offset);
                return floor.AddMinutes(-(floor.Minute % step.Multiple));
            }
            case TimeTickUnit.Hour:
            {
                var floor = new DateTimeOffset(t.Year, t.Month, t.Day, t.Hour, 0, 0, t.Offset);
                return floor.AddHours(-(floor.Hour % step.Multiple));
            }
            case TimeTickUnit.Day:
                return new DateTimeOffset(t.Year, t.Month, t.Day, 0, 0, 0, t.Offset);
            case TimeTickUnit.Week:
            {
                var day = new DateTimeOffset(t.Year, t.Month, t.Day, 0, 0, 0, t.Offset);
                // ISO-ish: align to Monday.
                var offset = ((int)day.DayOfWeek + 6) % 7;
                return day.AddDays(-offset);
            }
            case TimeTickUnit.Month:
            {
                var monthIndex0 = t.Month - 1;
                var alignedMonth0 = monthIndex0 - (monthIndex0 % step.Multiple);
                return new DateTimeOffset(t.Year, alignedMonth0 + 1, 1, 0, 0, 0, t.Offset);
            }
            case TimeTickUnit.Year:
                return new DateTimeOffset(t.Year - (t.Year % step.Multiple), 1, 1, 0, 0, 0, t.Offset);
            default:
                throw new ArgumentOutOfRangeException(nameof(step));
        }
    }

    private static DateTimeOffset Advance(DateTimeOffset t, TimeTickStep step) => step.Unit switch
    {
        TimeTickUnit.Millisecond => t.AddMilliseconds(step.Multiple),
        TimeTickUnit.Second => t.AddSeconds(step.Multiple),
        TimeTickUnit.Minute => t.AddMinutes(step.Multiple),
        TimeTickUnit.Hour => t.AddHours(step.Multiple),
        TimeTickUnit.Day => t.AddDays(step.Multiple),
        TimeTickUnit.Week => t.AddDays(step.Multiple * 7),
        TimeTickUnit.Month => t.AddMonths(step.Multiple),
        TimeTickUnit.Year => t.AddYears(step.Multiple),
        _ => throw new ArgumentOutOfRangeException(nameof(step)),
    };
}
