using System.Text;
using System.Text.Json;
using System.Globalization;

namespace Lumeo.IconGen;

/// <summary>One icon ready to emit: its PascalCase C# name, its upstream name, and parsed markup.</summary>
public readonly record struct EmitIcon(string Name, string Upstream, ParsedIcon Parsed);

/// <summary>
/// Emits a pack's icons as committed <c>.g.cs</c> source — one expression-bodied
/// <c>IconSource</c> property per icon (never a <c>static readonly</c> field, so a trimmer keeps
/// only referenced icons) — split into <c>~ChunkSize</c> partial files, plus a <c>manifest.json</c>
/// name list for docs/MCP.
/// </summary>
public static class IconEmitter
{
    private const string DefaultViewBox = "0 0 24 24";

    // Icon names that collide with an inherited System.Object member (e.g. Phosphor's `equals`
    // icon → `Equals`). A same-named static property hides the inherited member, which -warnaserror
    // turns into a fatal CS0108; the `new` modifier declares the hiding intentional and silences it
    // while keeping the member name identical to upstream.
    private static readonly HashSet<string> ObjectMembers = new(StringComparer.Ordinal)
    {
        "Equals", "GetHashCode", "GetType", "ToString", "ReferenceEquals", "MemberwiseClone", "Finalize",
    };

    /// <summary>Emits every file for <paramref name="config"/>; returns the written file paths.</summary>
    public static IReadOnlyList<string> Emit(PackConfig config, IReadOnlyList<EmitIcon> icons)
    {
        Directory.CreateDirectory(config.OutputDir);
        var written = new List<string>();

        var chunks = icons
            .Select((icon, i) => (icon, i))
            .GroupBy(x => x.i / config.ChunkSize, x => x.icon)
            .ToList();

        var partial = chunks.Count > 1;

        for (var c = 0; c < chunks.Count; c++)
        {
            var suffix = c == 0 ? "" : $".{c}";
            var path = Path.Combine(config.OutputDir, $"{config.OutputBaseName}{suffix}.g.cs");
            File.WriteAllText(path, RenderChunk(config, chunks[c].ToList(), partial), new UTF8Encoding(false));
            written.Add(path);
        }

        var manifestPath = Path.Combine(config.OutputDir, $"{config.OutputBaseName}.manifest.json");
        File.WriteAllText(manifestPath, RenderManifest(config, icons), new UTF8Encoding(false));
        written.Add(manifestPath);

        return written;
    }

    private static string RenderChunk(PackConfig config, List<EmitIcon> icons, bool partial)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated />\n");
        foreach (var line in config.LicenseHeader.Replace("\r\n", "\n").Split('\n'))
            sb.Append("// ").Append(line).Append('\n');
        sb.Append("// Source: ").Append(config.PackName).Append(" v").Append(config.Version).Append('\n');
        sb.Append("// Generated by tools/Lumeo.IconGen — DO NOT EDIT BY HAND.\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace ").Append(config.Namespace).Append(";\n\n");

        if (!partial)
        {
            sb.Append("/// <summary>Vendored ").Append(config.PackName)
              .Append(" icons (v").Append(config.Version)
              .Append("). One <see cref=\"global::Lumeo.IconSource\"/> per icon.</summary>\n");
        }

        sb.Append("public static ").Append(partial ? "partial " : "").Append("class ")
          .Append(config.ClassName).Append('\n').Append("{\n");

        foreach (var icon in icons)
        {
            sb.Append("    /// <summary>").Append(config.PackName).Append(" <c>")
              .Append(icon.Upstream).Append("</c>.</summary>\n");
            var newModifier = ObjectMembers.Contains(icon.Name) ? "new " : "";
            sb.Append("    public static ").Append(newModifier).Append("global::Lumeo.IconSource ")
              .Append(icon.Name).Append(" => ").Append(RenderFactory(config, icon.Parsed)).Append(";\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string RenderFactory(PackConfig config, ParsedIcon icon)
    {
        var content = Quote(icon.Content);
        var viewBoxDefault = icon.ViewBox == DefaultViewBox;

        if (config.Style == GenRenderStyle.Stroke)
        {
            var widthDefault = config.StrokeWidth == 2d;
            if (!widthDefault)
            {
                var vb = Quote(icon.ViewBox);
                var w = config.StrokeWidth.ToString(CultureInfo.InvariantCulture);
                return $"global::Lumeo.IconSource.Stroke({content}, {vb}, {w})";
            }
            return viewBoxDefault
                ? $"global::Lumeo.IconSource.Stroke({content})"
                : $"global::Lumeo.IconSource.Stroke({content}, {Quote(icon.ViewBox)})";
        }

        return viewBoxDefault
            ? $"global::Lumeo.IconSource.Fill({content})"
            : $"global::Lumeo.IconSource.Fill({content}, {Quote(icon.ViewBox)})";
    }

    private static string Quote(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string RenderManifest(PackConfig config, IReadOnlyList<EmitIcon> icons)
    {
        var manifest = new
        {
            pack = config.PackName,
            @class = config.ClassName,
            @namespace = config.Namespace,
            version = config.Version,
            style = config.Style.ToString(),
            count = icons.Count,
            icons = icons.Select(i => i.Name).ToArray(),
        };
        return JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });
    }
}
