// <auto-generated />
// Lucide icons — ISC License.
// https://github.com/lucide-icons/lucide
// 
// ISC License
// 
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of
// Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
// 
// Permission to use, copy, modify, and/or distribute this software for any purpose with or
// without fee is hereby granted, provided that the above copyright notice and this permission
// notice appear in all copies.
// 
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO
// THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT
// SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR
// ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
// CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE
// OR PERFORMANCE OF THIS SOFTWARE.
// Source: Lucide v1.23.0
// Generated by tools/Lumeo.IconGen — DO NOT EDIT BY HAND.
#nullable enable

namespace Lumeo;

/// <summary>Vendored Lucide icons (v1.23.0). One <see cref="global::Lumeo.IconSource"/> per icon.</summary>
public static class LumeoIcons
{
    /// <summary>Lucide <c>accessibility</c>.</summary>
    public static global::Lumeo.IconSource Accessibility => global::Lumeo.IconSource.Stroke("<circle cx=\"16\" cy=\"4\" r=\"1\" /><path d=\"m18 19 1-7-6 1\" /><path d=\"m5 8 3-3 5.5 3-2.36 3.5\" /><path d=\"M4.24 14.5a5 5 0 0 0 6.88 6\" /><path d=\"M13.76 17.5a5 5 0 0 0-6.88-6\" />");
    /// <summary>Lucide <c>activity</c>.</summary>
    public static global::Lumeo.IconSource Activity => global::Lumeo.IconSource.Stroke("<path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\" />");
    /// <summary>Lucide <c>align-center-horizontal</c>.</summary>
    public static global::Lumeo.IconSource AlignCenterHorizontal => global::Lumeo.IconSource.Stroke("<path d=\"M2 12h20\" /><path d=\"M10 16v4a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-4\" /><path d=\"M10 8V4a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v4\" /><path d=\"M20 16v1a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-1\" /><path d=\"M14 8V7c0-1.1.9-2 2-2h2a2 2 0 0 1 2 2v1\" />");
    /// <summary>Lucide <c>align-end-horizontal</c>.</summary>
    public static global::Lumeo.IconSource AlignEndHorizontal => global::Lumeo.IconSource.Stroke("<rect width=\"6\" height=\"16\" x=\"4\" y=\"2\" rx=\"2\" /><rect width=\"6\" height=\"9\" x=\"14\" y=\"9\" rx=\"2\" /><path d=\"M22 22H2\" />");
    /// <summary>Lucide <c>align-start-horizontal</c>.</summary>
    public static global::Lumeo.IconSource AlignStartHorizontal => global::Lumeo.IconSource.Stroke("<rect width=\"6\" height=\"16\" x=\"4\" y=\"6\" rx=\"2\" /><rect width=\"6\" height=\"9\" x=\"14\" y=\"6\" rx=\"2\" /><path d=\"M22 2H2\" />");
    /// <summary>Lucide <c>apple</c>.</summary>
    public static global::Lumeo.IconSource Apple => global::Lumeo.IconSource.Stroke("<path d=\"M12 6.528V3a1 1 0 0 1 1-1h0\" /><path d=\"M18.237 21A15 15 0 0 0 22 11a6 6 0 0 0-10-4.472A6 6 0 0 0 2 11a15.1 15.1 0 0 0 3.763 10 3 3 0 0 0 3.648.648 5.5 5.5 0 0 1 5.178 0A3 3 0 0 0 18.237 21\" />");
    /// <summary>Lucide <c>archive</c>.</summary>
    public static global::Lumeo.IconSource Archive => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"5\" x=\"2\" y=\"3\" rx=\"1\" /><path d=\"M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8\" /><path d=\"M10 12h4\" />");
    /// <summary>Lucide <c>arrow-down</c>.</summary>
    public static global::Lumeo.IconSource ArrowDown => global::Lumeo.IconSource.Stroke("<path d=\"M12 5v14\" /><path d=\"m19 12-7 7-7-7\" />");
    /// <summary>Lucide <c>arrow-left</c>.</summary>
    public static global::Lumeo.IconSource ArrowLeft => global::Lumeo.IconSource.Stroke("<path d=\"m12 19-7-7 7-7\" /><path d=\"M19 12H5\" />");
    /// <summary>Lucide <c>arrow-left-right</c>.</summary>
    public static global::Lumeo.IconSource ArrowLeftRight => global::Lumeo.IconSource.Stroke("<path d=\"M8 3 4 7l4 4\" /><path d=\"M4 7h16\" /><path d=\"m16 21 4-4-4-4\" /><path d=\"M20 17H4\" />");
    /// <summary>Lucide <c>arrow-right</c>.</summary>
    public static global::Lumeo.IconSource ArrowRight => global::Lumeo.IconSource.Stroke("<path d=\"M5 12h14\" /><path d=\"m12 5 7 7-7 7\" />");
    /// <summary>Lucide <c>arrow-up</c>.</summary>
    public static global::Lumeo.IconSource ArrowUp => global::Lumeo.IconSource.Stroke("<path d=\"m5 12 7-7 7 7\" /><path d=\"M12 19V5\" />");
    /// <summary>Lucide <c>arrow-up-down</c>.</summary>
    public static global::Lumeo.IconSource ArrowUpDown => global::Lumeo.IconSource.Stroke("<path d=\"m21 16-4 4-4-4\" /><path d=\"M17 20V4\" /><path d=\"m3 8 4-4 4 4\" /><path d=\"M7 4v16\" />");
    /// <summary>Lucide <c>arrow-up-right</c>.</summary>
    public static global::Lumeo.IconSource ArrowUpRight => global::Lumeo.IconSource.Stroke("<path d=\"M7 7h10v10\" /><path d=\"M7 17 17 7\" />");
    /// <summary>Lucide <c>at-sign</c>.</summary>
    public static global::Lumeo.IconSource AtSign => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8\" />");
    /// <summary>Lucide <c>badge-check</c>.</summary>
    public static global::Lumeo.IconSource BadgeCheck => global::Lumeo.IconSource.Stroke("<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" /><path d=\"m9 12 2 2 4-4\" />");
    /// <summary>Lucide <c>bell</c>.</summary>
    public static global::Lumeo.IconSource Bell => global::Lumeo.IconSource.Stroke("<path d=\"M10.268 21a2 2 0 0 0 3.464 0\" /><path d=\"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326\" />");
    /// <summary>Lucide <c>bell-off</c>.</summary>
    public static global::Lumeo.IconSource BellOff => global::Lumeo.IconSource.Stroke("<path d=\"M10.268 21a2 2 0 0 0 3.464 0\" /><path d=\"M17 17H4a1 1 0 0 1-.74-1.673C4.59 13.956 6 12.499 6 8a6 6 0 0 1 .258-1.742\" /><path d=\"m2 2 20 20\" /><path d=\"M8.668 3.01A6 6 0 0 1 18 8c0 2.687.77 4.653 1.707 6.05\" />");
    /// <summary>Lucide <c>blocks</c>.</summary>
    public static global::Lumeo.IconSource Blocks => global::Lumeo.IconSource.Stroke("<path d=\"M10 22V7a1 1 0 0 0-1-1H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5a1 1 0 0 0-1-1H2\" /><rect x=\"14\" y=\"2\" width=\"8\" height=\"8\" rx=\"1\" />");
    /// <summary>Lucide <c>bold</c>.</summary>
    public static global::Lumeo.IconSource Bold => global::Lumeo.IconSource.Stroke("<path d=\"M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8\" />");
    /// <summary>Lucide <c>book-open</c>.</summary>
    public static global::Lumeo.IconSource BookOpen => global::Lumeo.IconSource.Stroke("<path d=\"M12 7v14\" /><path d=\"M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z\" />");
    /// <summary>Lucide <c>bookmark</c>.</summary>
    public static global::Lumeo.IconSource Bookmark => global::Lumeo.IconSource.Stroke("<path d=\"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z\" />");
    /// <summary>Lucide <c>bookmark-check</c>.</summary>
    public static global::Lumeo.IconSource BookmarkCheck => global::Lumeo.IconSource.Stroke("<path d=\"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z\" /><path d=\"m9 10 2 2 4-4\" />");
    /// <summary>Lucide <c>box</c>.</summary>
    public static global::Lumeo.IconSource Box => global::Lumeo.IconSource.Stroke("<path d=\"M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z\" /><path d=\"m3.3 7 8.7 5 8.7-5\" /><path d=\"M12 22V12\" />");
    /// <summary>Lucide <c>braces</c>.</summary>
    public static global::Lumeo.IconSource Braces => global::Lumeo.IconSource.Stroke("<path d=\"M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1\" /><path d=\"M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1\" />");
    /// <summary>Lucide <c>building-2</c>.</summary>
    public static global::Lumeo.IconSource Building2 => global::Lumeo.IconSource.Stroke("<path d=\"M10 12h4\" /><path d=\"M10 8h4\" /><path d=\"M14 21v-3a2 2 0 0 0-4 0v3\" /><path d=\"M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2\" /><path d=\"M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16\" />");
    /// <summary>Lucide <c>calendar</c>.</summary>
    public static global::Lumeo.IconSource Calendar => global::Lumeo.IconSource.Stroke("<path d=\"M8 2v4\" /><path d=\"M16 2v4\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\" /><path d=\"M3 10h18\" />");
    /// <summary>Lucide <c>calendar-days</c>.</summary>
    public static global::Lumeo.IconSource CalendarDays => global::Lumeo.IconSource.Stroke("<path d=\"M8 2v4\" /><path d=\"M16 2v4\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\" /><path d=\"M3 10h18\" /><path d=\"M8 14h.01\" /><path d=\"M12 14h.01\" /><path d=\"M16 14h.01\" /><path d=\"M8 18h.01\" /><path d=\"M12 18h.01\" /><path d=\"M16 18h.01\" />");
    /// <summary>Lucide <c>calendar-plus</c>.</summary>
    public static global::Lumeo.IconSource CalendarPlus => global::Lumeo.IconSource.Stroke("<path d=\"M16 19h6\" /><path d=\"M16 2v4\" /><path d=\"M19 16v6\" /><path d=\"M21 12.598V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8.5\" /><path d=\"M3 10h18\" /><path d=\"M8 2v4\" />");
    /// <summary>Lucide <c>camera</c>.</summary>
    public static global::Lumeo.IconSource Camera => global::Lumeo.IconSource.Stroke("<path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\" /><circle cx=\"12\" cy=\"13\" r=\"3\" />");
    /// <summary>Lucide <c>chart-bar</c>.</summary>
    public static global::Lumeo.IconSource ChartBar => global::Lumeo.IconSource.Stroke("<path d=\"M3 3v16a2 2 0 0 0 2 2h16\" /><path d=\"M7 16h8\" /><path d=\"M7 11h12\" /><path d=\"M7 6h3\" />");
    /// <summary>Lucide <c>chart-line</c>.</summary>
    public static global::Lumeo.IconSource ChartLine => global::Lumeo.IconSource.Stroke("<path d=\"M3 3v16a2 2 0 0 0 2 2h16\" /><path d=\"m19 9-5 5-4-4-3 3\" />");
    /// <summary>Lucide <c>chart-pie</c>.</summary>
    public static global::Lumeo.IconSource ChartPie => global::Lumeo.IconSource.Stroke("<path d=\"M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z\" /><path d=\"M21.21 15.89A10 10 0 1 1 8 2.83\" />");
    /// <summary>Lucide <c>check</c>.</summary>
    public static global::Lumeo.IconSource Check => global::Lumeo.IconSource.Stroke("<path d=\"M20 6 9 17l-5-5\" />");
    /// <summary>Lucide <c>check-check</c>.</summary>
    public static global::Lumeo.IconSource CheckCheck => global::Lumeo.IconSource.Stroke("<path d=\"M18 6 7 17l-5-5\" /><path d=\"m22 10-7.5 7.5L13 16\" />");
    /// <summary>Lucide <c>chevron-down</c>.</summary>
    public static global::Lumeo.IconSource ChevronDown => global::Lumeo.IconSource.Stroke("<path d=\"m6 9 6 6 6-6\" />");
    /// <summary>Lucide <c>chevron-left</c>.</summary>
    public static global::Lumeo.IconSource ChevronLeft => global::Lumeo.IconSource.Stroke("<path d=\"m15 18-6-6 6-6\" />");
    /// <summary>Lucide <c>chevron-right</c>.</summary>
    public static global::Lumeo.IconSource ChevronRight => global::Lumeo.IconSource.Stroke("<path d=\"m9 18 6-6-6-6\" />");
    /// <summary>Lucide <c>chevron-up</c>.</summary>
    public static global::Lumeo.IconSource ChevronUp => global::Lumeo.IconSource.Stroke("<path d=\"m18 15-6-6-6 6\" />");
    /// <summary>Lucide <c>chevrons-left</c>.</summary>
    public static global::Lumeo.IconSource ChevronsLeft => global::Lumeo.IconSource.Stroke("<path d=\"m11 17-5-5 5-5\" /><path d=\"m18 17-5-5 5-5\" />");
    /// <summary>Lucide <c>chevrons-right</c>.</summary>
    public static global::Lumeo.IconSource ChevronsRight => global::Lumeo.IconSource.Stroke("<path d=\"m6 17 5-5-5-5\" /><path d=\"m13 17 5-5-5-5\" />");
    /// <summary>Lucide <c>chevrons-up-down</c>.</summary>
    public static global::Lumeo.IconSource ChevronsUpDown => global::Lumeo.IconSource.Stroke("<path d=\"m7 15 5 5 5-5\" /><path d=\"m7 9 5-5 5 5\" />");
    /// <summary>Lucide <c>circle</c>.</summary>
    public static global::Lumeo.IconSource Circle => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" />");
    /// <summary>Lucide <c>circle-alert</c>.</summary>
    public static global::Lumeo.IconSource CircleAlert => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" /><line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" />");
    /// <summary>Lucide <c>circle-check</c>.</summary>
    public static global::Lumeo.IconSource CircleCheck => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"m9 12 2 2 4-4\" />");
    /// <summary>Lucide <c>circle-dot</c>.</summary>
    public static global::Lumeo.IconSource CircleDot => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><circle cx=\"12\" cy=\"12\" r=\"1\" />");
    /// <summary>Lucide <c>circle-x</c>.</summary>
    public static global::Lumeo.IconSource CircleX => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"m15 9-6 6\" /><path d=\"m9 9 6 6\" />");
    /// <summary>Lucide <c>clipboard</c>.</summary>
    public static global::Lumeo.IconSource Clipboard => global::Lumeo.IconSource.Stroke("<rect width=\"8\" height=\"4\" x=\"8\" y=\"2\" rx=\"1\" ry=\"1\" /><path d=\"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2\" />");
    /// <summary>Lucide <c>clipboard-list</c>.</summary>
    public static global::Lumeo.IconSource ClipboardList => global::Lumeo.IconSource.Stroke("<rect width=\"8\" height=\"4\" x=\"8\" y=\"2\" rx=\"1\" ry=\"1\" /><path d=\"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2\" /><path d=\"M12 11h4\" /><path d=\"M12 16h4\" /><path d=\"M8 11h.01\" /><path d=\"M8 16h.01\" />");
    /// <summary>Lucide <c>clock</c>.</summary>
    public static global::Lumeo.IconSource Clock => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M12 6v6l4 2\" />");
    /// <summary>Lucide <c>cloud</c>.</summary>
    public static global::Lumeo.IconSource Cloud => global::Lumeo.IconSource.Stroke("<path d=\"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z\" />");
    /// <summary>Lucide <c>code</c>.</summary>
    public static global::Lumeo.IconSource Code => global::Lumeo.IconSource.Stroke("<path d=\"m16 18 6-6-6-6\" /><path d=\"m8 6-6 6 6 6\" />");
    /// <summary>Lucide <c>cog</c>.</summary>
    public static global::Lumeo.IconSource Cog => global::Lumeo.IconSource.Stroke("<path d=\"M11 10.27 7 3.34\" /><path d=\"m11 13.73-4 6.93\" /><path d=\"M12 22v-2\" /><path d=\"M12 2v2\" /><path d=\"M14 12h8\" /><path d=\"m17 20.66-1-1.73\" /><path d=\"m17 3.34-1 1.73\" /><path d=\"M2 12h2\" /><path d=\"m20.66 17-1.73-1\" /><path d=\"m20.66 7-1.73 1\" /><path d=\"m3.34 17 1.73-1\" /><path d=\"m3.34 7 1.73 1\" /><circle cx=\"12\" cy=\"12\" r=\"2\" /><circle cx=\"12\" cy=\"12\" r=\"8\" />");
    /// <summary>Lucide <c>columns-3</c>.</summary>
    public static global::Lumeo.IconSource Columns3 => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M9 3v18\" /><path d=\"M15 3v18\" />");
    /// <summary>Lucide <c>compass</c>.</summary>
    public static global::Lumeo.IconSource Compass => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z\" />");
    /// <summary>Lucide <c>component</c>.</summary>
    public static global::Lumeo.IconSource Component => global::Lumeo.IconSource.Stroke("<path d=\"M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z\" /><path d=\"M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z\" /><path d=\"M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z\" /><path d=\"M8.916 4.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z\" />");
    /// <summary>Lucide <c>cookie</c>.</summary>
    public static global::Lumeo.IconSource Cookie => global::Lumeo.IconSource.Stroke("<path d=\"M12 2a10 10 0 1 0 10 10 4 4 0 0 1-5-5 4 4 0 0 1-5-5\" /><path d=\"M8.5 8.5v.01\" /><path d=\"M16 15.5v.01\" /><path d=\"M12 12v.01\" /><path d=\"M11 17v.01\" /><path d=\"M7 14v.01\" />");
    /// <summary>Lucide <c>copy</c>.</summary>
    public static global::Lumeo.IconSource Copy => global::Lumeo.IconSource.Stroke("<rect width=\"14\" height=\"14\" x=\"8\" y=\"8\" rx=\"2\" ry=\"2\" /><path d=\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\" />");
    /// <summary>Lucide <c>corner-up-left</c>.</summary>
    public static global::Lumeo.IconSource CornerUpLeft => global::Lumeo.IconSource.Stroke("<path d=\"M20 20v-7a4 4 0 0 0-4-4H4\" /><path d=\"M9 14 4 9l5-5\" />");
    /// <summary>Lucide <c>credit-card</c>.</summary>
    public static global::Lumeo.IconSource CreditCard => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"14\" x=\"2\" y=\"5\" rx=\"2\" /><line x1=\"2\" x2=\"22\" y1=\"10\" y2=\"10\" />");
    /// <summary>Lucide <c>database</c>.</summary>
    public static global::Lumeo.IconSource Database => global::Lumeo.IconSource.Stroke("<ellipse cx=\"12\" cy=\"5\" rx=\"9\" ry=\"3\" /><path d=\"M3 5V19A9 3 0 0 0 21 19V5\" /><path d=\"M3 12A9 3 0 0 0 21 12\" />");
    /// <summary>Lucide <c>disc-2</c>.</summary>
    public static global::Lumeo.IconSource Disc2 => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M12 12h.01\" />");
    /// <summary>Lucide <c>dollar-sign</c>.</summary>
    public static global::Lumeo.IconSource DollarSign => global::Lumeo.IconSource.Stroke("<line x1=\"12\" x2=\"12\" y1=\"2\" y2=\"22\" /><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\" />");
    /// <summary>Lucide <c>download</c>.</summary>
    public static global::Lumeo.IconSource Download => global::Lumeo.IconSource.Stroke("<path d=\"M12 15V3\" /><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\" /><path d=\"m7 10 5 5 5-5\" />");
    /// <summary>Lucide <c>ellipsis</c>.</summary>
    public static global::Lumeo.IconSource Ellipsis => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"1\" /><circle cx=\"19\" cy=\"12\" r=\"1\" /><circle cx=\"5\" cy=\"12\" r=\"1\" />");
    /// <summary>Lucide <c>ellipsis-vertical</c>.</summary>
    public static global::Lumeo.IconSource EllipsisVertical => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"1\" /><circle cx=\"12\" cy=\"5\" r=\"1\" /><circle cx=\"12\" cy=\"19\" r=\"1\" />");
    /// <summary>Lucide <c>eraser</c>.</summary>
    public static global::Lumeo.IconSource Eraser => global::Lumeo.IconSource.Stroke("<path d=\"M21 21H8a2 2 0 0 1-1.42-.587l-3.994-3.999a2 2 0 0 1 0-2.828l10-10a2 2 0 0 1 2.829 0l5.999 6a2 2 0 0 1 0 2.828L12.834 21\" /><path d=\"m5.082 11.09 8.828 8.828\" />");
    /// <summary>Lucide <c>external-link</c>.</summary>
    public static global::Lumeo.IconSource ExternalLink => global::Lumeo.IconSource.Stroke("<path d=\"M15 3h6v6\" /><path d=\"M10 14 21 3\" /><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\" />");
    /// <summary>Lucide <c>eye</c>.</summary>
    public static global::Lumeo.IconSource Eye => global::Lumeo.IconSource.Stroke("<path d=\"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0\" /><circle cx=\"12\" cy=\"12\" r=\"3\" />");
    /// <summary>Lucide <c>eye-off</c>.</summary>
    public static global::Lumeo.IconSource EyeOff => global::Lumeo.IconSource.Stroke("<path d=\"M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49\" /><path d=\"M14.084 14.158a3 3 0 0 1-4.242-4.242\" /><path d=\"M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143\" /><path d=\"m2 2 20 20\" />");
    /// <summary>Lucide <c>file</c>.</summary>
    public static global::Lumeo.IconSource File => global::Lumeo.IconSource.Stroke("<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />");
    /// <summary>Lucide <c>file-archive</c>.</summary>
    public static global::Lumeo.IconSource FileArchive => global::Lumeo.IconSource.Stroke("<path d=\"M13.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v11.5\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"M8 12v-1\" /><path d=\"M8 18v-2\" /><path d=\"M8 7V6\" /><circle cx=\"8\" cy=\"20\" r=\"2\" />");
    /// <summary>Lucide <c>file-code</c>.</summary>
    public static global::Lumeo.IconSource FileCode => global::Lumeo.IconSource.Stroke("<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"M10 12.5 8 15l2 2.5\" /><path d=\"m14 12.5 2 2.5-2 2.5\" />");
    /// <summary>Lucide <c>file-down</c>.</summary>
    public static global::Lumeo.IconSource FileDown => global::Lumeo.IconSource.Stroke("<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"M12 18v-6\" /><path d=\"m9 15 3 3 3-3\" />");
    /// <summary>Lucide <c>file-pen</c>.</summary>
    public static global::Lumeo.IconSource FilePen => global::Lumeo.IconSource.Stroke("<path d=\"M12.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v9.34\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"M10.378 12.622a1 1 0 0 1 3 3.003L8.36 20.637a2 2 0 0 1-.854.506l-2.867.837a.5.5 0 0 1-.62-.62l.836-2.869a2 2 0 0 1 .506-.853z\" />");
    /// <summary>Lucide <c>file-text</c>.</summary>
    public static global::Lumeo.IconSource FileText => global::Lumeo.IconSource.Stroke("<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"M10 9H8\" /><path d=\"M16 13H8\" /><path d=\"M16 17H8\" />");
    /// <summary>Lucide <c>file-x</c>.</summary>
    public static global::Lumeo.IconSource FileX => global::Lumeo.IconSource.Stroke("<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /><path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /><path d=\"m14.5 12.5-5 5\" /><path d=\"m9.5 12.5 5 5\" />");
    /// <summary>Lucide <c>film</c>.</summary>
    public static global::Lumeo.IconSource Film => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M7 3v18\" /><path d=\"M3 7.5h4\" /><path d=\"M3 12h18\" /><path d=\"M3 16.5h4\" /><path d=\"M17 3v18\" /><path d=\"M17 7.5h4\" /><path d=\"M17 16.5h4\" />");
    /// <summary>Lucide <c>flag</c>.</summary>
    public static global::Lumeo.IconSource Flag => global::Lumeo.IconSource.Stroke("<path d=\"M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528\" />");
    /// <summary>Lucide <c>folder</c>.</summary>
    public static global::Lumeo.IconSource Folder => global::Lumeo.IconSource.Stroke("<path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" />");
    /// <summary>Lucide <c>folder-git-2</c>.</summary>
    public static global::Lumeo.IconSource FolderGit2 => global::Lumeo.IconSource.Stroke("<path d=\"M18 19a5 5 0 0 1-5-5v8\" /><path d=\"M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v5\" /><circle cx=\"13\" cy=\"12\" r=\"2\" /><circle cx=\"20\" cy=\"19\" r=\"2\" />");
    /// <summary>Lucide <c>folder-open</c>.</summary>
    public static global::Lumeo.IconSource FolderOpen => global::Lumeo.IconSource.Stroke("<path d=\"m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2\" />");
    /// <summary>Lucide <c>folder-plus</c>.</summary>
    public static global::Lumeo.IconSource FolderPlus => global::Lumeo.IconSource.Stroke("<path d=\"M12 10v6\" /><path d=\"M9 13h6\" /><path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" />");
    /// <summary>Lucide <c>folder-up</c>.</summary>
    public static global::Lumeo.IconSource FolderUp => global::Lumeo.IconSource.Stroke("<path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" /><path d=\"M12 10v6\" /><path d=\"m9 13 3-3 3 3\" />");
    /// <summary>Lucide <c>forward</c>.</summary>
    public static global::Lumeo.IconSource Forward => global::Lumeo.IconSource.Stroke("<path d=\"m15 17 5-5-5-5\" /><path d=\"M4 18v-2a4 4 0 0 1 4-4h12\" />");
    /// <summary>Lucide <c>funnel</c>.</summary>
    public static global::Lumeo.IconSource Funnel => global::Lumeo.IconSource.Stroke("<path d=\"M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z\" />");
    /// <summary>Lucide <c>github</c>.</summary>
    public static global::Lumeo.IconSource Github => global::Lumeo.IconSource.Stroke("<path d=\"M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4\" /><path d=\"M9 18c-4.51 2-5-2-7-2\" />");
    /// <summary>Lucide <c>globe</c>.</summary>
    public static global::Lumeo.IconSource Globe => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20\" /><path d=\"M2 12h20\" />");
    /// <summary>Lucide <c>grip-horizontal</c>.</summary>
    public static global::Lumeo.IconSource GripHorizontal => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"9\" r=\"1\" /><circle cx=\"19\" cy=\"9\" r=\"1\" /><circle cx=\"5\" cy=\"9\" r=\"1\" /><circle cx=\"12\" cy=\"15\" r=\"1\" /><circle cx=\"19\" cy=\"15\" r=\"1\" /><circle cx=\"5\" cy=\"15\" r=\"1\" />");
    /// <summary>Lucide <c>grip-vertical</c>.</summary>
    public static global::Lumeo.IconSource GripVertical => global::Lumeo.IconSource.Stroke("<circle cx=\"9\" cy=\"12\" r=\"1\" /><circle cx=\"9\" cy=\"5\" r=\"1\" /><circle cx=\"9\" cy=\"19\" r=\"1\" /><circle cx=\"15\" cy=\"12\" r=\"1\" /><circle cx=\"15\" cy=\"5\" r=\"1\" /><circle cx=\"15\" cy=\"19\" r=\"1\" />");
    /// <summary>Lucide <c>group</c>.</summary>
    public static global::Lumeo.IconSource Group => global::Lumeo.IconSource.Stroke("<path d=\"M3 7V5c0-1.1.9-2 2-2h2\" /><path d=\"M17 3h2c1.1 0 2 .9 2 2v2\" /><path d=\"M21 17v2c0 1.1-.9 2-2 2h-2\" /><path d=\"M7 21H5c-1.1 0-2-.9-2-2v-2\" /><rect width=\"7\" height=\"5\" x=\"7\" y=\"7\" rx=\"1\" /><rect width=\"7\" height=\"5\" x=\"10\" y=\"12\" rx=\"1\" />");
    /// <summary>Lucide <c>hammer</c>.</summary>
    public static global::Lumeo.IconSource Hammer => global::Lumeo.IconSource.Stroke("<path d=\"m15 12-9.373 9.373a1 1 0 0 1-3.001-3L12 9\" /><path d=\"m18 15 4-4\" /><path d=\"m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172v-.344a2 2 0 0 0-.586-1.414l-1.657-1.657A6 6 0 0 0 12.516 3H9l1.243 1.243A6 6 0 0 1 12 8.485V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5\" />");
    /// <summary>Lucide <c>hard-drive</c>.</summary>
    public static global::Lumeo.IconSource HardDrive => global::Lumeo.IconSource.Stroke("<path d=\"M10 16h.01\" /><path d=\"M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z\" /><path d=\"M21.946 12.013H2.054\" /><path d=\"M6 16h.01\" />");
    /// <summary>Lucide <c>heading-1</c>.</summary>
    public static global::Lumeo.IconSource Heading1 => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h8\" /><path d=\"M4 18V6\" /><path d=\"M12 18V6\" /><path d=\"m17 12 3-2v8\" />");
    /// <summary>Lucide <c>heading-2</c>.</summary>
    public static global::Lumeo.IconSource Heading2 => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h8\" /><path d=\"M4 18V6\" /><path d=\"M12 18V6\" /><path d=\"M21 18h-4c0-4 4-3 4-6 0-1.5-2-2.5-4-1\" />");
    /// <summary>Lucide <c>heading-3</c>.</summary>
    public static global::Lumeo.IconSource Heading3 => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h8\" /><path d=\"M4 18V6\" /><path d=\"M12 18V6\" /><path d=\"M17.5 10.5c1.7-1 3.5 0 3.5 1.5a2 2 0 0 1-2 2\" /><path d=\"M17 17.5c2 1.5 4 .3 4-1.5a2 2 0 0 0-2-2\" />");
    /// <summary>Lucide <c>heart</c>.</summary>
    public static global::Lumeo.IconSource Heart => global::Lumeo.IconSource.Stroke("<path d=\"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5\" />");
    /// <summary>Lucide <c>house</c>.</summary>
    public static global::Lumeo.IconSource House => global::Lumeo.IconSource.Stroke("<path d=\"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8\" /><path d=\"M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\" />");
    /// <summary>Lucide <c>image</c>.</summary>
    public static global::Lumeo.IconSource Image => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" /><circle cx=\"9\" cy=\"9\" r=\"2\" /><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" />");
    /// <summary>Lucide <c>image-off</c>.</summary>
    public static global::Lumeo.IconSource ImageOff => global::Lumeo.IconSource.Stroke("<line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" /><path d=\"M10.41 10.41a2 2 0 1 1-2.83-2.83\" /><line x1=\"13.5\" x2=\"6\" y1=\"13.5\" y2=\"21\" /><line x1=\"18\" x2=\"21\" y1=\"12\" y2=\"15\" /><path d=\"M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59\" /><path d=\"M21 15V5a2 2 0 0 0-2-2H9\" />");
    /// <summary>Lucide <c>inbox</c>.</summary>
    public static global::Lumeo.IconSource Inbox => global::Lumeo.IconSource.Stroke("<polyline points=\"22 12 16 12 14 15 10 15 8 12 2 12\" /><path d=\"M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z\" />");
    /// <summary>Lucide <c>info</c>.</summary>
    public static global::Lumeo.IconSource Info => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M12 16v-4\" /><path d=\"M12 8h.01\" />");
    /// <summary>Lucide <c>italic</c>.</summary>
    public static global::Lumeo.IconSource Italic => global::Lumeo.IconSource.Stroke("<line x1=\"19\" x2=\"10\" y1=\"4\" y2=\"4\" /><line x1=\"14\" x2=\"5\" y1=\"20\" y2=\"20\" /><line x1=\"15\" x2=\"9\" y1=\"4\" y2=\"20\" />");
    /// <summary>Lucide <c>key</c>.</summary>
    public static global::Lumeo.IconSource Key => global::Lumeo.IconSource.Stroke("<path d=\"m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4\" /><path d=\"m21 2-9.6 9.6\" /><circle cx=\"7.5\" cy=\"15.5\" r=\"5.5\" />");
    /// <summary>Lucide <c>keyboard</c>.</summary>
    public static global::Lumeo.IconSource Keyboard => global::Lumeo.IconSource.Stroke("<path d=\"M10 8h.01\" /><path d=\"M12 12h.01\" /><path d=\"M14 8h.01\" /><path d=\"M16 12h.01\" /><path d=\"M18 8h.01\" /><path d=\"M6 8h.01\" /><path d=\"M7 16h10\" /><path d=\"M8 12h.01\" /><rect width=\"20\" height=\"16\" x=\"2\" y=\"4\" rx=\"2\" />");
    /// <summary>Lucide <c>languages</c>.</summary>
    public static global::Lumeo.IconSource Languages => global::Lumeo.IconSource.Stroke("<path d=\"m5 8 6 6\" /><path d=\"m4 14 6-6 2-3\" /><path d=\"M2 5h12\" /><path d=\"M7 2h1\" /><path d=\"m22 22-5-10-5 10\" /><path d=\"M14 18h6\" />");
    /// <summary>Lucide <c>layers</c>.</summary>
    public static global::Lumeo.IconSource Layers => global::Lumeo.IconSource.Stroke("<path d=\"M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z\" /><path d=\"M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12\" /><path d=\"M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17\" />");
    /// <summary>Lucide <c>layout-dashboard</c>.</summary>
    public static global::Lumeo.IconSource LayoutDashboard => global::Lumeo.IconSource.Stroke("<rect width=\"7\" height=\"9\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"5\" x=\"14\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"9\" x=\"14\" y=\"12\" rx=\"1\" /><rect width=\"7\" height=\"5\" x=\"3\" y=\"16\" rx=\"1\" />");
    /// <summary>Lucide <c>layout-grid</c>.</summary>
    public static global::Lumeo.IconSource LayoutGrid => global::Lumeo.IconSource.Stroke("<rect width=\"7\" height=\"7\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"14\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"14\" y=\"14\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"3\" y=\"14\" rx=\"1\" />");
    /// <summary>Lucide <c>layout-list</c>.</summary>
    public static global::Lumeo.IconSource LayoutList => global::Lumeo.IconSource.Stroke("<rect width=\"7\" height=\"7\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"3\" y=\"14\" rx=\"1\" /><path d=\"M14 4h7\" /><path d=\"M14 9h7\" /><path d=\"M14 15h7\" /><path d=\"M14 20h7\" />");
    /// <summary>Lucide <c>layout-template</c>.</summary>
    public static global::Lumeo.IconSource LayoutTemplate => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"7\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"9\" height=\"7\" x=\"3\" y=\"14\" rx=\"1\" /><rect width=\"5\" height=\"7\" x=\"16\" y=\"14\" rx=\"1\" />");
    /// <summary>Lucide <c>lightbulb</c>.</summary>
    public static global::Lumeo.IconSource Lightbulb => global::Lumeo.IconSource.Stroke("<path d=\"M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5\" /><path d=\"M9 18h6\" /><path d=\"M10 22h4\" />");
    /// <summary>Lucide <c>link</c>.</summary>
    public static global::Lumeo.IconSource Link => global::Lumeo.IconSource.Stroke("<path d=\"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71\" /><path d=\"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71\" />");
    /// <summary>Lucide <c>link-2-off</c>.</summary>
    public static global::Lumeo.IconSource Link2Off => global::Lumeo.IconSource.Stroke("<path d=\"M9 17H7A5 5 0 0 1 7 7\" /><path d=\"M15 7h2a5 5 0 0 1 4 8\" /><line x1=\"8\" x2=\"12\" y1=\"12\" y2=\"12\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" />");
    /// <summary>Lucide <c>list</c>.</summary>
    public static global::Lumeo.IconSource List => global::Lumeo.IconSource.Stroke("<path d=\"M3 5h.01\" /><path d=\"M3 12h.01\" /><path d=\"M3 19h.01\" /><path d=\"M8 5h13\" /><path d=\"M8 12h13\" /><path d=\"M8 19h13\" />");
    /// <summary>Lucide <c>list-filter</c>.</summary>
    public static global::Lumeo.IconSource ListFilter => global::Lumeo.IconSource.Stroke("<path d=\"M2 5h20\" /><path d=\"M6 12h12\" /><path d=\"M9 19h6\" />");
    /// <summary>Lucide <c>list-music</c>.</summary>
    public static global::Lumeo.IconSource ListMusic => global::Lumeo.IconSource.Stroke("<path d=\"M16 5H3\" /><path d=\"M11 12H3\" /><path d=\"M11 19H3\" /><path d=\"M21 16V5\" /><circle cx=\"18\" cy=\"16\" r=\"3\" />");
    /// <summary>Lucide <c>list-ordered</c>.</summary>
    public static global::Lumeo.IconSource ListOrdered => global::Lumeo.IconSource.Stroke("<path d=\"M11 5h10\" /><path d=\"M11 12h10\" /><path d=\"M11 19h10\" /><path d=\"M4 4h1v5\" /><path d=\"M4 9h2\" /><path d=\"M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02\" />");
    /// <summary>Lucide <c>loader</c>.</summary>
    public static global::Lumeo.IconSource Loader => global::Lumeo.IconSource.Stroke("<path d=\"M12 2v4\" /><path d=\"m16.2 7.8 2.9-2.9\" /><path d=\"M18 12h4\" /><path d=\"m16.2 16.2 2.9 2.9\" /><path d=\"M12 18v4\" /><path d=\"m4.9 19.1 2.9-2.9\" /><path d=\"M2 12h4\" /><path d=\"m4.9 4.9 2.9 2.9\" />");
    /// <summary>Lucide <c>loader-circle</c>.</summary>
    public static global::Lumeo.IconSource LoaderCircle => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 1-6.219-8.56\" />");
    /// <summary>Lucide <c>lock</c>.</summary>
    public static global::Lumeo.IconSource Lock => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\" /><path d=\"M7 11V7a5 5 0 0 1 10 0v4\" />");
    /// <summary>Lucide <c>log-in</c>.</summary>
    public static global::Lumeo.IconSource LogIn => global::Lumeo.IconSource.Stroke("<path d=\"m10 17 5-5-5-5\" /><path d=\"M15 12H3\" /><path d=\"M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4\" />");
    /// <summary>Lucide <c>log-out</c>.</summary>
    public static global::Lumeo.IconSource LogOut => global::Lumeo.IconSource.Stroke("<path d=\"m16 17 5-5-5-5\" /><path d=\"M21 12H9\" /><path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\" />");
    /// <summary>Lucide <c>mail</c>.</summary>
    public static global::Lumeo.IconSource Mail => global::Lumeo.IconSource.Stroke("<path d=\"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7\" /><rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\" />");
    /// <summary>Lucide <c>map-pin</c>.</summary>
    public static global::Lumeo.IconSource MapPin => global::Lumeo.IconSource.Stroke("<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" /><circle cx=\"12\" cy=\"10\" r=\"3\" />");
    /// <summary>Lucide <c>maximize-2</c>.</summary>
    public static global::Lumeo.IconSource Maximize2 => global::Lumeo.IconSource.Stroke("<path d=\"M15 3h6v6\" /><path d=\"m21 3-7 7\" /><path d=\"m3 21 7-7\" /><path d=\"M9 21H3v-6\" />");
    /// <summary>Lucide <c>menu</c>.</summary>
    public static global::Lumeo.IconSource Menu => global::Lumeo.IconSource.Stroke("<path d=\"M4 5h16\" /><path d=\"M4 12h16\" /><path d=\"M4 19h16\" />");
    /// <summary>Lucide <c>message-circle</c>.</summary>
    public static global::Lumeo.IconSource MessageCircle => global::Lumeo.IconSource.Stroke("<path d=\"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719\" />");
    /// <summary>Lucide <c>message-square</c>.</summary>
    public static global::Lumeo.IconSource MessageSquare => global::Lumeo.IconSource.Stroke("<path d=\"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z\" />");
    /// <summary>Lucide <c>mic</c>.</summary>
    public static global::Lumeo.IconSource Mic => global::Lumeo.IconSource.Stroke("<path d=\"M12 19v3\" /><path d=\"M19 10v2a7 7 0 0 1-14 0v-2\" /><rect x=\"9\" y=\"2\" width=\"6\" height=\"13\" rx=\"3\" />");
    /// <summary>Lucide <c>minimize-2</c>.</summary>
    public static global::Lumeo.IconSource Minimize2 => global::Lumeo.IconSource.Stroke("<path d=\"m14 10 7-7\" /><path d=\"M20 10h-6V4\" /><path d=\"m3 21 7-7\" /><path d=\"M4 14h6v6\" />");
    /// <summary>Lucide <c>minus</c>.</summary>
    public static global::Lumeo.IconSource Minus => global::Lumeo.IconSource.Stroke("<path d=\"M5 12h14\" />");
    /// <summary>Lucide <c>monitor</c>.</summary>
    public static global::Lumeo.IconSource Monitor => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" /><line x1=\"8\" x2=\"16\" y1=\"21\" y2=\"21\" /><line x1=\"12\" x2=\"12\" y1=\"17\" y2=\"21\" />");
    /// <summary>Lucide <c>moon</c>.</summary>
    public static global::Lumeo.IconSource Moon => global::Lumeo.IconSource.Stroke("<path d=\"M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401\" />");
    /// <summary>Lucide <c>mouse-pointer-click</c>.</summary>
    public static global::Lumeo.IconSource MousePointerClick => global::Lumeo.IconSource.Stroke("<path d=\"M14 4.1 12 6\" /><path d=\"m5.1 8-2.9-.8\" /><path d=\"m6 12-1.9 2\" /><path d=\"M7.2 2.2 8 5.1\" /><path d=\"M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z\" />");
    /// <summary>Lucide <c>music</c>.</summary>
    public static global::Lumeo.IconSource Music => global::Lumeo.IconSource.Stroke("<path d=\"M9 18V5l12-2v13\" /><circle cx=\"6\" cy=\"18\" r=\"3\" /><circle cx=\"18\" cy=\"16\" r=\"3\" />");
    /// <summary>Lucide <c>navigation</c>.</summary>
    public static global::Lumeo.IconSource Navigation => global::Lumeo.IconSource.Stroke("<polygon points=\"3 11 22 2 13 21 11 13 3 11\" />");
    /// <summary>Lucide <c>package</c>.</summary>
    public static global::Lumeo.IconSource Package => global::Lumeo.IconSource.Stroke("<path d=\"M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z\" /><path d=\"M12 22V12\" /><polyline points=\"3.29 7 12 12 20.71 7\" /><path d=\"m7.5 4.27 9 5.15\" />");
    /// <summary>Lucide <c>paintbrush</c>.</summary>
    public static global::Lumeo.IconSource Paintbrush => global::Lumeo.IconSource.Stroke("<path d=\"m14.622 17.897-10.68-2.913\" /><path d=\"M18.376 2.622a1 1 0 1 1 3.002 3.002L17.36 9.643a.5.5 0 0 0 0 .707l.944.944a2.41 2.41 0 0 1 0 3.408l-.944.944a.5.5 0 0 1-.707 0L8.354 7.348a.5.5 0 0 1 0-.707l.944-.944a2.41 2.41 0 0 1 3.408 0l.944.944a.5.5 0 0 0 .707 0z\" /><path d=\"M9 8c-1.804 2.71-3.97 3.46-6.583 3.948a.507.507 0 0 0-.302.819l7.32 8.883a1 1 0 0 0 1.185.204C12.735 20.405 16 16.792 16 15\" />");
    /// <summary>Lucide <c>palette</c>.</summary>
    public static global::Lumeo.IconSource Palette => global::Lumeo.IconSource.Stroke("<path d=\"M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z\" /><circle cx=\"13.5\" cy=\"6.5\" r=\".5\" fill=\"currentColor\" /><circle cx=\"17.5\" cy=\"10.5\" r=\".5\" fill=\"currentColor\" /><circle cx=\"6.5\" cy=\"12.5\" r=\".5\" fill=\"currentColor\" /><circle cx=\"8.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>panel-left</c>.</summary>
    public static global::Lumeo.IconSource PanelLeft => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M9 3v18\" />");
    /// <summary>Lucide <c>panel-left-close</c>.</summary>
    public static global::Lumeo.IconSource PanelLeftClose => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M9 3v18\" /><path d=\"m16 15-3-3 3-3\" />");
    /// <summary>Lucide <c>panel-left-open</c>.</summary>
    public static global::Lumeo.IconSource PanelLeftOpen => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M9 3v18\" /><path d=\"m14 9 3 3-3 3\" />");
    /// <summary>Lucide <c>paperclip</c>.</summary>
    public static global::Lumeo.IconSource Paperclip => global::Lumeo.IconSource.Stroke("<path d=\"m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551\" />");
    /// <summary>Lucide <c>pause</c>.</summary>
    public static global::Lumeo.IconSource Pause => global::Lumeo.IconSource.Stroke("<rect x=\"14\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" /><rect x=\"5\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" />");
    /// <summary>Lucide <c>pen-line</c>.</summary>
    public static global::Lumeo.IconSource PenLine => global::Lumeo.IconSource.Stroke("<path d=\"M13 21h8\" /><path d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\" />");
    /// <summary>Lucide <c>pencil</c>.</summary>
    public static global::Lumeo.IconSource Pencil => global::Lumeo.IconSource.Stroke("<path d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\" /><path d=\"m15 5 4 4\" />");
    /// <summary>Lucide <c>phone</c>.</summary>
    public static global::Lumeo.IconSource Phone => global::Lumeo.IconSource.Stroke("<path d=\"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384\" />");
    /// <summary>Lucide <c>pilcrow</c>.</summary>
    public static global::Lumeo.IconSource Pilcrow => global::Lumeo.IconSource.Stroke("<path d=\"M13 4v16\" /><path d=\"M17 4v16\" /><path d=\"M19 4H9.5a4.5 4.5 0 0 0 0 9H13\" />");
    /// <summary>Lucide <c>pin</c>.</summary>
    public static global::Lumeo.IconSource Pin => global::Lumeo.IconSource.Stroke("<path d=\"M12 17v5\" /><path d=\"M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z\" />");
    /// <summary>Lucide <c>play</c>.</summary>
    public static global::Lumeo.IconSource Play => global::Lumeo.IconSource.Stroke("<path d=\"M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z\" />");
    /// <summary>Lucide <c>plus</c>.</summary>
    public static global::Lumeo.IconSource Plus => global::Lumeo.IconSource.Stroke("<path d=\"M5 12h14\" /><path d=\"M12 5v14\" />");
    /// <summary>Lucide <c>puzzle</c>.</summary>
    public static global::Lumeo.IconSource Puzzle => global::Lumeo.IconSource.Stroke("<path d=\"M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z\" />");
    /// <summary>Lucide <c>quote</c>.</summary>
    public static global::Lumeo.IconSource Quote => global::Lumeo.IconSource.Stroke("<path d=\"M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z\" /><path d=\"M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z\" />");
    /// <summary>Lucide <c>radio</c>.</summary>
    public static global::Lumeo.IconSource Radio => global::Lumeo.IconSource.Stroke("<path d=\"M16.247 7.761a6 6 0 0 1 0 8.478\" /><path d=\"M19.075 4.933a10 10 0 0 1 0 14.134\" /><path d=\"M4.925 19.067a10 10 0 0 1 0-14.134\" /><path d=\"M7.753 16.239a6 6 0 0 1 0-8.478\" /><circle cx=\"12\" cy=\"12\" r=\"2\" />");
    /// <summary>Lucide <c>redo</c>.</summary>
    public static global::Lumeo.IconSource Redo => global::Lumeo.IconSource.Stroke("<path d=\"M21 7v6h-6\" /><path d=\"M3 17a9 9 0 0 1 9-9 9 9 0 0 1 6 2.3l3 2.7\" />");
    /// <summary>Lucide <c>refresh-cw</c>.</summary>
    public static global::Lumeo.IconSource RefreshCw => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\" /><path d=\"M21 3v5h-5\" /><path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\" /><path d=\"M8 16H3v5\" />");
    /// <summary>Lucide <c>remove-formatting</c>.</summary>
    public static global::Lumeo.IconSource RemoveFormatting => global::Lumeo.IconSource.Stroke("<path d=\"M4 7V4h16v3\" /><path d=\"M5 20h6\" /><path d=\"M13 4 8 20\" /><path d=\"m15 15 5 5\" /><path d=\"m20 15-5 5\" />");
    /// <summary>Lucide <c>repeat</c>.</summary>
    public static global::Lumeo.IconSource Repeat => global::Lumeo.IconSource.Stroke("<path d=\"m17 2 4 4-4 4\" /><path d=\"M3 11v-1a4 4 0 0 1 4-4h14\" /><path d=\"m7 22-4-4 4-4\" /><path d=\"M21 13v1a4 4 0 0 1-4 4H3\" />");
    /// <summary>Lucide <c>rocket</c>.</summary>
    public static global::Lumeo.IconSource Rocket => global::Lumeo.IconSource.Stroke("<path d=\"M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5\" /><path d=\"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09\" /><path d=\"M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z\" /><path d=\"M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05\" />");
    /// <summary>Lucide <c>rotate-ccw</c>.</summary>
    public static global::Lumeo.IconSource RotateCcw => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\" /><path d=\"M3 3v5h5\" />");
    /// <summary>Lucide <c>search</c>.</summary>
    public static global::Lumeo.IconSource Search => global::Lumeo.IconSource.Stroke("<path d=\"m21 21-4.34-4.34\" /><circle cx=\"11\" cy=\"11\" r=\"8\" />");
    /// <summary>Lucide <c>search-x</c>.</summary>
    public static global::Lumeo.IconSource SearchX => global::Lumeo.IconSource.Stroke("<path d=\"m13.5 8.5-5 5\" /><path d=\"m8.5 8.5 5 5\" /><circle cx=\"11\" cy=\"11\" r=\"8\" /><path d=\"m21 21-4.3-4.3\" />");
    /// <summary>Lucide <c>send</c>.</summary>
    public static global::Lumeo.IconSource Send => global::Lumeo.IconSource.Stroke("<path d=\"M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z\" /><path d=\"m21.854 2.147-10.94 10.939\" />");
    /// <summary>Lucide <c>server</c>.</summary>
    public static global::Lumeo.IconSource Server => global::Lumeo.IconSource.Stroke("<rect width=\"20\" height=\"8\" x=\"2\" y=\"2\" rx=\"2\" ry=\"2\" /><rect width=\"20\" height=\"8\" x=\"2\" y=\"14\" rx=\"2\" ry=\"2\" /><line x1=\"6\" x2=\"6.01\" y1=\"6\" y2=\"6\" /><line x1=\"6\" x2=\"6.01\" y1=\"18\" y2=\"18\" />");
    /// <summary>Lucide <c>server-cog</c>.</summary>
    public static global::Lumeo.IconSource ServerCog => global::Lumeo.IconSource.Stroke("<path d=\"m10.852 14.772-.383.923\" /><path d=\"M13.148 14.772a3 3 0 1 0-2.296-5.544l-.383-.923\" /><path d=\"m13.148 9.228.383-.923\" /><path d=\"m13.53 15.696-.382-.924a3 3 0 1 1-2.296-5.544\" /><path d=\"m14.772 10.852.923-.383\" /><path d=\"m14.772 13.148.923.383\" /><path d=\"M4.5 10H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-.5\" /><path d=\"M4.5 14H4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2h-.5\" /><path d=\"M6 18h.01\" /><path d=\"M6 6h.01\" /><path d=\"m9.228 10.852-.923-.383\" /><path d=\"m9.228 13.148-.923.383\" />");
    /// <summary>Lucide <c>settings</c>.</summary>
    public static global::Lumeo.IconSource Settings => global::Lumeo.IconSource.Stroke("<path d=\"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915\" /><circle cx=\"12\" cy=\"12\" r=\"3\" />");
    /// <summary>Lucide <c>settings-2</c>.</summary>
    public static global::Lumeo.IconSource Settings2 => global::Lumeo.IconSource.Stroke("<path d=\"M14 17H5\" /><path d=\"M19 7h-9\" /><circle cx=\"17\" cy=\"17\" r=\"3\" /><circle cx=\"7\" cy=\"7\" r=\"3\" />");
    /// <summary>Lucide <c>share-2</c>.</summary>
    public static global::Lumeo.IconSource Share2 => global::Lumeo.IconSource.Stroke("<circle cx=\"18\" cy=\"5\" r=\"3\" /><circle cx=\"6\" cy=\"12\" r=\"3\" /><circle cx=\"18\" cy=\"19\" r=\"3\" /><line x1=\"8.59\" x2=\"15.42\" y1=\"13.51\" y2=\"17.49\" /><line x1=\"15.41\" x2=\"8.59\" y1=\"6.51\" y2=\"10.49\" />");
    /// <summary>Lucide <c>sheet</c>.</summary>
    public static global::Lumeo.IconSource Sheet => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" /><line x1=\"3\" x2=\"21\" y1=\"9\" y2=\"9\" /><line x1=\"3\" x2=\"21\" y1=\"15\" y2=\"15\" /><line x1=\"9\" x2=\"9\" y1=\"9\" y2=\"21\" /><line x1=\"15\" x2=\"15\" y1=\"9\" y2=\"21\" />");
    /// <summary>Lucide <c>shield</c>.</summary>
    public static global::Lumeo.IconSource Shield => global::Lumeo.IconSource.Stroke("<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" />");
    /// <summary>Lucide <c>shield-alert</c>.</summary>
    public static global::Lumeo.IconSource ShieldAlert => global::Lumeo.IconSource.Stroke("<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /><path d=\"M12 8v4\" /><path d=\"M12 16h.01\" />");
    /// <summary>Lucide <c>shield-check</c>.</summary>
    public static global::Lumeo.IconSource ShieldCheck => global::Lumeo.IconSource.Stroke("<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /><path d=\"m9 12 2 2 4-4\" />");
    /// <summary>Lucide <c>shopping-bag</c>.</summary>
    public static global::Lumeo.IconSource ShoppingBag => global::Lumeo.IconSource.Stroke("<path d=\"M16 10a4 4 0 0 1-8 0\" /><path d=\"M3.103 6.034h17.794\" /><path d=\"M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z\" />");
    /// <summary>Lucide <c>shopping-cart</c>.</summary>
    public static global::Lumeo.IconSource ShoppingCart => global::Lumeo.IconSource.Stroke("<circle cx=\"8\" cy=\"21\" r=\"1\" /><circle cx=\"19\" cy=\"21\" r=\"1\" /><path d=\"M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12\" />");
    /// <summary>Lucide <c>shuffle</c>.</summary>
    public static global::Lumeo.IconSource Shuffle => global::Lumeo.IconSource.Stroke("<path d=\"m18 14 4 4-4 4\" /><path d=\"m18 2 4 4-4 4\" /><path d=\"M2 18h1.973a4 4 0 0 0 3.3-1.7l5.454-8.6a4 4 0 0 1 3.3-1.7H22\" /><path d=\"M2 6h1.972a4 4 0 0 1 3.6 2.2\" /><path d=\"M22 18h-6.041a4 4 0 0 1-3.3-1.8l-.359-.45\" />");
    /// <summary>Lucide <c>skip-back</c>.</summary>
    public static global::Lumeo.IconSource SkipBack => global::Lumeo.IconSource.Stroke("<path d=\"M17.971 4.285A2 2 0 0 1 21 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432z\" /><path d=\"M3 20V4\" />");
    /// <summary>Lucide <c>skip-forward</c>.</summary>
    public static global::Lumeo.IconSource SkipForward => global::Lumeo.IconSource.Stroke("<path d=\"M21 4v16\" /><path d=\"M6.029 4.285A2 2 0 0 0 3 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432z\" />");
    /// <summary>Lucide <c>slash</c>.</summary>
    public static global::Lumeo.IconSource Slash => global::Lumeo.IconSource.Stroke("<path d=\"M22 2 2 22\" />");
    /// <summary>Lucide <c>sliders-horizontal</c>.</summary>
    public static global::Lumeo.IconSource SlidersHorizontal => global::Lumeo.IconSource.Stroke("<path d=\"M10 5H3\" /><path d=\"M12 19H3\" /><path d=\"M14 3v4\" /><path d=\"M16 17v4\" /><path d=\"M21 12h-9\" /><path d=\"M21 19h-5\" /><path d=\"M21 5h-7\" /><path d=\"M8 10v4\" /><path d=\"M8 12H3\" />");
    /// <summary>Lucide <c>smartphone</c>.</summary>
    public static global::Lumeo.IconSource Smartphone => global::Lumeo.IconSource.Stroke("<rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" /><path d=\"M12 18h.01\" />");
    /// <summary>Lucide <c>smile</c>.</summary>
    public static global::Lumeo.IconSource Smile => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M8 14s1.5 2 4 2 4-2 4-2\" /><line x1=\"9\" x2=\"9.01\" y1=\"9\" y2=\"9\" /><line x1=\"15\" x2=\"15.01\" y1=\"9\" y2=\"9\" />");
    /// <summary>Lucide <c>sparkles</c>.</summary>
    public static global::Lumeo.IconSource Sparkles => global::Lumeo.IconSource.Stroke("<path d=\"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z\" /><path d=\"M20 2v4\" /><path d=\"M22 4h-4\" /><circle cx=\"4\" cy=\"20\" r=\"2\" />");
    /// <summary>Lucide <c>square</c>.</summary>
    public static global::Lumeo.IconSource Square => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />");
    /// <summary>Lucide <c>square-check</c>.</summary>
    public static global::Lumeo.IconSource SquareCheck => global::Lumeo.IconSource.Stroke("<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"m9 12 2 2 4-4\" />");
    /// <summary>Lucide <c>square-code</c>.</summary>
    public static global::Lumeo.IconSource SquareCode => global::Lumeo.IconSource.Stroke("<path d=\"m10 9-3 3 3 3\" /><path d=\"m14 15 3-3-3-3\" /><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" />");
    /// <summary>Lucide <c>square-mouse-pointer</c>.</summary>
    public static global::Lumeo.IconSource SquareMousePointer => global::Lumeo.IconSource.Stroke("<path d=\"M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z\" /><path d=\"M21 11V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6\" />");
    /// <summary>Lucide <c>square-pen</c>.</summary>
    public static global::Lumeo.IconSource SquarePen => global::Lumeo.IconSource.Stroke("<path d=\"M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7\" /><path d=\"M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z\" />");
    /// <summary>Lucide <c>square-terminal</c>.</summary>
    public static global::Lumeo.IconSource SquareTerminal => global::Lumeo.IconSource.Stroke("<path d=\"m7 11 2-2-2-2\" /><path d=\"M11 13h4\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" />");
    /// <summary>Lucide <c>star</c>.</summary>
    public static global::Lumeo.IconSource Star => global::Lumeo.IconSource.Stroke("<path d=\"M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z\" />");
    /// <summary>Lucide <c>strikethrough</c>.</summary>
    public static global::Lumeo.IconSource Strikethrough => global::Lumeo.IconSource.Stroke("<path d=\"M16 4H9a3 3 0 0 0-2.83 4\" /><path d=\"M14 12a4 4 0 0 1 0 8H6\" /><line x1=\"4\" x2=\"20\" y1=\"12\" y2=\"12\" />");
    /// <summary>Lucide <c>sun</c>.</summary>
    public static global::Lumeo.IconSource Sun => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"4\" /><path d=\"M12 2v2\" /><path d=\"M12 20v2\" /><path d=\"m4.93 4.93 1.41 1.41\" /><path d=\"m17.66 17.66 1.41 1.41\" /><path d=\"M2 12h2\" /><path d=\"M20 12h2\" /><path d=\"m6.34 17.66-1.41 1.41\" /><path d=\"m19.07 4.93-1.41 1.41\" />");
    /// <summary>Lucide <c>table</c>.</summary>
    public static global::Lumeo.IconSource Table => global::Lumeo.IconSource.Stroke("<path d=\"M12 3v18\" /><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M3 9h18\" /><path d=\"M3 15h18\" />");
    /// <summary>Lucide <c>tag</c>.</summary>
    public static global::Lumeo.IconSource Tag => global::Lumeo.IconSource.Stroke("<path d=\"M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />");
    /// <summary>Lucide <c>target</c>.</summary>
    public static global::Lumeo.IconSource Target => global::Lumeo.IconSource.Stroke("<circle cx=\"12\" cy=\"12\" r=\"10\" /><circle cx=\"12\" cy=\"12\" r=\"6\" /><circle cx=\"12\" cy=\"12\" r=\"2\" />");
    /// <summary>Lucide <c>terminal</c>.</summary>
    public static global::Lumeo.IconSource Terminal => global::Lumeo.IconSource.Stroke("<path d=\"M12 19h8\" /><path d=\"m4 17 6-6-6-6\" />");
    /// <summary>Lucide <c>test-tube</c>.</summary>
    public static global::Lumeo.IconSource TestTube => global::Lumeo.IconSource.Stroke("<path d=\"M14.5 2v17.5c0 1.4-1.1 2.5-2.5 2.5c-1.4 0-2.5-1.1-2.5-2.5V2\" /><path d=\"M8.5 2h7\" /><path d=\"M14.5 16h-5\" />");
    /// <summary>Lucide <c>trash-2</c>.</summary>
    public static global::Lumeo.IconSource Trash2 => global::Lumeo.IconSource.Stroke("<path d=\"M10 11v6\" /><path d=\"M14 11v6\" /><path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\" /><path d=\"M3 6h18\" /><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\" />");
    /// <summary>Lucide <c>trending-down</c>.</summary>
    public static global::Lumeo.IconSource TrendingDown => global::Lumeo.IconSource.Stroke("<path d=\"M16 17h6v-6\" /><path d=\"m22 17-8.5-8.5-5 5L2 7\" />");
    /// <summary>Lucide <c>trending-up</c>.</summary>
    public static global::Lumeo.IconSource TrendingUp => global::Lumeo.IconSource.Stroke("<path d=\"M16 7h6v6\" /><path d=\"m22 7-8.5 8.5-5-5L2 17\" />");
    /// <summary>Lucide <c>triangle-alert</c>.</summary>
    public static global::Lumeo.IconSource TriangleAlert => global::Lumeo.IconSource.Stroke("<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" /><path d=\"M12 9v4\" /><path d=\"M12 17h.01\" />");
    /// <summary>Lucide <c>truck</c>.</summary>
    public static global::Lumeo.IconSource Truck => global::Lumeo.IconSource.Stroke("<path d=\"M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2\" /><path d=\"M15 18H9\" /><path d=\"M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14\" /><circle cx=\"17\" cy=\"18\" r=\"2\" /><circle cx=\"7\" cy=\"18\" r=\"2\" />");
    /// <summary>Lucide <c>underline</c>.</summary>
    public static global::Lumeo.IconSource Underline => global::Lumeo.IconSource.Stroke("<path d=\"M6 4v6a6 6 0 0 0 12 0V4\" /><line x1=\"4\" x2=\"20\" y1=\"20\" y2=\"20\" />");
    /// <summary>Lucide <c>undo</c>.</summary>
    public static global::Lumeo.IconSource Undo => global::Lumeo.IconSource.Stroke("<path d=\"M3 7v6h6\" /><path d=\"M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13\" />");
    /// <summary>Lucide <c>upload</c>.</summary>
    public static global::Lumeo.IconSource Upload => global::Lumeo.IconSource.Stroke("<path d=\"M12 3v12\" /><path d=\"m17 8-5-5-5 5\" /><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\" />");
    /// <summary>Lucide <c>user</c>.</summary>
    public static global::Lumeo.IconSource User => global::Lumeo.IconSource.Stroke("<path d=\"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2\" /><circle cx=\"12\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>user-minus</c>.</summary>
    public static global::Lumeo.IconSource UserMinus => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" /><line x1=\"22\" x2=\"16\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>user-plus</c>.</summary>
    public static global::Lumeo.IconSource UserPlus => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><circle cx=\"9\" cy=\"7\" r=\"4\" /><line x1=\"19\" x2=\"19\" y1=\"8\" y2=\"14\" /><line x1=\"22\" x2=\"16\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>users</c>.</summary>
    public static global::Lumeo.IconSource Users => global::Lumeo.IconSource.Stroke("<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /><path d=\"M16 3.128a4 4 0 0 1 0 7.744\" /><path d=\"M22 21v-2a4 4 0 0 0-3-3.87\" /><circle cx=\"9\" cy=\"7\" r=\"4\" />");
    /// <summary>Lucide <c>video</c>.</summary>
    public static global::Lumeo.IconSource Video => global::Lumeo.IconSource.Stroke("<path d=\"m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5\" /><rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\" />");
    /// <summary>Lucide <c>volume</c>.</summary>
    public static global::Lumeo.IconSource Volume => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" />");
    /// <summary>Lucide <c>volume-1</c>.</summary>
    public static global::Lumeo.IconSource Volume1 => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><path d=\"M16 9a5 5 0 0 1 0 6\" />");
    /// <summary>Lucide <c>volume-2</c>.</summary>
    public static global::Lumeo.IconSource Volume2 => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><path d=\"M16 9a5 5 0 0 1 0 6\" /><path d=\"M19.364 18.364a9 9 0 0 0 0-12.728\" />");
    /// <summary>Lucide <c>volume-x</c>.</summary>
    public static global::Lumeo.IconSource VolumeX => global::Lumeo.IconSource.Stroke("<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" /><line x1=\"22\" x2=\"16\" y1=\"9\" y2=\"15\" /><line x1=\"16\" x2=\"22\" y1=\"9\" y2=\"15\" />");
    /// <summary>Lucide <c>wallet</c>.</summary>
    public static global::Lumeo.IconSource Wallet => global::Lumeo.IconSource.Stroke("<path d=\"M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1\" /><path d=\"M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4\" />");
    /// <summary>Lucide <c>wand</c>.</summary>
    public static global::Lumeo.IconSource Wand => global::Lumeo.IconSource.Stroke("<path d=\"M15 4V2\" /><path d=\"M15 16v-2\" /><path d=\"M8 9h2\" /><path d=\"M20 9h2\" /><path d=\"M17.8 11.8 19 13\" /><path d=\"M15 9h.01\" /><path d=\"M17.8 6.2 19 5\" /><path d=\"m3 21 9-9\" /><path d=\"M12.2 6.2 11 5\" />");
    /// <summary>Lucide <c>wrench</c>.</summary>
    public static global::Lumeo.IconSource Wrench => global::Lumeo.IconSource.Stroke("<path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z\" />");
    /// <summary>Lucide <c>x</c>.</summary>
    public static global::Lumeo.IconSource X => global::Lumeo.IconSource.Stroke("<path d=\"M18 6 6 18\" /><path d=\"m6 6 12 12\" />");
    /// <summary>Lucide <c>zap</c>.</summary>
    public static global::Lumeo.IconSource Zap => global::Lumeo.IconSource.Stroke("<path d=\"M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z\" />");
    /// <summary>Lucide <c>zoom-in</c>.</summary>
    public static global::Lumeo.IconSource ZoomIn => global::Lumeo.IconSource.Stroke("<circle cx=\"11\" cy=\"11\" r=\"8\" /><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" /><line x1=\"11\" x2=\"11\" y1=\"8\" y2=\"14\" /><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" />");
    /// <summary>Lucide <c>zoom-out</c>.</summary>
    public static global::Lumeo.IconSource ZoomOut => global::Lumeo.IconSource.Stroke("<circle cx=\"11\" cy=\"11\" r=\"8\" /><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" /><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" />");
}
