using Microsoft.AspNetCore.Components;

namespace Lumeo;

public record DataGridContext<TItem>(
    IReadOnlyList<DataGridColumn<TItem>> Columns,
    IReadOnlyList<TItem> DisplayedItems,
    IReadOnlyList<TItem> SelectedItems,
    List<SortDescriptor> Sorts,
    List<FilterDescriptor> Filters,
    string? GlobalSearch,
    int CurrentPage,
    int PageSize,
    int TotalCount,
    DataGridSelectionMode SelectionMode,
    DataGridEditMode EditMode,
    bool IsLoading,
    bool RowReorderable,
    bool RowContextMenuEnabled,
    EventCallback<TItem> OnRowClick,
    EventCallback<TItem> OnRowDoubleClick,
    EventCallback<SortDescriptor> OnSort,
    EventCallback<FilterDescriptor> OnFilter,
    EventCallback<TItem> OnSelectionChanged,
    EventCallback<CellEditEventArgs<TItem>> OnCellEdit,
    Func<TItem, bool> IsRowSelected,
    Func<TItem, bool> IsRowExpanded,
    Func<TItem, bool> IsRowEditing,
    Action<TItem> ToggleSelection,
    Action SelectAll,
    Action ClearSelection,
    Action<TItem> ToggleRowExpand,
    Action<TItem> StartRowEdit,
    Action<TItem> CancelRowEdit,
    Func<TItem, Task> CommitRowEdit,
    Func<TItem, DataGridColumn<TItem>, object?> GetEditValue,
    Action<TItem, DataGridColumn<TItem>, object?> SetEditValue,
    Func<TItem, string>? RowClass,
    Func<TItem, string>? RowStyle
);
