// <auto-generated />
// Tabler Icons — MIT License.
// https://github.com/tabler/tabler-icons
// 
// MIT License
// 
// Copyright (c) 2020-2026 Paweł Kuna
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// Source: Tabler v3.44.0
// Generated by tools/Lumeo.IconGen — DO NOT EDIT BY HAND.
#nullable enable

namespace Lumeo.Icons;

public static partial class Tabler
{
    /// <summary>Tabler <c>wifi-1</c>.</summary>
    public static global::Lumeo.IconSource Wifi1 => global::Lumeo.IconSource.Stroke("<path d=\"M12 18l.01 0\" /><path d=\"M9.172 15.172a4 4 0 0 1 5.656 0\" />");
    /// <summary>Tabler <c>wifi-2</c>.</summary>
    public static global::Lumeo.IconSource Wifi2 => global::Lumeo.IconSource.Stroke("<path d=\"M12 18l.01 0\" /><path d=\"M9.172 15.172a4 4 0 0 1 5.656 0\" /><path d=\"M6.343 12.343a8 8 0 0 1 11.314 0\" />");
    /// <summary>Tabler <c>wifi-off</c>.</summary>
    public static global::Lumeo.IconSource WifiOff => global::Lumeo.IconSource.Stroke("<path d=\"M12 18l.01 0\" /><path d=\"M9.172 15.172a4 4 0 0 1 5.656 0\" /><path d=\"M6.343 12.343a7.963 7.963 0 0 1 3.864 -2.14m4.163 .155a7.965 7.965 0 0 1 3.287 2\" /><path d=\"M3.515 9.515a12 12 0 0 1 3.544 -2.455m3.101 -.92a12 12 0 0 1 10.325 3.374\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>wind</c>.</summary>
    public static global::Lumeo.IconSource Wind => global::Lumeo.IconSource.Stroke("<path d=\"M5 8h8.5a2.5 2.5 0 1 0 -2.34 -3.24\" /><path d=\"M3 12h15.5a2.5 2.5 0 1 1 -2.34 3.24\" /><path d=\"M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24\" />");
    /// <summary>Tabler <c>wind-electricity</c>.</summary>
    public static global::Lumeo.IconSource WindElectricity => global::Lumeo.IconSource.Stroke("<path d=\"M20 7l-3 5h4l-3 5\" /><path d=\"M3 16h4a2 2 0 1 1 0 4\" /><path d=\"M3 12h8a2 2 0 1 0 0 -4\" /><path d=\"M3 8h3a2 2 0 1 0 0 -4\" />");
    /// <summary>Tabler <c>wind-off</c>.</summary>
    public static global::Lumeo.IconSource WindOff => global::Lumeo.IconSource.Stroke("<path d=\"M5 8h3m4 0h1.5a2.5 2.5 0 1 0 -2.34 -3.24\" /><path d=\"M3 12h9\" /><path d=\"M16 12h2.5a2.5 2.5 0 0 1 1.801 4.282\" /><path d=\"M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>windmill</c>.</summary>
    public static global::Lumeo.IconSource Windmill => global::Lumeo.IconSource.Stroke("<path d=\"M12 12c2.76 0 5 -2.01 5 -4.5s-2.24 -4.5 -5 -4.5v9\" /><path d=\"M12 12c0 2.76 2.01 5 4.5 5s4.5 -2.24 4.5 -5h-9\" /><path d=\"M12 12c-2.76 0 -5 2.01 -5 4.5s2.24 4.5 5 4.5v-9\" /><path d=\"M12 12c0 -2.76 -2.01 -5 -4.5 -5s-4.5 2.24 -4.5 5h9\" />");
    /// <summary>Tabler <c>windmill-off</c>.</summary>
    public static global::Lumeo.IconSource WindmillOff => global::Lumeo.IconSource.Stroke("<path d=\"M15.061 11.06c1.18 -.824 1.939 -2.11 1.939 -3.56c0 -2.49 -2.24 -4.5 -5 -4.5v5\" /><path d=\"M12 12c0 2.76 2.01 5 4.5 5c.166 0 .33 -.01 .49 -.03m2.624 -1.36c.856 -.91 1.386 -2.19 1.386 -3.61h-5\" /><path d=\"M12 12c-2.76 0 -5 2.01 -5 4.5s2.24 4.5 5 4.5v-9\" /><path d=\"M6.981 7.033c-2.244 .285 -3.981 2.402 -3.981 4.967h9\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>window</c>.</summary>
    public static global::Lumeo.IconSource Window => global::Lumeo.IconSource.Stroke("<path d=\"M12 3c-3.866 0 -7 3.272 -7 7v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1 -1v-10c0 -3.728 -3.134 -7 -7 -7\" /><path d=\"M5 13l14 0\" /><path d=\"M12 3l0 18\" />");
    /// <summary>Tabler <c>window-maximize</c>.</summary>
    public static global::Lumeo.IconSource WindowMaximize => global::Lumeo.IconSource.Stroke("<path d=\"M3 17a1 1 0 0 1 1 -1h3a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1l0 -3\" /><path d=\"M4 12v-6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-6\" /><path d=\"M12 8h4v4\" /><path d=\"M16 8l-5 5\" />");
    /// <summary>Tabler <c>window-minimize</c>.</summary>
    public static global::Lumeo.IconSource WindowMinimize => global::Lumeo.IconSource.Stroke("<path d=\"M3 17a1 1 0 0 1 1 -1h3a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1l0 -3\" /><path d=\"M4 12v-6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-6\" /><path d=\"M15 13h-4v-4\" /><path d=\"M11 13l5 -5\" />");
    /// <summary>Tabler <c>window-off</c>.</summary>
    public static global::Lumeo.IconSource WindowOff => global::Lumeo.IconSource.Stroke("<path d=\"M6.166 6.19a6.903 6.903 0 0 0 -1.166 3.81v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1 -1v-1m0 -4v-5c0 -3.728 -3.134 -7 -7 -7a6.86 6.86 0 0 0 -3.804 1.158\" /><path d=\"M5 13h8m4 0h2\" /><path d=\"M12 3v5m0 4v9\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>windsock</c>.</summary>
    public static global::Lumeo.IconSource Windsock => global::Lumeo.IconSource.Stroke("<path d=\"M6 3v18\" /><path d=\"M6 11l12 -1v-4l-12 -1\" /><path d=\"M10 5.5v5\" /><path d=\"M14 6v4\" /><path d=\"M4 21h4\" />");
    /// <summary>Tabler <c>wiper</c>.</summary>
    public static global::Lumeo.IconSource Wiper => global::Lumeo.IconSource.Stroke("<path d=\"M11 18a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /><path d=\"M3 9l5.5 5.5a5 5 0 0 1 7 0l5.5 -5.5a12 12 0 0 0 -18 0\" /><path d=\"M12 18l-2.2 -12.8\" />");
    /// <summary>Tabler <c>wiper-wash</c>.</summary>
    public static global::Lumeo.IconSource WiperWash => global::Lumeo.IconSource.Stroke("<path d=\"M11 20a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /><path d=\"M3 11l5.5 5.5a5 5 0 0 1 7 0l5.5 -5.5a12 12 0 0 0 -18 0\" /><path d=\"M12 20l0 -14\" /><path d=\"M4 6a4 4 0 0 1 .4 -1.8\" /><path d=\"M7 2.1a4 4 0 0 1 2 0\" /><path d=\"M12 6a4 4 0 0 0 -.4 -1.8\" /><path d=\"M12 6a4 4 0 0 1 .4 -1.8\" /><path d=\"M15 2.1a4 4 0 0 1 2 0\" /><path d=\"M20 6a4 4 0 0 0 -.4 -1.8\" />");
    /// <summary>Tabler <c>woman</c>.</summary>
    public static global::Lumeo.IconSource Woman => global::Lumeo.IconSource.Stroke("<path d=\"M10 16v5\" /><path d=\"M14 16v5\" /><path d=\"M8 16h8l-2 -7h-4l-2 7\" /><path d=\"M5 11c1.667 -1.333 3.333 -2 5 -2\" /><path d=\"M19 11c-1.667 -1.333 -3.333 -2 -5 -2\" /><path d=\"M10 4a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />");
    /// <summary>Tabler <c>wood</c>.</summary>
    public static global::Lumeo.IconSource Wood => global::Lumeo.IconSource.Stroke("<path d=\"M6 5.5a6 2.5 0 1 0 12 0a6 2.5 0 1 0 -12 0\" /><path d=\"M18 5.5v4.626a1.415 1.415 0 0 1 1.683 2.18l-.097 .108l-1.586 1.586v4c0 1.61 -2.54 2.925 -5.725 3l-.275 0c-3.314 0 -6 -1.343 -6 -3v-2l-1.586 -1.586a1.414 1.414 0 0 1 1.586 -2.287v-6.627\" /><path d=\"M10 12.5v1.5\" /><path d=\"M14 16v1\" />");
    /// <summary>Tabler <c>world</c>.</summary>
    public static global::Lumeo.IconSource World => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h16.8\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a17 17 0 0 1 0 18\" />");
    /// <summary>Tabler <c>world-bolt</c>.</summary>
    public static global::Lumeo.IconSource WorldBolt => global::Lumeo.IconSource.Stroke("<path d=\"M20.985 12.52a9 9 0 1 0 -7.52 8.36\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h10.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3c2.313 3.706 3.07 7.856 2.27 12\" /><path d=\"M19 16l-2 3h4l-2 3\" />");
    /// <summary>Tabler <c>world-cancel</c>.</summary>
    public static global::Lumeo.IconSource WorldCancel => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -8.985 9\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.991 16.991 0 0 1 2.53 10.275\" /><path d=\"M16 19a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /><path d=\"M17 21l4 -4\" />");
    /// <summary>Tabler <c>world-check</c>.</summary>
    public static global::Lumeo.IconSource WorldCheck => global::Lumeo.IconSource.Stroke("<path d=\"M20.946 12.99a9 9 0 1 0 -9.46 7.995\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h13.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.997 16.997 0 0 1 2.311 12.001\" /><path d=\"M15 19l2 2l4 -4\" />");
    /// <summary>Tabler <c>world-code</c>.</summary>
    public static global::Lumeo.IconSource WorldCode => global::Lumeo.IconSource.Stroke("<path d=\"M20.942 13.02a9 9 0 1 0 -9.47 7.964\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3c2 3.206 2.837 6.913 2.508 10.537\" /><path d=\"M20 21l2 -2l-2 -2\" /><path d=\"M17 17l-2 2l2 2\" />");
    /// <summary>Tabler <c>world-cog</c>.</summary>
    public static global::Lumeo.IconSource WorldCog => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -8.979 9\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h8.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.992 16.992 0 0 1 2.522 10.376\" /><path d=\"M17.001 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /><path d=\"M19.001 15.5v1.5\" /><path d=\"M19.001 21v1.5\" /><path d=\"M22.032 17.25l-1.299 .75\" /><path d=\"M17.27 20l-1.3 .75\" /><path d=\"M15.97 17.25l1.3 .75\" /><path d=\"M20.733 20l1.3 .75\" />");
    /// <summary>Tabler <c>world-dollar</c>.</summary>
    public static global::Lumeo.IconSource WorldDollar => global::Lumeo.IconSource.Stroke("<path d=\"M20.876 10.51a9 9 0 1 0 -7.839 10.43\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.986 16.986 0 0 1 2.578 9.02\" /><path d=\"M21 15h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5\" /><path d=\"M19 21v1m0 -8v1\" />");
    /// <summary>Tabler <c>world-down</c>.</summary>
    public static global::Lumeo.IconSource WorldDown => global::Lumeo.IconSource.Stroke("<path d=\"M20.986 12.509a9 9 0 1 0 -8.455 8.476\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h10.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3c2.313 3.706 3.07 7.857 2.27 12\" /><path d=\"M19 16v6\" /><path d=\"M22 19l-3 3l-3 -3\" />");
    /// <summary>Tabler <c>world-download</c>.</summary>
    public static global::Lumeo.IconSource WorldDownload => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -9 9\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h8.4\" /><path d=\"M11.578 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3c1.719 2.755 2.5 5.876 2.5 9\" /><path d=\"M18 14v7m-3 -3l3 3l3 -3\" />");
    /// <summary>Tabler <c>world-exclamation</c>.</summary>
    public static global::Lumeo.IconSource WorldExclamation => global::Lumeo.IconSource.Stroke("<path d=\"M20.986 12.51a9 9 0 1 0 -5.71 7.873\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h10.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a17 17 0 0 1 0 18\" /><path d=\"M19 16v3\" /><path d=\"M19 22v.01\" />");
    /// <summary>Tabler <c>world-heart</c>.</summary>
    public static global::Lumeo.IconSource WorldHeart => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -9.679 8.974\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h6.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.983 16.983 0 0 1 2.556 8.136\" /><path d=\"M18 22l3.35 -3.284a2.143 2.143 0 0 0 .005 -3.071a2.242 2.242 0 0 0 -3.129 -.006l-.224 .22l-.223 -.22a2.242 2.242 0 0 0 -3.128 -.006a2.143 2.143 0 0 0 -.006 3.071l3.355 3.296\" />");
    /// <summary>Tabler <c>world-latitude</c>.</summary>
    public static global::Lumeo.IconSource WorldLatitude => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M4.6 7l14.8 0\" /><path d=\"M3 12l18 0\" /><path d=\"M4.6 17l14.8 0\" />");
    /// <summary>Tabler <c>world-longitude</c>.</summary>
    public static global::Lumeo.IconSource WorldLongitude => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M11.5 3a11.2 11.2 0 0 0 0 18\" /><path d=\"M12.5 3a11.2 11.2 0 0 1 0 18\" /><path d=\"M12 3l0 18\" />");
    /// <summary>Tabler <c>world-map</c>.</summary>
    public static global::Lumeo.IconSource WorldMap => global::Lumeo.IconSource.Stroke("<path d=\"M20 8h-2a2 2 0 0 0 -2 2a2 2 0 1 1 -4 0v-1a2 2 0 0 0 -2 -2h-1a2 2 0 0 1 -2 -2v-.5\" /><path d=\"M3 12h3a2 2 0 0 1 2 2v.5a1.5 1.5 0 0 0 1.5 1.5a1.5 1.5 0 0 1 1.5 1.5v3.25\" /><path d=\"M15 20.5v-3.5a2 2 0 0 1 2 -2h3.5\" /><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />");
    /// <summary>Tabler <c>world-minus</c>.</summary>
    public static global::Lumeo.IconSource WorldMinus => global::Lumeo.IconSource.Stroke("<path d=\"M20.483 15.006a9 9 0 1 0 -7.958 5.978\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h16.8\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.94 16.94 0 0 1 2.307 12\" /><path d=\"M16 19h6\" />");
    /// <summary>Tabler <c>world-off</c>.</summary>
    public static global::Lumeo.IconSource WorldOff => global::Lumeo.IconSource.Stroke("<path d=\"M5.657 5.615a9 9 0 1 0 12.717 12.739m1.672 -2.322a9 9 0 0 0 -12.066 -12.084\" /><path d=\"M3.6 9h5.4m4 0h7.4\" /><path d=\"M3.6 15h11.4m4 0h1.4\" /><path d=\"M11.5 3a17.001 17.001 0 0 0 -1.493 3.022m-.847 3.145c-.68 4.027 .1 8.244 2.34 11.833\" /><path d=\"M12.5 3a16.982 16.982 0 0 1 2.549 8.005m-.207 3.818a16.979 16.979 0 0 1 -2.342 6.177\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>world-pause</c>.</summary>
    public static global::Lumeo.IconSource WorldPause => global::Lumeo.IconSource.Stroke("<path d=\"M20.945 12.997a9 9 0 1 0 -7.928 7.945\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.992 16.992 0 0 1 2.51 10.526\" /><path d=\"M17 17v5\" /><path d=\"M21 17v5\" />");
    /// <summary>Tabler <c>world-pin</c>.</summary>
    public static global::Lumeo.IconSource WorldPin => global::Lumeo.IconSource.Stroke("<path d=\"M20.972 11.291a9 9 0 1 0 -8.322 9.686\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h8.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.986 16.986 0 0 1 2.578 9.018\" /><path d=\"M21.121 20.121a3 3 0 1 0 -4.242 0c.418 .419 1.125 1.045 2.121 1.879c1.051 -.89 1.759 -1.516 2.121 -1.879\" /><path d=\"M19 18v.01\" />");
    /// <summary>Tabler <c>world-plus</c>.</summary>
    public static global::Lumeo.IconSource WorldPlus => global::Lumeo.IconSource.Stroke("<path d=\"M20.985 12.518a9 9 0 1 0 -8.45 8.466\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h11.4\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.998 16.998 0 0 1 2.283 12.157\" /><path d=\"M16 19h6\" /><path d=\"M19 16v6\" />");
    /// <summary>Tabler <c>world-question</c>.</summary>
    public static global::Lumeo.IconSource WorldQuestion => global::Lumeo.IconSource.Stroke("<path d=\"M20.975 11.33a9 9 0 1 0 -5.673 9.043\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.988 16.988 0 0 1 2.57 9.518m-1.056 5.403a17 17 0 0 1 -1.514 3.079\" /><path d=\"M19 22v.01\" /><path d=\"M19 19a2.003 2.003 0 0 0 .914 -3.782a1.98 1.98 0 0 0 -2.414 .483\" />");
    /// <summary>Tabler <c>world-search</c>.</summary>
    public static global::Lumeo.IconSource WorldSearch => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -9 9\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h7.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.984 16.984 0 0 1 2.574 8.62\" /><path d=\"M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /><path d=\"M20.2 20.2l1.8 1.8\" />");
    /// <summary>Tabler <c>world-share</c>.</summary>
    public static global::Lumeo.IconSource WorldShare => global::Lumeo.IconSource.Stroke("<path d=\"M20.94 13.045a9 9 0 1 0 -8.953 7.955\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.4\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.991 16.991 0 0 1 2.529 10.294\" /><path d=\"M16 22l5 -5\" /><path d=\"M21 21.5v-4.5h-4.5\" />");
    /// <summary>Tabler <c>world-star</c>.</summary>
    public static global::Lumeo.IconSource WorldStar => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -9.968 8.948\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h6.4\" /><path d=\"M11.5 3a17.001 17.001 0 0 0 -1.886 13.802\" /><path d=\"M12.5 3a16.982 16.982 0 0 1 2.549 8.01\" /><path d=\"M17.8 20.817l-2.172 1.138a.392 .392 0 0 1 -.568 -.41l.415 -2.411l-1.757 -1.707a.389 .389 0 0 1 .217 -.665l2.428 -.352l1.086 -2.193a.392 .392 0 0 1 .702 0l1.086 2.193l2.428 .352a.39 .39 0 0 1 .217 .665l-1.757 1.707l.414 2.41a.39 .39 0 0 1 -.567 .411l-2.172 -1.138\" />");
    /// <summary>Tabler <c>world-up</c>.</summary>
    public static global::Lumeo.IconSource WorldUp => global::Lumeo.IconSource.Stroke("<path d=\"M20.985 12.52a9 9 0 1 0 -8.451 8.463\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h10.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.996 16.996 0 0 1 2.391 11.512\" /><path d=\"M19 22v-6\" /><path d=\"M22 19l-3 -3l-3 3\" />");
    /// <summary>Tabler <c>world-upload</c>.</summary>
    public static global::Lumeo.IconSource WorldUpload => global::Lumeo.IconSource.Stroke("<path d=\"M21 12a9 9 0 1 0 -9 9\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h8.4\" /><path d=\"M11.578 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3c1.719 2.755 2.5 5.876 2.5 9\" /><path d=\"M18 21v-7m3 3l-3 -3l-3 3\" />");
    /// <summary>Tabler <c>world-www</c>.</summary>
    public static global::Lumeo.IconSource WorldWww => global::Lumeo.IconSource.Stroke("<path d=\"M19.5 7a9 9 0 0 0 -7.5 -4a8.991 8.991 0 0 0 -7.484 4\" /><path d=\"M11.5 3a16.989 16.989 0 0 0 -1.826 4\" /><path d=\"M12.5 3a16.989 16.989 0 0 1 1.828 4\" /><path d=\"M19.5 17a9 9 0 0 1 -7.5 4a8.991 8.991 0 0 1 -7.484 -4\" /><path d=\"M11.5 21a16.989 16.989 0 0 1 -1.826 -4\" /><path d=\"M12.5 21a16.989 16.989 0 0 0 1.828 -4\" /><path d=\"M2 10l1 4l1.5 -4l1.5 4l1 -4\" /><path d=\"M17 10l1 4l1.5 -4l1.5 4l1 -4\" /><path d=\"M9.5 10l1 4l1.5 -4l1.5 4l1 -4\" />");
    /// <summary>Tabler <c>world-x</c>.</summary>
    public static global::Lumeo.IconSource WorldX => global::Lumeo.IconSource.Stroke("<path d=\"M20.929 13.131a9 9 0 1 0 -8.931 7.869\" /><path d=\"M3.6 9h16.8\" /><path d=\"M3.6 15h9.9\" /><path d=\"M11.5 3a17 17 0 0 0 0 18\" /><path d=\"M12.5 3a16.992 16.992 0 0 1 2.505 10.573\" /><path d=\"M22 22l-5 -5\" /><path d=\"M17 22l5 -5\" />");
    /// <summary>Tabler <c>wrecking-ball</c>.</summary>
    public static global::Lumeo.IconSource WreckingBall => global::Lumeo.IconSource.Stroke("<path d=\"M17 13a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /><path d=\"M2 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /><path d=\"M11 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /><path d=\"M13 19l-9 0\" /><path d=\"M4 15l9 0\" /><path d=\"M8 12v-5h2a3 3 0 0 1 3 3v5\" /><path d=\"M5 15v-2a1 1 0 0 1 1 -1h7\" /><path d=\"M19 11v-7l-6 7\" />");
    /// <summary>Tabler <c>writing</c>.</summary>
    public static global::Lumeo.IconSource Writing => global::Lumeo.IconSource.Stroke("<path d=\"M20 17v-12c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v12l2 2l2 -2\" /><path d=\"M16 7h4\" /><path d=\"M18 19h-13a2 2 0 1 1 0 -4h4a2 2 0 1 0 0 -4h-3\" />");
    /// <summary>Tabler <c>writing-off</c>.</summary>
    public static global::Lumeo.IconSource WritingOff => global::Lumeo.IconSource.Stroke("<path d=\"M16 7h4\" /><path d=\"M16 16v1l2 2l.5 -.5m1.5 -2.5v-11c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v7\" /><path d=\"M18 19h-13a2 2 0 1 1 0 -4h4a2 2 0 1 0 0 -4h-3\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>writing-sign</c>.</summary>
    public static global::Lumeo.IconSource WritingSign => global::Lumeo.IconSource.Stroke("<path d=\"M3 19c3.333 -2 5 -4 5 -6c0 -3 -1 -3 -2 -3s-2.032 1.085 -2 3c.034 2.048 1.658 2.877 2.5 4c1.5 2 2.5 2.5 3.5 1c.667 -1 1.167 -1.833 1.5 -2.5c1 2.333 2.333 3.5 4 3.5h2.5\" /><path d=\"M20 17v-12c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v12l2 2l2 -2\" /><path d=\"M16 7h4\" />");
    /// <summary>Tabler <c>writing-sign-off</c>.</summary>
    public static global::Lumeo.IconSource WritingSignOff => global::Lumeo.IconSource.Stroke("<path d=\"M3 19c3.333 -2 5 -4 5 -6c0 -3 -1 -3 -2 -3s-2.032 1.085 -2 3c.034 2.048 1.658 2.877 2.5 4c1.5 2 2.5 2.5 3.5 1c.667 -1 1.167 -1.833 1.5 -2.5c1 2.333 2.333 3.5 4 3.5h2.5\" /><path d=\"M16 16v1l2 2l.5 -.5m1.5 -2.5v-11c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v7\" /><path d=\"M16 7h4\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>x</c>.</summary>
    public static global::Lumeo.IconSource X => global::Lumeo.IconSource.Stroke("<path d=\"M18 6l-12 12\" /><path d=\"M6 6l12 12\" />");
    /// <summary>Tabler <c>x-mark</c>.</summary>
    public static global::Lumeo.IconSource XMark => global::Lumeo.IconSource.Stroke("<path d=\"M12 16l3.644 3.644a1.21 1.21 0 0 0 1.712 0l2.288 -2.288a1.21 1.21 0 0 0 0 -1.712l-3.644 -3.644l3.644 -3.644a1.21 1.21 0 0 0 0 -1.712l-2.288 -2.288a1.21 1.21 0 0 0 -1.712 0l-3.644 3.644l-3.644 -3.644a1.21 1.21 0 0 0 -1.712 0l-2.288 2.288a1.21 1.21 0 0 0 0 1.712l3.644 3.644l-3.644 3.644a1.21 1.21 0 0 0 0 1.712l2.288 2.288a1.21 1.21 0 0 0 1.712 0l3.644 -3.644\" />");
    /// <summary>Tabler <c>x-power-y</c>.</summary>
    public static global::Lumeo.IconSource XPowerY => global::Lumeo.IconSource.Stroke("<path d=\"M15 3l3 5.063\" /><path d=\"M5 12l6 6\" /><path d=\"M5 18l6 -6\" /><path d=\"M21 3l-4.8 9\" />");
    /// <summary>Tabler <c>xbox-a</c>.</summary>
    public static global::Lumeo.IconSource XboxA => global::Lumeo.IconSource.Stroke("<path d=\"M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9\" /><path d=\"M15 16l-3 -8l-3 8\" /><path d=\"M14 14h-4\" />");
    /// <summary>Tabler <c>xbox-b</c>.</summary>
    public static global::Lumeo.IconSource XboxB => global::Lumeo.IconSource.Stroke("<path d=\"M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9\" /><path d=\"M13 12a2 2 0 1 1 0 4h-3v-4\" /><path d=\"M13 12h-3\" /><path d=\"M13 12a2 2 0 1 0 0 -4h-3v4\" />");
    /// <summary>Tabler <c>xbox-x</c>.</summary>
    public static global::Lumeo.IconSource XboxX => global::Lumeo.IconSource.Stroke("<path d=\"M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9\" /><path d=\"M9 8l6 8\" /><path d=\"M15 8l-6 8\" />");
    /// <summary>Tabler <c>xbox-y</c>.</summary>
    public static global::Lumeo.IconSource XboxY => global::Lumeo.IconSource.Stroke("<path d=\"M12 21a9 9 0 0 0 9 -9a9 9 0 0 0 -9 -9a9 9 0 0 0 -9 9a9 9 0 0 0 9 9\" /><path d=\"M9 8l3 4\" /><path d=\"M15 8l-2.988 3.984l-.012 4.016\" />");
    /// <summary>Tabler <c>xd</c>.</summary>
    public static global::Lumeo.IconSource Xd => global::Lumeo.IconSource.Stroke("<path d=\"M6 8l4 8\" /><path d=\"M6 16l4 -8\" /><path d=\"M14 8v8h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-2\" />");
    /// <summary>Tabler <c>xxx</c>.</summary>
    public static global::Lumeo.IconSource Xxx => global::Lumeo.IconSource.Stroke("<path d=\"M10 8l4 8\" /><path d=\"M10 16l4 -8\" /><path d=\"M17 8l4 8\" /><path d=\"M17 16l4 -8\" /><path d=\"M3 8l4 8\" /><path d=\"M3 16l4 -8\" />");
    /// <summary>Tabler <c>yin-yang</c>.</summary>
    public static global::Lumeo.IconSource YinYang => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M12 3a4.5 4.5 0 0 0 0 9a4.5 4.5 0 0 1 0 9\" /><path d=\"M11.5 7.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0\" fill=\"currentColor\" /><path d=\"M11.5 16.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0\" fill=\"currentColor\" />");
    /// <summary>Tabler <c>yoga</c>.</summary>
    public static global::Lumeo.IconSource Yoga => global::Lumeo.IconSource.Stroke("<path d=\"M4 20h4l1.5 -3\" /><path d=\"M17 20l-1 -5h-5l1 -7\" /><path d=\"M4 10l4 -1l4 -1l4 1.5l4 1.5\" /><path d=\"M10.007 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />");
    /// <summary>Tabler <c>zeppelin</c>.</summary>
    public static global::Lumeo.IconSource Zeppelin => global::Lumeo.IconSource.Stroke("<path d=\"M13.5 4c4.694 0 8.5 2.686 8.5 6s-3.806 6 -8.5 6c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c2.78 -1.852 5.235 -2.778 7.365 -2.778\" /><path d=\"M10 15.5v4.5h6v-4\" />");
    /// <summary>Tabler <c>zeppelin-off</c>.</summary>
    public static global::Lumeo.IconSource ZeppelinOff => global::Lumeo.IconSource.Stroke("<path d=\"M15.773 15.783c-.723 .141 -1.486 .217 -2.273 .217c-2.13 0 -4.584 -.926 -7.364 -2.777l-2.136 1.777v-3.33a46.07 46.07 0 0 1 -2 -1.67a46.07 46.07 0 0 1 2 -1.67v-3.33l2.135 1.778c.13 -.087 .261 -.172 .39 -.256m2.564 -1.42c1.601 -.735 3.071 -1.102 4.411 -1.102c4.694 0 8.5 2.686 8.5 6c0 1.919 -1.276 3.627 -3.261 4.725\" /><path d=\"M10 15.5v4.5h6v-4\" /><path d=\"M3 3l18 18\" />");
    /// <summary>Tabler <c>zero-config</c>.</summary>
    public static global::Lumeo.IconSource ZeroConfig => global::Lumeo.IconSource.Stroke("<path d=\"M4 12a8 8 0 1 0 16 0a8 8 0 1 0 -16 0\" /><path d=\"M3 21l18 -18\" />");
    /// <summary>Tabler <c>zip</c>.</summary>
    public static global::Lumeo.IconSource Zip => global::Lumeo.IconSource.Stroke("<path d=\"M16 16v-8h2a2 2 0 1 1 0 4h-2\" /><path d=\"M12 8v8\" /><path d=\"M4 8h4l-4 8h4\" />");
    /// <summary>Tabler <c>zodiac-aquarius</c>.</summary>
    public static global::Lumeo.IconSource ZodiacAquarius => global::Lumeo.IconSource.Stroke("<path d=\"M3 10l3 -3l3 3l3 -3l3 3l3 -3l3 3\" /><path d=\"M3 17l3 -3l3 3l3 -3l3 3l3 -3l3 3\" />");
    /// <summary>Tabler <c>zodiac-aries</c>.</summary>
    public static global::Lumeo.IconSource ZodiacAries => global::Lumeo.IconSource.Stroke("<path d=\"M12 5a5 5 0 1 0 -4 8\" /><path d=\"M16 13a5 5 0 1 0 -4 -8\" /><path d=\"M12 21l0 -16\" />");
    /// <summary>Tabler <c>zodiac-cancer</c>.</summary>
    public static global::Lumeo.IconSource ZodiacCancer => global::Lumeo.IconSource.Stroke("<path d=\"M3 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /><path d=\"M15 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /><path d=\"M3 12a10 6.5 0 0 1 14 -6.5\" /><path d=\"M21 12a10 6.5 0 0 1 -14 6.5\" />");
    /// <summary>Tabler <c>zodiac-capricorn</c>.</summary>
    public static global::Lumeo.IconSource ZodiacCapricorn => global::Lumeo.IconSource.Stroke("<path d=\"M4 4a3 3 0 0 1 3 3v9\" /><path d=\"M7 7a3 3 0 0 1 6 0v11a3 3 0 0 1 -3 3\" /><path d=\"M13 17a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" />");
    /// <summary>Tabler <c>zodiac-gemini</c>.</summary>
    public static global::Lumeo.IconSource ZodiacGemini => global::Lumeo.IconSource.Stroke("<path d=\"M3 3a21 21 0 0 0 18 0\" /><path d=\"M3 21a21 21 0 0 1 18 0\" /><path d=\"M7 4.5l0 15\" /><path d=\"M17 4.5l0 15\" />");
    /// <summary>Tabler <c>zodiac-leo</c>.</summary>
    public static global::Lumeo.IconSource ZodiacLeo => global::Lumeo.IconSource.Stroke("<path d=\"M13 17a4 4 0 1 0 8 0\" /><path d=\"M3 16a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /><path d=\"M7 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\" /><path d=\"M7 7c0 3 2 5 2 9\" /><path d=\"M15 7c0 4 -2 6 -2 10\" />");
    /// <summary>Tabler <c>zodiac-libra</c>.</summary>
    public static global::Lumeo.IconSource ZodiacLibra => global::Lumeo.IconSource.Stroke("<path d=\"M5 20l14 0\" /><path d=\"M5 17h5v-.3a7 7 0 1 1 4 0v.3h5\" />");
    /// <summary>Tabler <c>zodiac-pisces</c>.</summary>
    public static global::Lumeo.IconSource ZodiacPisces => global::Lumeo.IconSource.Stroke("<path d=\"M5 3a21 21 0 0 1 0 18\" /><path d=\"M19 3a21 21 0 0 0 0 18\" /><path d=\"M5 12l14 0\" />");
    /// <summary>Tabler <c>zodiac-sagittarius</c>.</summary>
    public static global::Lumeo.IconSource ZodiacSagittarius => global::Lumeo.IconSource.Stroke("<path d=\"M4 20l16 -16\" /><path d=\"M13 4h7v7\" /><path d=\"M6.5 12.5l5 5\" />");
    /// <summary>Tabler <c>zodiac-scorpio</c>.</summary>
    public static global::Lumeo.IconSource ZodiacScorpio => global::Lumeo.IconSource.Stroke("<path d=\"M3 4a2 2 0 0 1 2 2v9\" /><path d=\"M5 6a2 2 0 0 1 4 0v9\" /><path d=\"M9 6a2 2 0 0 1 4 0v10a3 3 0 0 0 3 3h5l-3 -3m0 6l3 -3\" />");
    /// <summary>Tabler <c>zodiac-taurus</c>.</summary>
    public static global::Lumeo.IconSource ZodiacTaurus => global::Lumeo.IconSource.Stroke("<path d=\"M6 3a6 6 0 0 0 12 0\" /><path d=\"M6 15a6 6 0 1 0 12 0a6 6 0 1 0 -12 0\" />");
    /// <summary>Tabler <c>zodiac-virgo</c>.</summary>
    public static global::Lumeo.IconSource ZodiacVirgo => global::Lumeo.IconSource.Stroke("<path d=\"M3 4a2 2 0 0 1 2 2v9\" /><path d=\"M5 6a2 2 0 0 1 4 0v9\" /><path d=\"M9 6a2 2 0 0 1 4 0v10a7 5 0 0 0 7 5\" /><path d=\"M12 21a7 5 0 0 0 7 -5v-2a3 3 0 0 0 -6 0\" />");
    /// <summary>Tabler <c>zoom</c>.</summary>
    public static global::Lumeo.IconSource Zoom => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" />");
    /// <summary>Tabler <c>zoom-cancel</c>.</summary>
    public static global::Lumeo.IconSource ZoomCancel => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M8 8l4 4\" /><path d=\"M12 8l-4 4\" /><path d=\"M21 21l-6 -6\" />");
    /// <summary>Tabler <c>zoom-check</c>.</summary>
    public static global::Lumeo.IconSource ZoomCheck => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" /><path d=\"M7 10l2 2l4 -4\" />");
    /// <summary>Tabler <c>zoom-code</c>.</summary>
    public static global::Lumeo.IconSource ZoomCode => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" /><path d=\"M8 8l-2 2l2 2\" /><path d=\"M12 8l2 2l-2 2\" />");
    /// <summary>Tabler <c>zoom-exclamation</c>.</summary>
    public static global::Lumeo.IconSource ZoomExclamation => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" /><path d=\"M10 13v.01\" /><path d=\"M10 7v3\" />");
    /// <summary>Tabler <c>zoom-in</c>.</summary>
    public static global::Lumeo.IconSource ZoomIn => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M7 10l6 0\" /><path d=\"M10 7l0 6\" /><path d=\"M21 21l-6 -6\" />");
    /// <summary>Tabler <c>zoom-in-area</c>.</summary>
    public static global::Lumeo.IconSource ZoomInArea => global::Lumeo.IconSource.Stroke("<path d=\"M15 13v4\" /><path d=\"M13 15h4\" /><path d=\"M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0\" /><path d=\"M22 22l-3 -3\" /><path d=\"M6 18h-1a2 2 0 0 1 -2 -2v-1\" /><path d=\"M3 11v-1\" /><path d=\"M3 6v-1a2 2 0 0 1 2 -2h1\" /><path d=\"M10 3h1\" /><path d=\"M15 3h1a2 2 0 0 1 2 2v1\" />");
    /// <summary>Tabler <c>zoom-money</c>.</summary>
    public static global::Lumeo.IconSource ZoomMoney => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" /><path d=\"M12 7h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5\" /><path d=\"M10 13v1m0 -8v1\" />");
    /// <summary>Tabler <c>zoom-out</c>.</summary>
    public static global::Lumeo.IconSource ZoomOut => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M7 10l6 0\" /><path d=\"M21 21l-6 -6\" />");
    /// <summary>Tabler <c>zoom-out-area</c>.</summary>
    public static global::Lumeo.IconSource ZoomOutArea => global::Lumeo.IconSource.Stroke("<path d=\"M13 15h4\" /><path d=\"M10 15a5 5 0 1 0 10 0a5 5 0 1 0 -10 0\" /><path d=\"M22 22l-3 -3\" /><path d=\"M6 18h-1a2 2 0 0 1 -2 -2v-1\" /><path d=\"M3 11v-1\" /><path d=\"M3 6v-1a2 2 0 0 1 2 -2h1\" /><path d=\"M10 3h1\" /><path d=\"M15 3h1a2 2 0 0 1 2 2v1\" />");
    /// <summary>Tabler <c>zoom-pan</c>.</summary>
    public static global::Lumeo.IconSource ZoomPan => global::Lumeo.IconSource.Stroke("<path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" /><path d=\"M17 17l-2.5 -2.5\" /><path d=\"M10 4l2 -2l2 2\" /><path d=\"M20 10l2 2l-2 2\" /><path d=\"M4 10l-2 2l2 2\" /><path d=\"M10 20l2 2l2 -2\" />");
    /// <summary>Tabler <c>zoom-question</c>.</summary>
    public static global::Lumeo.IconSource ZoomQuestion => global::Lumeo.IconSource.Stroke("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M21 21l-6 -6\" /><path d=\"M10 13l0 .01\" /><path d=\"M10 10a1.5 1.5 0 1 0 -1.14 -2.474\" />");
    /// <summary>Tabler <c>zoom-replace</c>.</summary>
    public static global::Lumeo.IconSource ZoomReplace => global::Lumeo.IconSource.Stroke("<path d=\"M21 21l-6 -6\" /><path d=\"M3.291 8a7 7 0 0 1 5.077 -4.806a7.021 7.021 0 0 1 8.242 4.403\" /><path d=\"M17 4v4h-4\" /><path d=\"M16.705 12a7 7 0 0 1 -5.074 4.798a7.021 7.021 0 0 1 -8.241 -4.403\" /><path d=\"M3 16v-4h4\" />");
    /// <summary>Tabler <c>zoom-reset</c>.</summary>
    public static global::Lumeo.IconSource ZoomReset => global::Lumeo.IconSource.Stroke("<path d=\"M21 21l-6 -6\" /><path d=\"M3.268 12.043a7.017 7.017 0 0 0 6.634 4.957a7.012 7.012 0 0 0 7.043 -6.131a7 7 0 0 0 -5.314 -7.672a7.021 7.021 0 0 0 -8.241 4.403\" /><path d=\"M3 4v4h4\" />");
    /// <summary>Tabler <c>zoom-scan</c>.</summary>
    public static global::Lumeo.IconSource ZoomScan => global::Lumeo.IconSource.Stroke("<path d=\"M8 11a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" /><path d=\"M16 16l-2.5 -2.5\" /><path d=\"M3 7v-2a2 2 0 0 1 2 -2h2\" /><path d=\"M3 17v2a2 2 0 0 0 2 2h2\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" /><path d=\"M17 21h2a2 2 0 0 0 2 -2v-2\" />");
    /// <summary>Tabler <c>zzz</c>.</summary>
    public static global::Lumeo.IconSource Zzz => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h6l-6 8h6\" /><path d=\"M14 4h6l-6 8h6\" />");
    /// <summary>Tabler <c>zzz-off</c>.</summary>
    public static global::Lumeo.IconSource ZzzOff => global::Lumeo.IconSource.Stroke("<path d=\"M4 12h6l-6 8h6\" /><path d=\"M14 4h6l-5.146 6.862m1.146 1.138h4\" /><path d=\"M3 3l18 18\" />");
}
